import Foundation

struct ChineseCuisineFoodItems {
    static let foods: [FoodItem] = [
        // Sweet and Sour Pork
        FoodItem(
            id: UUID(),
            name: "Sweet and Sour Pork",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 345,
                protein: 22.5,
                carbohydrates: 28,
                fat: 18.8,
                fiber: 2.5,
                sugar: 22.5,
                vitaminA: 125,
                vitaminC: 35,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 8,
                thiamin: 0.45,
                riboflavin: 0.28,
                niacin: 6.8,
                vitaminB6: 0.48,
                vitaminB12: 2.5,
                folate: 22,
                calcium: 85,
                iron: 2.8,
                magnesium: 42,
                phosphorus: 225,
                potassium: 385,
                sodium: 685,
                zinc: 3.8,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 75
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy pork pieces in tangy sweet and sour sauce with pineapple and peppers",
            nameFr: "Porc Aigre-Doux",
            nameEs: "Cerdo Agridulce",
            nameHe: "חזיר חמוץ מתוק",
            notesFr: "Morceaux de porc croustillants dans une sauce aigre-douce avec ananas et poivrons",
            notesEs: "Trozos de cerdo crujientes en salsa agridulce con piña y pimientos",
            notesHe: "חתיכות חזיר פריכות ברוטב חמוץ מתוק עם אננס ופלפלים"
        ),
        
        // Kung Pao Chicken
        FoodItem(
            id: UUID(),
            name: "Kung Pao Chicken",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 26.5,
                carbohydrates: 12,
                fat: 15.8,
                fiber: 3.2,
                sugar: 8.5,
                vitaminA: 85,
                vitaminC: 25,
                vitaminD: 0.5,
                vitaminE: 3.8,
                vitaminK: 12,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 9.2,
                vitaminB6: 0.55,
                vitaminB12: 2.8,
                folate: 28,
                calcium: 65,
                iron: 2.5,
                magnesium: 85,
                phosphorus: 245,
                potassium: 485,
                sodium: 785,
                zinc: 3.5,
                selenium: 25.8,
                omega3: 1.2,
                omega6: 4.8,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Spicy stir-fried chicken with peanuts, vegetables, and chili peppers",
            nameFr: "Poulet Kung Pao",
            nameEs: "Pollo Kung Pao",
            nameHe: "עוף קונג פאו",
            notesFr: "Poulet sauté épicé avec cacahuètes, légumes et piments",
            notesEs: "Pollo salteado picante con cacahuetes, verduras y chiles",
            notesHe: "עוף מוקפץ חריף עם בוטנים, ירקות ופלפלי צ'ילי"
        ),
        
        // Peking Duck
        FoodItem(
            id: UUID(),
            name: "Peking Duck",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 24.8,
                carbohydrates: 8,
                fat: 28.5,
                fiber: 1.2,
                sugar: 4.5,
                vitaminA: 145,
                vitaminC: 8,
                vitaminD: 1.2,
                vitaminE: 2.8,
                vitaminK: 15,
                thiamin: 0.22,
                riboflavin: 0.35,
                niacin: 8.8,
                vitaminB6: 0.42,
                vitaminB12: 3.2,
                folate: 18,
                calcium: 45,
                iron: 3.8,
                magnesium: 35,
                phosphorus: 225,
                potassium: 285,
                sodium: 585,
                zinc: 4.2,
                selenium: 28.5,
                omega3: 0.8,
                omega6: 3.5,
                cholesterol: 95
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy roasted duck with thin pancakes, scallions, and hoisin sauce",
            nameFr: "Canard Laqué de Pékin",
            nameEs: "Pato Pequinés",
            nameHe: "ברווז פקין",
            notesFr: "Canard rôti croustillant avec crêpes fines, oignons verts et sauce hoisin",
            notesEs: "Pato asado crujiente con panqueques finos, cebolletas y salsa hoisin",
            notesHe: "ברווז צלוי פריך עם פנקייקים דקים, בצל ירוק ורוטב הויסין"
        ),
        
        // Fried Rice
        FoodItem(
            id: UUID(),
            name: "Yang Chow Fried Rice",
            category: .grains,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.5,
                carbohydrates: 42,
                fat: 8.8,
                fiber: 2.8,
                sugar: 4.2,
                vitaminA: 185,
                vitaminC: 15,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.28,
                riboflavin: 0.25,
                niacin: 4.8,
                vitaminB6: 0.32,
                vitaminB12: 1.5,
                folate: 45,
                calcium: 85,
                iron: 2.2,
                magnesium: 55,
                phosphorus: 185,
                potassium: 285,
                sodium: 685,
                zinc: 2.8,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 185
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Wok-fried rice with eggs, shrimp, char siu pork, and vegetables",
            nameFr: "Riz Frit de Yang Chow",
            nameEs: "Arroz Frito Yang Chow",
            nameHe: "אורז מטוגן יאנג צ'או",
            notesFr: "Riz sauté au wok avec œufs, crevettes, porc char siu et légumes",
            notesEs: "Arroz salteado en wok con huevos, camarones, cerdo char siu y verduras",
            notesHe: "אורז מוקפץ בוואוק עם ביצים, שרימפס, חזיר צ'אר סיו וירקות"
        ),
        
        // Mapo Tofu
        FoodItem(
            id: UUID(),
            name: "Mapo Tofu",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 16.8,
                carbohydrates: 8,
                fat: 14.5,
                fiber: 2.8,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 15,
                thiamin: 0.15,
                riboflavin: 0.18,
                niacin: 2.8,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 65,
                calcium: 285,
                iron: 3.8,
                magnesium: 85,
                phosphorus: 185,
                potassium: 385,
                sodium: 785,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.8,
                omega6: 4.2,
                cholesterol: 25
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Silky tofu in spicy Sichuan sauce with ground pork and fermented beans",
            nameFr: "Tofu Mapo",
            nameEs: "Tofu Mapo",
            nameHe: "טופו מאפו",
            notesFr: "Tofu soyeux dans une sauce épicée du Sichuan avec porc haché et haricots fermentés",
            notesEs: "Tofu sedoso en salsa picante de Sichuan con cerdo molido y frijoles fermentados",
            notesHe: "טופו משיי ברוטב סצ'ואן חריף עם חזיר טחון ושעועית מותססת"
        ),
        
        // Dim Sum - Har Gow
        FoodItem(
            id: UUID(),
            name: "Har Gow (Shrimp Dumplings)",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 12.8,
                carbohydrates: 18,
                fat: 4.8,
                fiber: 1.2,
                sugar: 2.5,
                vitaminA: 45,
                vitaminC: 8,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 5,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 2.2,
                vitaminB6: 0.18,
                vitaminB12: 1.8,
                folate: 25,
                calcium: 85,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 145,
                potassium: 185,
                sodium: 485,
                zinc: 1.8,
                selenium: 22.5,
                omega3: 0.5,
                omega6: 1.2,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Translucent steamed dumplings filled with fresh shrimp",
            nameFr: "Har Gow (Raviolis aux Crevettes)",
            nameEs: "Har Gow (Dumplings de Camarón)",
            nameHe: "האר גאו (כיסוני שרימפס)",
            notesFr: "Raviolis vapeur translucides farcis aux crevettes fraîches",
            notesEs: "Dumplings al vapor translúcidos rellenos de camarones frescos",
            notesHe: "כיסונים מאודים שקופים ממולאים שרימפס טרי"
        ),
        
        // Chow Mein
        FoodItem(
            id: UUID(),
            name: "Chicken Chow Mein",
            category: .grains,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 18.5,
                carbohydrates: 38,
                fat: 12.8,
                fiber: 4.2,
                sugar: 6.8,
                vitaminA: 125,
                vitaminC: 25,
                vitaminD: 0.3,
                vitaminE: 2.8,
                vitaminK: 35,
                thiamin: 0.25,
                riboflavin: 0.18,
                niacin: 6.8,
                vitaminB6: 0.42,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 65,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 185,
                potassium: 385,
                sodium: 785,
                zinc: 2.8,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 3.8,
                cholesterol: 65
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Stir-fried wheat noodles with chicken, vegetables, and soy sauce",
            nameFr: "Chow Mein au Poulet",
            nameEs: "Chow Mein de Pollo",
            nameHe: "צ'או מיין עוף",
            notesFr: "Nouilles de blé sautées avec poulet, légumes et sauce soja",
            notesEs: "Fideos de trigo salteados con pollo, verduras y salsa de soja",
            notesHe: "אטריות חיטה מוקפצות עם עוף, ירקות ורוטב סויה"
        ),
        
        // General Tso's Chicken
        FoodItem(
            id: UUID(),
            name: "General Tso's Chicken",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 365,
                protein: 24.5,
                carbohydrates: 32,
                fat: 18.8,
                fiber: 2.2,
                sugar: 26.5,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0.5,
                vitaminE: 2.2,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 8.5,
                vitaminB6: 0.52,
                vitaminB12: 2.5,
                folate: 22,
                calcium: 65,
                iron: 2.5,
                magnesium: 42,
                phosphorus: 225,
                potassium: 285,
                sodium: 885,
                zinc: 3.5,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 4.8,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy battered chicken in sweet and spicy glaze",
            nameFr: "Poulet du Général Tso",
            nameEs: "Pollo del General Tso",
            nameHe: "עוף הגנרל צו",
            notesFr: "Poulet pané croustillant dans un glaçage sucré et épicé",
            notesEs: "Pollo empanizado crujiente en glaseado dulce y picante",
            notesHe: "עוף בציפוי פריך בגלייז מתוק וחריף"
        ),
        
        // Hot Pot
        FoodItem(
            id: UUID(),
            name: "Sichuan Hot Pot",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 22.8,
                carbohydrates: 12,
                fat: 16.8,
                fiber: 3.8,
                sugar: 5.2,
                vitaminA: 185,
                vitaminC: 45,
                vitaminD: 0.8,
                vitaminE: 2.8,
                vitaminK: 45,
                thiamin: 0.25,
                riboflavin: 0.28,
                niacin: 6.8,
                vitaminB6: 0.45,
                vitaminB12: 2.8,
                folate: 65,
                calcium: 125,
                iron: 4.2,
                magnesium: 85,
                phosphorus: 225,
                potassium: 585,
                sodium: 985,
                zinc: 3.8,
                selenium: 22.5,
                omega3: 0.5,
                omega6: 3.2,
                cholesterol: 75
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Spicy communal broth with mixed meats, vegetables, and tofu",
            nameFr: "Fondue Chinoise du Sichuan",
            nameEs: "Hot Pot de Sichuan",
            nameHe: "סיר חם סצ'ואן",
            notesFr: "Bouillon communal épicé avec viandes mélangées, légumes et tofu",
            notesEs: "Caldo comunal picante con carnes mixtas, verduras y tofu",
            notesHe: "מרק קהילתי חריף עם בשרים מעורבים, ירקות וטופו"
        ),
        
        // Wontons
        FoodItem(
            id: UUID(),
            name: "Wonton Soup",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 205,
                protein: 14.8,
                carbohydrates: 22,
                fat: 6.8,
                fiber: 2.2,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 15,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 3.8,
                vitaminB6: 0.25,
                vitaminB12: 1.8,
                folate: 35,
                calcium: 85,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 165,
                potassium: 285,
                sodium: 685,
                zinc: 2.2,
                selenium: 15.8,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 65
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Clear broth with pork and shrimp filled wontons and vegetables",
            nameFr: "Soupe aux Wontons",
            nameEs: "Sopa de Wontons",
            nameHe: "מרק וונטון",
            notesFr: "Bouillon clair avec wontons farcis au porc et aux crevettes et légumes",
            notesEs: "Caldo claro con wontons rellenos de cerdo y camarones y verduras",
            notesHe: "מרק צלול עם וונטון ממולא חזיר ושרימפס וירקות"
        ),
        
        // Ma Po Eggplant
        FoodItem(
            id: UUID(),
            name: "Ma Po Eggplant",
            category: .vegetables,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.8,
                carbohydrates: 18,
                fat: 10.5,
                fiber: 6.8,
                sugar: 8.5,
                vitaminA: 45,
                vitaminC: 25,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 12,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 2.2,
                vitaminB6: 0.25,
                vitaminB12: 0,
                folate: 45,
                calcium: 65,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 85,
                potassium: 485,
                sodium: 685,
                zinc: 1.8,
                selenium: 5.8,
                omega3: 0.2,
                omega6: 3.8,
                cholesterol: 0
            ),
            servingSize: 160,
            servingUnit: "g",
            isCustom: true,
            notes: "Silky eggplant in spicy Sichuan sauce with fermented black beans",
            nameFr: "Aubergine Ma Po",
            nameEs: "Berenjena Ma Po",
            nameHe: "חציל מא פו",
            notesFr: "Aubergine soyeuse dans une sauce épicée du Sichuan avec haricots noirs fermentés",
            notesEs: "Berenjena sedosa en salsa picante de Sichuan con frijoles negros fermentados",
            notesHe: "חציל משיי ברוטב סצ'ואן חריף עם שעועית שחורה מותססת"
        ),
        
        // Spring Rolls
        FoodItem(
            id: UUID(),
            name: "Spring Rolls",
            category: .snacks,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 8.5,
                carbohydrates: 28,
                fat: 11.8,
                fiber: 3.8,
                sugar: 4.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 25,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 45,
                calcium: 85,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 125,
                potassium: 285,
                sodium: 485,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.5,
                omega6: 4.8,
                cholesterol: 0
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy fried rolls filled with vegetables and sometimes meat",
            nameFr: "Rouleaux de Printemps",
            nameEs: "Rollitos Primavera",
            nameHe: "רולי אביב",
            notesFr: "Rouleaux frits croustillants farcis de légumes et parfois de viande",
            notesEs: "Rollos fritos crujientes rellenos de verduras y a veces carne",
            notesHe: "רולים מטוגנים פריכים ממולאים ירקות ולפעמים בשר"
        ),
        
        // Beef and Broccoli
        FoodItem(
            id: UUID(),
            name: "Beef and Broccoli",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 265,
                protein: 24.8,
                carbohydrates: 12,
                fat: 14.5,
                fiber: 4.2,
                sugar: 6.8,
                vitaminA: 185,
                vitaminC: 85,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 125,
                thiamin: 0.18,
                riboflavin: 0.25,
                niacin: 6.8,
                vitaminB6: 0.45,
                vitaminB12: 3.8,
                folate: 85,
                calcium: 125,
                iron: 3.8,
                magnesium: 65,
                phosphorus: 225,
                potassium: 585,
                sodium: 685,
                zinc: 4.8,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Tender beef slices stir-fried with fresh broccoli in oyster sauce",
            nameFr: "Bœuf aux Brocolis",
            nameEs: "Carne con Brócoli",
            nameHe: "בקר וברוקולי",
            notesFr: "Tranches de bœuf tendres sautées avec brocolis frais dans une sauce aux huîtres",
            notesEs: "Rebanadas tiernas de carne salteadas con brócoli fresco en salsa de ostras",
            notesHe: "פרוסות בקר רכות מוקפצות עם ברוקולי טרי ברוטב צדפות"
        ),
        
        // Dan Dan Noodles
        FoodItem(
            id: UUID(),
            name: "Dan Dan Noodles",
            category: .grains,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 16.8,
                carbohydrates: 45,
                fat: 16.8,
                fiber: 4.2,
                sugar: 6.8,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 3.8,
                vitaminK: 18,
                thiamin: 0.28,
                riboflavin: 0.18,
                niacin: 5.8,
                vitaminB6: 0.32,
                vitaminB12: 0.8,
                folate: 65,
                calcium: 125,
                iron: 3.2,
                magnesium: 85,
                phosphorus: 185,
                potassium: 385,
                sodium: 885,
                zinc: 2.8,
                selenium: 15.8,
                omega3: 0.8,
                omega6: 6.8,
                cholesterol: 25
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Sichuan noodles with spicy sesame sauce, ground pork, and preserved vegetables",
            nameFr: "Nouilles Dan Dan",
            nameEs: "Fideos Dan Dan",
            nameHe: "אטריות דן דן",
            notesFr: "Nouilles du Sichuan avec sauce au sésame épicée, porc haché et légumes conservés",
            notesEs: "Fideos de Sichuan con salsa de sésamo picante, cerdo molido y verduras conservadas",
            notesHe: "אטריות סצ'ואן עם רוטב שומשום חריף, חזיר טחון וירקות כבושים"
        ),
        
        // Orange Chicken
        FoodItem(
            id: UUID(),
            name: "Orange Chicken",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 345,
                protein: 22.8,
                carbohydrates: 35,
                fat: 15.8,
                fiber: 2.2,
                sugar: 28.5,
                vitaminA: 125,
                vitaminC: 65,
                vitaminD: 0.5,
                vitaminE: 2.8,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 8.8,
                vitaminB6: 0.52,
                vitaminB12: 2.5,
                folate: 25,
                calcium: 85,
                iron: 2.5,
                magnesium: 42,
                phosphorus: 225,
                potassium: 385,
                sodium: 785,
                zinc: 3.5,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 4.2,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy battered chicken in sweet and tangy orange glaze",
            nameFr: "Poulet à l'Orange",
            nameEs: "Pollo a la Naranja",
            nameHe: "עוף תפוז",
            notesFr: "Poulet pané croustillant dans un glaçage sucré et acidulé à l'orange",
            notesEs: "Pollo empanizado crujiente en glaseado dulce y ácido de naranja",
            notesHe: "עוף בציפוי פריך בגלייז תפוז מתוק וחמצמץ"
        ),
        
        // Char Siu
        FoodItem(
            id: UUID(),
            name: "Char Siu (BBQ Pork)",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 26.5,
                carbohydrates: 12,
                fat: 19.8,
                fiber: 0.8,
                sugar: 10.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 5,
                thiamin: 0.48,
                riboflavin: 0.32,
                niacin: 7.8,
                vitaminB6: 0.52,
                vitaminB12: 2.8,
                folate: 18,
                calcium: 45,
                iron: 2.8,
                magnesium: 35,
                phosphorus: 245,
                potassium: 385,
                sodium: 785,
                zinc: 4.2,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Cantonese barbecued pork with sweet and savory glaze",
            nameFr: "Char Siu (Porc BBQ)",
            nameEs: "Char Siu (Cerdo BBQ)",
            nameHe: "צ'אר סיו (חזיר בברביקיו)",
            notesFr: "Porc grillé cantonais avec glaçage sucré et salé",
            notesEs: "Cerdo a la parrilla cantonés con glaseado dulce y salado",
            notesHe: "חזיר צלוי קנטונזי עם גלייז מתוק ומלוח"
        ),
        
        // Congee
        FoodItem(
            id: UUID(),
            name: "Chicken Congee",
            category: .grains,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 12.5,
                carbohydrates: 22,
                fat: 3.8,
                fiber: 1.2,
                sugar: 2.5,
                vitaminA: 45,
                vitaminC: 5,
                vitaminD: 0.3,
                vitaminE: 0.8,
                vitaminK: 5,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 4.8,
                vitaminB6: 0.28,
                vitaminB12: 1.8,
                folate: 25,
                calcium: 65,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 145,
                potassium: 285,
                sodium: 585,
                zinc: 2.2,
                selenium: 18.5,
                omega3: 0.2,
                omega6: 1.2,
                cholesterol: 45
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Silky rice porridge with shredded chicken and ginger",
            nameFr: "Congee au Poulet",
            nameEs: "Congee de Pollo",
            nameHe: "קונג'י עוף",
            notesFr: "Bouillie de riz soyeuse avec poulet effiloché et gingembre",
            notesEs: "Papilla de arroz sedosa con pollo desmenuzado y jengibre",
            notesHe: "דייסת אורז משיית עם עוף מרוטש וזנגביל"
        ),
        
        // Tea Egg
        FoodItem(
            id: UUID(),
            name: "Chinese Tea Egg",
            category: .protein,
            cuisineType: .chinese,
            nutritionalInfo: NutritionalInfo(
                calories: 85,
                protein: 6.8,
                carbohydrates: 1,
                fat: 5.8,
                fiber: 0,
                sugar: 0.8,
                vitaminA: 85,
                vitaminC: 0,
                vitaminD: 1.2,
                vitaminE: 0.8,
                vitaminK: 2,
                thiamin: 0.05,
                riboflavin: 0.28,
                niacin: 0.8,
                vitaminB6: 0.08,
                vitaminB12: 1.2,
                folate: 25,
                calcium: 45,
                iron: 1.2,
                magnesium: 12,
                phosphorus: 125,
                potassium: 85,
                sodium: 285,
                zinc: 0.8,
                selenium: 18.5,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 185
            ),
            servingSize: 60,
            servingUnit: "g",
            isCustom: true,
            notes: "Marbled hard-boiled egg stewed in spiced tea and soy sauce",
            nameFr: "Œuf au Thé Chinois",
            nameEs: "Huevo de Té Chino",
            nameHe: "ביצת תה סינית",
            notesFr: "Œuf dur marbré mijoté dans du thé épicé et de la sauce soja",
            notesEs: "Huevo duro jaspeado cocido en té especiado y salsa de soja",
            notesHe: "ביצה קשה מנומרת מבושלת בתה מתובל ורוטב סויה"
        ),
        
        // Sesame Balls
        FoodItem(
            id: UUID(),
            name: "Sesame Balls",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 5.8,
                carbohydrates: 38,
                fat: 12.8,
                fiber: 2.2,
                sugar: 18.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 5,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 2.2,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 25,
                calcium: 185,
                iron: 2.2,
                magnesium: 85,
                phosphorus: 125,
                potassium: 185,
                sodium: 185,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 4.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Deep-fried glutinous rice balls filled with sweet red bean paste",
            nameFr: "Boules de Sésame",
            nameEs: "Bolas de Sésamo",
            nameHe: "כדורי שומשום",
            notesFr: "Boules de riz glutineux frites farcies de pâte de haricots rouges sucrée",
            notesEs: "Bolas de arroz glutinoso fritas rellenas de pasta dulce de frijoles rojos",
            notesHe: "כדורי אורז דביק מטוגנים ממולאים ממרח שעועית אדומה מתוק"
        ),
        
        // Hot and Sour Soup
        FoodItem(
            id: UUID(),
            name: "Hot and Sour Soup",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 125,
                protein: 8.5,
                carbohydrates: 12,
                fat: 4.8,
                fiber: 2.8,
                sugar: 4.5,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 12,
                thiamin: 0.12,
                riboflavin: 0.15,
                niacin: 2.8,
                vitaminB6: 0.18,
                vitaminB12: 0.5,
                folate: 35,
                calcium: 125,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 125,
                potassium: 285,
                sodium: 785,
                zinc: 1.8,
                selenium: 12.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 35
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Spicy and tangy soup with tofu, mushrooms, and egg ribbons",
            nameFr: "Soupe Aigre-Piquante",
            nameEs: "Sopa Agripicante",
            nameHe: "מרק חריף וחמוץ",
            notesFr: "Soupe épicée et acidulée avec tofu, champignons et rubans d'œuf",
            notesEs: "Sopa picante y ácida con tofu, hongos y cintas de huevo",
            notesHe: "מרק חריף וחמצמץ עם טופו, פטריות ורצועות ביצה"
        )
    ]
}