import Foundation

struct PastaFoodItems {
    static let foods: [FoodItem] = [
        // Spaghetti with Marinara Sauce
        FoodItem(
            id: UUID(),
            name: "Spaghetti with Marinara Sauce",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 320,
                protein: 12,
                carbohydrates: 64,
                fat: 3,
                fiber: 4,
                sugar: 8,
                vitaminA: 600,
                vitaminC: 13.5,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 10,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 2,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 40,
                calcium: 60,
                iron: 1.2,
                magnesium: 40,
                phosphorus: 100,
                potassium: 400,
                sodium: 590,
                zinc: 1,
                selenium: 10,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Low in fat and relatively low in calories. Good source of complex carbohydrates for energy. Tomato sauce provides lycopene, an antioxidant.",
            nameFr: "Spaghetti à la sauce marinara",
            nameEs: "Espaguetis con salsa marinara",
            nameHe: "ספגטי ברוטב מרינרה",
            notesFr: "Faible en matières grasses et en calories. Bonne source de glucides complexes. La sauce tomate apporte du lycopène, un antioxydant.",
            notesEs: "Bajo en grasa y relativamente bajo en calorías. Buena fuente de carbohidratos complejos. La salsa de tomate aporta licopeno, un antioxidante.",
            notesHe: "דל שומן וקלוריות יחסית. מקור טוב לפחמימות מורכבות. רוטב העגבניות מספק ליקופן, נוגד חמצון."
        ),

        // Fettuccine Alfredo
        FoodItem(
            id: UUID(),
            name: "Fettuccine Alfredo",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 670,
                protein: 19,
                carbohydrates: 50,
                fat: 43,
                fiber: 2,
                sugar: 3,
                vitaminA: 1500,
                vitaminC: 0,
                vitaminD: 20,
                vitaminE: 2,
                vitaminK: 5,
                thiamin: 0.3,
                riboflavin: 0.3,
                niacin: 2,
                vitaminB6: 0.1,
                vitaminB12: 0.5,
                folate: 20,
                calcium: 300,
                iron: 1,
                magnesium: 30,
                phosphorus: 200,
                potassium: 200,
                sodium: 950,
                zinc: 1.5,
                selenium: 15,
                omega3: 0.2,
                omega6: 1,
                cholesterol: 80
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Good source of calcium from cream and cheese. Very high in calories and saturated fat. Can contribute to elevated cholesterol levels.",
            nameFr: "Fettuccine Alfredo",
            nameEs: "Fettuccine Alfredo",
            nameHe: "פטוצ'יני אלפרדו",
            notesFr: "Bonne source de calcium grâce à la crème et au fromage. Très riche en calories et en graisses saturées. Peut augmenter le cholestérol.",
            notesEs: "Buena fuente de calcio de la crema y el queso. Muy alto en calorías y grasas saturadas. Puede elevar el colesterol.",
            notesHe: "מקור טוב לסידן מקרם וגבינה. עתיר קלוריות ושומן רווי. עלול להעלות את רמות הכולסטרול."
        ),

        // Whole Wheat Pasta Primavera
        FoodItem(
            id: UUID(),
            name: "Whole Wheat Pasta Primavera",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 350,
                protein: 14,
                carbohydrates: 60,
                fat: 8,
                fiber: 9,
                sugar: 6,
                vitaminA: 1750,
                vitaminC: 40.5,
                vitaminD: 0,
                vitaminE: 3,
                vitaminK: 30,
                thiamin: 0.4,
                riboflavin: 0.3,
                niacin: 3,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 80,
                calcium: 100,
                iron: 1.6,
                magnesium: 80,
                phosphorus: 150,
                potassium: 500,
                sodium: 400,
                zinc: 1.5,
                selenium: 20,
                omega3: 0.3,
                omega6: 1,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Rich in fiber from whole wheat pasta and vegetables. Excellent source of vitamins A and C from mixed vegetables. High in antioxidants and phytonutrients.",
            nameFr: "Pâtes complètes Primavera",
            nameEs: "Pasta integral Primavera",
            nameHe: "פסטה מחיטה מלאה פרימברה",
            notesFr: "Riche en fibres grâce aux pâtes complètes et légumes. Excellente source de vitamines A et C. Riche en antioxydants et phytonutriments.",
            notesEs: "Rica en fibra de pasta integral y verduras. Excelente fuente de vitaminas A y C. Alta en antioxidantes y fitonutrientes.",
            notesHe: "עשירה בסיבים תזונתיים מחיטה מלאה וירקות. מקור מצוין לוויטמינים A ו־C. עשירה בנוגדי חמצון ופיטונוטריאנטים."
        ),

        // Shrimp Scampi with Linguine
        FoodItem(
            id: UUID(),
            name: "Shrimp Scampi with Linguine",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 440,
                protein: 24,
                carbohydrates: 52,
                fat: 16,
                fiber: 2,
                sugar: 2,
                vitaminA: 300,
                vitaminC: 5,
                vitaminD: 40,
                vitaminE: 2,
                vitaminK: 5,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 3,
                vitaminB6: 0.3,
                vitaminB12: 1.2,
                folate: 30,
                calcium: 80,
                iron: 1.2,
                magnesium: 50,
                phosphorus: 200,
                potassium: 300,
                sodium: 800,
                zinc: 1.5,
                selenium: 41.25,
                omega3: 0.5,
                omega6: 0.8,
                cholesterol: 150
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Excellent source of lean protein from shrimp. Rich in selenium and vitamin B12. Contains heart-healthy garlic. Good source of omega-3 fatty acids.",
            nameFr: "Scampi aux crevettes et linguine",
            nameEs: "Scampi de camarones con linguini",
            nameHe: "שימפ סקאמפי עם לינגוויני",
            notesFr: "Excellente source de protéines maigres des crevettes. Riche en sélénium et vitamine B12. Contient de l'ail bon pour le cœur. Bonne source d'oméga-3.",
            notesEs: "Excelente fuente de proteína magra de camarones. Rico en selenio y vitamina B12. Contiene ajo saludable para el corazón. Buena fuente de omega-3.",
            notesHe: "מקור מצוין לחלבון רזה מהשרימפס. עשיר בסלניום ובוויטמין B12. מכיל שום בריא ללב. מקור טוב לחומצות שומן אומגה 3."
        ),

        // Pesto Pasta with Pine Nuts
        FoodItem(
            id: UUID(),
            name: "Pesto Pasta with Pine Nuts",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 490,
                protein: 15,
                carbohydrates: 52,
                fat: 25,
                fiber: 3,
                sugar: 3,
                vitaminA: 500,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 3.75,
                vitaminK: 132,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 2,
                vitaminB6: 0.2,
                vitaminB12: 0.2,
                folate: 40,
                calcium: 150,
                iron: 2,
                magnesium: 80,
                phosphorus: 200,
                potassium: 300,
                sodium: 600,
                zinc: 2,
                selenium: 24.75,
                omega3: 1,
                omega6: 5,
                cholesterol: 10
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Contains healthy fats from olive oil, pine nuts, and sometimes walnuts. Rich in antioxidants from basil and olive oil. Good source of vitamin K for bone health.",
            nameFr: "Pâtes au pesto avec pignons de pin",
            nameEs: "Pasta al pesto con piñones",
            nameHe: "פסטו פסטה עם אגוזי אורן",
            notesFr: "Contient des graisses saines de l'huile d'olive, des pignons et parfois des noix. Riche en antioxydants. Bonne source de vitamine K pour les os.",
            notesEs: "Contiene grasas saludables de aceite de oliva, piñones y a veces nueces. Rica en antioxidantes. Buena fuente de vitamina K para los huesos.",
            notesHe: "מכילה שומנים בריאים משמן זית, אגוזי אורן ולעיתים גם אגוזים. עשירה בנוגדי חמצון. מקור טוב לוויטמין K לבריאות העצם."
        ),
        
        // NEW PASTA VARIETIES - Multiple Preparations
        
        // Plain Spaghetti (Cooked)
        FoodItem(
            id: UUID(),
            name: "Spaghetti (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Basic cooked spaghetti pasta, excellent source of carbohydrates",
            nameFr: "Spaghetti (nature, cuit)",
            nameEs: "Espaguetis (simple, cocido)",
            nameHe: "ספגטי (רגיל, מבושל)",
            notesFr: "Pâtes spaghetti de base cuites, excellente source de glucides",
            notesEs: "Pasta espagueti básica cocida, excelente fuente de carbohidratos",
            notesHe: "פסטת ספגטי בסיסית מבושלת, מקור מצוין לפחמימות"
        ),
        
        // Penne (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Penne (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Tube-shaped pasta, perfect for holding sauces",
            nameFr: "Penne (nature, cuit)",
            nameEs: "Penne (simple, cocido)",
            nameHe: "פנה (רגיל, מבושל)",
            notesFr: "Pâtes en forme de tube, parfaites pour retenir les sauces",
            notesEs: "Pasta en forma de tubo, perfecta para retener salsas",
            notesHe: "פסטה בצורת צינור, מושלמת לאחיזת רטבים"
        ),
        
        // Penne Arrabbiata
        FoodItem(
            id: UUID(),
            name: "Penne Arrabbiata",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 310,
                protein: 10,
                carbohydrates: 58,
                fat: 6,
                fiber: 4,
                sugar: 8,
                vitaminA: 850,
                vitaminC: 15,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 2.5,
                folate: 25,
                calcium: 45,
                iron: 2.2,
                magnesium: 60,
                phosphorus: 110,
                potassium: 420,
                sodium: 680,
                zinc: 1.2,
                selenium: 65
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Spicy tomato sauce with garlic and red pepper flakes",
            nameFr: "Penne Arrabbiata",
            nameEs: "Penne Arrabbiata",
            nameHe: "פנה אראביאטה",
            notesFr: "Sauce tomate épicée à l'ail et aux flocons de piment rouge",
            notesEs: "Salsa de tomate picante con ajo y hojuelas de chile rojo",
            notesHe: "רוטב עגבניות חריף עם שום ופתיתי פלפל אדום"
        ),
        
        // Fusilli (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Fusilli (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Spiral-shaped pasta, excellent for holding chunky sauces",
            nameFr: "Fusilli (nature, cuit)",
            nameEs: "Fusilli (simple, cocido)",
            nameHe: "פוזילי (רגיל, מבושל)",
            notesFr: "Pâtes en spirale, excellentes pour retenir les sauces épaisses",
            notesEs: "Pasta en espiral, excelente para retener salsas espesas",
            notesHe: "פסטה בצורת ספירלה, מצוינת לאחיזת רטבים עבים"
        ),
        
        // Fusilli with Vegetables
        FoodItem(
            id: UUID(),
            name: "Fusilli with Vegetables",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 280,
                protein: 11,
                carbohydrates: 52,
                fat: 4,
                fiber: 6,
                sugar: 8,
                vitaminA: 1200,
                vitaminC: 25,
                vitaminK: 20,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 2.2,
                folate: 35,
                calcium: 60,
                iron: 2.5,
                magnesium: 70,
                phosphorus: 120,
                potassium: 380,
                sodium: 320,
                zinc: 1.4,
                selenium: 65
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Healthy mix of pasta with seasonal vegetables",
            nameFr: "Fusilli aux légumes",
            nameEs: "Fusilli con verduras",
            nameHe: "פוזילי עם ירקות",
            notesFr: "Mélange sain de pâtes avec légumes de saison",
            notesEs: "Mezcla saludable de pasta con verduras de temporada",
            notesHe: "תערובת בריאה של פסטה עם ירקות עונתיים"
        ),
        
        // Macaroni (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Macaroni (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Classic elbow-shaped pasta, perfect for mac and cheese",
            nameFr: "Macaroni (nature, cuit)",
            nameEs: "Macarrones (simple, cocido)",
            nameHe: "מקרוני (רגיל, מבושל)",
            notesFr: "Pâtes classiques en forme de coude, parfaites pour le mac and cheese",
            notesEs: "Pasta clásica en forma de codo, perfecta para mac and cheese",
            notesHe: "פסטה קלאסית בצורת מרפק, מושלמת למקרוני בגבינה"
        ),
        
        // Macaroni and Cheese
        FoodItem(
            id: UUID(),
            name: "Macaroni and Cheese",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 390,
                protein: 18,
                carbohydrates: 40,
                fat: 18,
                fiber: 2,
                sugar: 6,
                vitaminA: 900,
                vitaminD: 15,
                riboflavin: 0.4,
                vitaminB12: 0.8,
                folate: 25,
                calcium: 350,
                iron: 1.5,
                magnesium: 45,
                phosphorus: 280,
                potassium: 180,
                sodium: 850,
                zinc: 2.2,
                selenium: 68
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Comfort food rich in calcium and protein from cheese",
            nameFr: "Macaroni au fromage",
            nameEs: "Macarrones con queso",
            nameHe: "מקרוני בגבינה",
            notesFr: "Plat réconfortant riche en calcium et protéines du fromage",
            notesEs: "Comida reconfortante rica en calcio y proteínas del queso",
            notesHe: "מזון נוחם עשיר בסידן וחלבונים מהגבינה"
        ),
        
        // Linguine (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Linguine (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Flat, thin pasta similar to spaghetti but wider",
            nameFr: "Linguine (nature, cuit)",
            nameEs: "Linguini (simple, cocido)",
            nameHe: "לינגוויני (רגיל, מבושל)",
            notesFr: "Pâtes plates et fines similaires aux spaghetti mais plus larges",
            notesEs: "Pasta plana y delgada similar a espaguetis pero más ancha",
            notesHe: "פסטה שטוחה ודקה דומה לספגטי אך רחבה יותר"
        ),
        
        // Linguine with Clam Sauce
        FoodItem(
            id: UUID(),
            name: "Linguine with Clam Sauce",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 380,
                protein: 22,
                carbohydrates: 48,
                fat: 12,
                fiber: 3,
                sugar: 4,
                vitaminA: 200,
                vitaminC: 8,
                vitaminB12: 15.6,
                folate: 28,
                calcium: 78,
                iron: 13.2,
                magnesium: 65,
                phosphorus: 220,
                potassium: 320,
                sodium: 720,
                zinc: 2.8,
                selenium: 89
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Seafood pasta rich in iron, vitamin B12, and zinc",
            nameFr: "Linguine aux palourdes",
            nameEs: "Linguini con salsa de almejas",
            nameHe: "לינגוויני ברוטב צדפות",
            notesFr: "Pâtes aux fruits de mer riches en fer, vitamine B12 et zinc",
            notesEs: "Pasta de mariscos rica en hierro, vitamina B12 y zinc",
            notesHe: "פסטת פירות ים עשירה בברזל, ויטמין B12 ואבץ"
        ),
        
        // Fettuccine (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Fettuccine (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Flat, thick ribbon pasta, perfect for cream sauces",
            nameFr: "Fettuccine (nature, cuit)",
            nameEs: "Fettuccine (simple, cocido)",
            nameHe: "פטוצ'יני (רגיל, מבושל)",
            notesFr: "Pâtes plates et épaisses en ruban, parfaites pour les sauces crémeuses",
            notesEs: "Pasta plana y gruesa en forma de cinta, perfecta para salsas cremosas",
            notesHe: "פסטה שטוחה ועבה בצורת סרט, מושלמת לרטבי קרם"
        ),
        
        // Tagliatelle (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Tagliatelle (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional egg pasta from Emilia-Romagna, ribbon-shaped",
            nameFr: "Tagliatelle (nature, cuit)",
            nameEs: "Tagliatelle (simple, cocido)",
            nameHe: "טליאטלה (רגיל, מבושל)",
            notesFr: "Pâtes aux œufs traditionnelles d'Émilie-Romagne, en forme de ruban",
            notesEs: "Pasta tradicional de huevo de Emilia-Romagna, en forma de cinta",
            notesHe: "פסטת ביצים מסורתית מאמיליה-רומניה, בצורת סרט"
        ),
        
        // Tagliatelle Bolognese
        FoodItem(
            id: UUID(),
            name: "Tagliatelle Bolognese",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 420,
                protein: 22,
                carbohydrates: 48,
                fat: 16,
                fiber: 4,
                sugar: 8,
                vitaminA: 650,
                vitaminC: 12,
                vitaminB12: 2.1,
                folate: 32,
                calcium: 85,
                iron: 3.2,
                magnesium: 68,
                phosphorus: 180,
                potassium: 520,
                sodium: 780,
                zinc: 4.2,
                selenium: 72
            ),
            servingSize: 300,
            servingUnit: "g",
            isCustom: true,
            notes: "Classic meat sauce with ground beef, rich in protein and iron",
            nameFr: "Tagliatelle Bolognaise",
            nameEs: "Tagliatelle Boloñesa",
            nameHe: "טליאטלה בולונזה",
            notesFr: "Sauce à la viande classique avec bœuf haché, riche en protéines et fer",
            notesEs: "Salsa de carne clásica con carne molida, rica en proteínas y hierro",
            notesHe: "רוטב בשר קלאסי עם בשר טחון, עשיר בחלבונים וברזל"
        ),
        
        // Lasagna Sheets (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Lasagna Sheets (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Flat pasta sheets used for layered dishes",
            nameFr: "Feuilles de lasagne (nature, cuit)",
            nameEs: "Láminas de lasaña (simple, cocido)",
            nameHe: "דפי לזניה (רגיל, מבושל)",
            notesFr: "Feuilles de pâtes plates utilisées pour les plats en couches",
            notesEs: "Láminas de pasta plana usadas para platos en capas",
            notesHe: "דפי פסטה שטוחים המשמשים למנות שכבות"
        ),
        
        // Meat Lasagna
        FoodItem(
            id: UUID(),
            name: "Meat Lasagna",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 510,
                protein: 28,
                carbohydrates: 42,
                fat: 26,
                fiber: 4,
                sugar: 12,
                vitaminA: 1200,
                vitaminC: 15,
                vitaminB12: 1.8,
                folate: 35,
                calcium: 420,
                iron: 3.8,
                magnesium: 75,
                phosphorus: 320,
                potassium: 680,
                sodium: 1100,
                zinc: 5.2,
                selenium: 78
            ),
            servingSize: 350,
            servingUnit: "g",
            isCustom: true,
            notes: "Layered pasta with meat sauce, cheese, and béchamel",
            nameFr: "Lasagne à la viande",
            nameEs: "Lasaña de carne",
            nameHe: "לזניה בשר",
            notesFr: "Pâtes en couches avec sauce à la viande, fromage et béchamel",
            notesEs: "Pasta en capas con salsa de carne, queso y bechamel",
            notesHe: "פסטה שכבות עם רוטב בשר, גבינה ובשמל"
        ),
        
        // Rigatoni (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Rigatoni (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Large tube pasta with ridges, excellent for thick sauces",
            nameFr: "Rigatoni (nature, cuit)",
            nameEs: "Rigatoni (simple, cocido)",
            nameHe: "ריגטוני (רגיל, מבושל)",
            notesFr: "Grosses pâtes tubulaires avec des rainures, excellentes pour les sauces épaisses",
            notesEs: "Pasta de tubo grande con estrías, excelente para salsas espesas",
            notesHe: "פסטת צינור גדולה עם חריצים, מצוינת לרטבים עבים"
        ),
        
        // Rigatoni with Sausage
        FoodItem(
            id: UUID(),
            name: "Rigatoni with Sausage",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 480,
                protein: 24,
                carbohydrates: 52,
                fat: 22,
                fiber: 4,
                sugar: 8,
                vitaminA: 580,
                vitaminC: 18,
                vitaminB12: 1.2,
                folate: 28,
                calcium: 95,
                iron: 2.8,
                magnesium: 72,
                phosphorus: 220,
                potassium: 450,
                sodium: 920,
                zinc: 3.8,
                selenium: 75
            ),
            servingSize: 300,
            servingUnit: "g",
            isCustom: true,
            notes: "Hearty pasta with Italian sausage and tomato sauce",
            nameFr: "Rigatoni aux saucisses",
            nameEs: "Rigatoni con salchicha",
            nameHe: "ריגטוני עם נקניק",
            notesFr: "Pâtes copieuses avec saucisse italienne et sauce tomate",
            notesEs: "Pasta abundante con salchicha italiana y salsa de tomate",
            notesHe: "פסטה מזינה עם נקניק איטלקי ורוטב עגבניות"
        ),
        
        // Shells - Conchiglie (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Shells - Conchiglie (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Shell-shaped pasta perfect for holding chunky sauces",
            nameFr: "Coquilles - Conchiglie (nature, cuit)",
            nameEs: "Conchas - Conchiglie (simple, cocido)",
            nameHe: "קונכיות - קונכיליה (רגיל, מבושל)",
            notesFr: "Pâtes en forme de coquille parfaites pour retenir les sauces épaisses",
            notesEs: "Pasta en forma de concha perfecta para retener salsas espesas",
            notesHe: "פסטה בצורת קונכיה מושלמת לאחיזת רטבים עבים"
        ),
        
        // Stuffed Shells
        FoodItem(
            id: UUID(),
            name: "Stuffed Shells",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 450,
                protein: 24,
                carbohydrates: 48,
                fat: 18,
                fiber: 4,
                sugar: 10,
                vitaminA: 1100,
                vitaminC: 12,
                vitaminB12: 1.5,
                folate: 42,
                calcium: 380,
                iron: 2.5,
                magnesium: 68,
                phosphorus: 290,
                potassium: 420,
                sodium: 850,
                zinc: 3.2,
                selenium: 72
            ),
            servingSize: 300,
            servingUnit: "g",
            isCustom: true,
            notes: "Large shells stuffed with ricotta cheese and herbs",
            nameFr: "Coquilles farcies",
            nameEs: "Conchas rellenas",
            nameHe: "קונכיות ממולאות",
            notesFr: "Grosses coquilles farcies au fromage ricotta et aux herbes",
            notesEs: "Conchas grandes rellenas con queso ricotta y hierbas",
            notesHe: "קונכיות גדולות ממולאות בגבינת ריקוטה ועשבי תיבול"
        ),
        
        // Tortellini (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Tortellini (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 250,
                protein: 11,
                carbohydrates: 38,
                fat: 6,
                fiber: 2,
                sugar: 2,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 2.2,
                folate: 25,
                calcium: 45,
                iron: 2.2,
                magnesium: 42,
                phosphorus: 120,
                potassium: 95,
                sodium: 380,
                zinc: 1.8,
                selenium: 65
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Ring-shaped stuffed pasta, traditionally filled with meat or cheese",
            nameFr: "Tortellini (nature, cuit)",
            nameEs: "Tortellini (simple, cocido)",
            nameHe: "טורטליני (רגיל, מבושל)",
            notesFr: "Pâtes farcies en forme d'anneau, traditionnellement à la viande ou au fromage",
            notesEs: "Pasta rellena en forma de anillo, tradicionalmente con carne o queso",
            notesHe: "פסטה ממולאת בצורת טבעת, מסורתית עם בשר או גבינה"
        ),
        
        // Tortellini in Broth
        FoodItem(
            id: UUID(),
            name: "Tortellini in Broth",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 180,
                protein: 12,
                carbohydrates: 28,
                fat: 4,
                fiber: 2,
                sugar: 3,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 2.8,
                folate: 22,
                calcium: 35,
                iron: 1.8,
                magnesium: 38,
                phosphorus: 110,
                potassium: 280,
                sodium: 850,
                zinc: 1.5,
                selenium: 68
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional Italian soup with stuffed pasta in clear broth",
            nameFr: "Tortellini en bouillon",
            nameEs: "Tortellini en caldo",
            nameHe: "טורטליני במרק",
            notesFr: "Soupe italienne traditionnelle avec pâtes farcies dans un bouillon clair",
            notesEs: "Sopa italiana tradicional con pasta rellena en caldo claro",
            notesHe: "מרק איטלקי מסורתי עם פסטה ממולאת במרק צלול"
        ),
        
        // Ravioli (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Ravioli (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 280,
                protein: 13,
                carbohydrates: 42,
                fat: 7,
                fiber: 3,
                sugar: 3,
                thiamin: 0.3,
                riboflavin: 0.3,
                niacin: 2.5,
                folate: 32,
                calcium: 85,
                iron: 2.5,
                magnesium: 48,
                phosphorus: 140,
                potassium: 120,
                sodium: 450,
                zinc: 2.2,
                selenium: 70
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Square stuffed pasta parcels, traditionally filled with cheese or meat",
            nameFr: "Ravioli (nature, cuit)",
            nameEs: "Ravioli (simple, cocido)",
            nameHe: "רביולי (רגיל, מבושל)",
            notesFr: "Pâtes farcies carrées, traditionnellement au fromage ou à la viande",
            notesEs: "Pasta rellena cuadrada, tradicionalmente con queso o carne",
            notesHe: "פסטה ממולאת מרובעת, מסורתית עם גבינה או בשר"
        ),
        
        // Cheese Ravioli with Marinara
        FoodItem(
            id: UUID(),
            name: "Cheese Ravioli with Marinara",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 380,
                protein: 18,
                carbohydrates: 52,
                fat: 12,
                fiber: 5,
                sugar: 12,
                vitaminA: 950,
                vitaminC: 18,
                vitaminB12: 1.2,
                folate: 42,
                calcium: 280,
                iron: 2.8,
                magnesium: 58,
                phosphorus: 220,
                potassium: 520,
                sodium: 780,
                zinc: 2.8,
                selenium: 72
            ),
            servingSize: 300,
            servingUnit: "g",
            isCustom: true,
            notes: "Cheese-filled ravioli with classic tomato sauce",
            nameFr: "Ravioli au fromage avec marinara",
            nameEs: "Ravioli de queso con marinara",
            nameHe: "רביולי גבינה עם מרינרה",
            notesFr: "Ravioli fourrés au fromage avec sauce tomate classique",
            notesEs: "Ravioli rellenos de queso con salsa de tomate clásica",
            notesHe: "רביולי ממולא גבינה עם רוטב עגבניות קלאסי"
        ),
        
        // Orzo (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Orzo (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Rice-shaped pasta, perfect for soups and salads",
            nameFr: "Orzo (nature, cuit)",
            nameEs: "Orzo (simple, cocido)",
            nameHe: "אורזו (רגיל, מבושל)",
            notesFr: "Pâtes en forme de riz, parfaites pour les soupes et salades",
            notesEs: "Pasta en forma de arroz, perfecta para sopas y ensaladas",
            notesHe: "פסטה בצורת אורז, מושלמת למרקים וסלטים"
        ),
        
        // Orzo Salad
        FoodItem(
            id: UUID(),
            name: "Orzo Salad",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 320,
                protein: 12,
                carbohydrates: 48,
                fat: 10,
                fiber: 6,
                sugar: 8,
                vitaminA: 1400,
                vitaminC: 35,
                vitaminE: 2.5,
                vitaminK: 45,
                folate: 35,
                calcium: 85,
                iron: 2.2,
                magnesium: 68,
                phosphorus: 120,
                potassium: 420,
                sodium: 480,
                zinc: 1.8,
                selenium: 65
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Mediterranean-style pasta salad with vegetables and herbs",
            nameFr: "Salade d'orzo",
            nameEs: "Ensalada de orzo",
            nameHe: "סלט אורזו",
            notesFr: "Salade de pâtes méditerranéenne avec légumes et herbes",
            notesEs: "Ensalada de pasta mediterránea con verduras y hierbas",
            notesHe: "סלט פסטה ים תיכוני עם ירקות ועשבי תיבול"
        ),
        
        // Cannelloni (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Cannelloni (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Large tube pasta designed for stuffing",
            nameFr: "Cannelloni (nature, cuit)",
            nameEs: "Canelones (simple, cocido)",
            nameHe: "קנלוני (רגיל, מבושל)",
            notesFr: "Grosses pâtes tubulaires conçues pour être farcies",
            notesEs: "Pasta de tubo grande diseñada para rellenar",
            notesHe: "פסטת צינור גדולה המיועדת למילוי"
        ),
        
        // Stuffed Cannelloni
        FoodItem(
            id: UUID(),
            name: "Stuffed Cannelloni",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 420,
                protein: 22,
                carbohydrates: 45,
                fat: 18,
                fiber: 4,
                sugar: 10,
                vitaminA: 1200,
                vitaminC: 15,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 350,
                iron: 3.2,
                magnesium: 72,
                phosphorus: 280,
                potassium: 520,
                sodium: 920,
                zinc: 3.5,
                selenium: 75
            ),
            servingSize: 300,
            servingUnit: "g",
            isCustom: true,
            notes: "Tube pasta stuffed with ricotta and spinach, baked in sauce",
            nameFr: "Cannelloni farcis",
            nameEs: "Canelones rellenos",
            nameHe: "קנלוני ממולא",
            notesFr: "Pâtes tubulaires farcies à la ricotta et aux épinards, cuites au four dans la sauce",
            notesEs: "Pasta tubular rellena con ricotta y espinacas, horneada en salsa",
            notesHe: "פסטת צינור ממולאת בריקוטה ותרד, אפויה ברוטב"
        ),
        
        // Angel Hair - Capellini (Plain, Cooked)
        FoodItem(
            id: UUID(),
            name: "Angel Hair - Capellini (Plain, Cooked)",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.1,
                carbohydrates: 44,
                fat: 1.3,
                fiber: 2.5,
                sugar: 0.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.8,
                folate: 18,
                calcium: 21,
                iron: 1.8,
                magnesium: 53,
                phosphorus: 89,
                potassium: 62,
                sodium: 6,
                zinc: 1.0,
                selenium: 63.2
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Very thin pasta, cooks quickly, perfect for light sauces",
            nameFr: "Cheveux d'ange - Capellini (nature, cuit)",
            nameEs: "Cabello de ángel - Capellini (simple, cocido)",
            nameHe: "שיער מלאכים - קפליני (רגיל, מבושל)",
            notesFr: "Pâtes très fines, cuisson rapide, parfaites pour les sauces légères",
            notesEs: "Pasta muy delgada, cocción rápida, perfecta para salsas ligeras",
            notesHe: "פסטה דקה מאוד, מתבשלת מהר, מושלמת לרטבים קלים"
        ),
        
        // Angel Hair with Garlic and Oil
        FoodItem(
            id: UUID(),
            name: "Angel Hair with Garlic and Oil",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 380,
                protein: 12,
                carbohydrates: 52,
                fat: 14,
                fiber: 3,
                sugar: 2,
                vitaminE: 2.8,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 2.2,
                folate: 25,
                calcium: 35,
                iron: 2.2,
                magnesium: 68,
                phosphorus: 120,
                potassium: 180,
                sodium: 420,
                zinc: 1.5,
                selenium: 68
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Classic Italian aglio e olio, simple and flavorful",
            nameFr: "Cheveux d'ange à l'ail et à l'huile",
            nameEs: "Cabello de ángel con ajo y aceite",
            nameHe: "שיער מלאכים עם שום ושמן",
            notesFr: "Aglio e olio italien classique, simple et savoureux",
            notesEs: "Aglio e olio italiano clásico, simple y sabroso",
            notesHe: "אליו אה אוליו איטלקי קלאסי, פשוט וטעים"
        )
    ]
}
