import Foundation

struct VegetableFoodItems {
    static let foods: [FoodItem] = [
        // Broccoli
        FoodItem(
            id: UUID(),
            name: "Broccoli",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 34,
                protein: 2.8,
                carbohydrates: 7,
                fat: 0.4,
                fiber: 2.6,
                sugar: 1.5,
                vitaminA: 623,
                vitaminC: 89,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 102,
                thiamin: 0.07,
                riboflavin: 0.12,
                niacin: 0.6,
                vitaminB6: 0.18,
                vitaminB12: 0,
                folate: 63,
                calcium: 47,
                iron: 0.7,
                magnesium: 21,
                phosphorus: 66,
                potassium: 316,
                sodium: 33,
                zinc: 0.4,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Rich in vitamin C and fiber, excellent steamed or roasted",
            nameFr: "Brocoli",
            nameEs: "Brócoli",
            nameHe: "ברוקולי",
            notesFr: "Riche en vitamine C et fibres, excellent à la vapeur ou rôti",
            notesEs: "Rico en vitamina C y fibra, excelente al vapor o asado",
            notesHe: "עשיר בוויטמין C וסיבים, מעולה מאודה או צלוי"
        ),
        
        // Spinach
        FoodItem(
            id: UUID(),
            name: "Spinach",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 23,
                protein: 2.9,
                carbohydrates: 3.6,
                fat: 0.4,
                fiber: 2.2,
                sugar: 0.4,
                vitaminA: 469,
                vitaminC: 28,
                vitaminD: 0,
                vitaminE: 2.0,
                vitaminK: 483,
                thiamin: 0.08,
                riboflavin: 0.19,
                niacin: 0.7,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 194,
                calcium: 99,
                iron: 2.7,
                magnesium: 79,
                phosphorus: 49,
                potassium: 558,
                sodium: 79,
                zinc: 0.5,
                selenium: 1,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in iron and folate, great in salads or cooked dishes",
            nameFr: "Épinards",
            nameEs: "Espinacas",
            nameHe: "תרד",
            notesFr: "Riche en fer et folate, excellent en salade ou cuit",
            notesEs: "Alto en hierro y folato, excelente en ensaladas o platos cocidos",
            notesHe: "עשיר בברזל וחומצה פולית, מעולה בסלטים או מבושל"
        ),
        
        // Carrots
        FoodItem(
            id: UUID(),
            name: "Carrots",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 41,
                protein: 0.9,
                carbohydrates: 10,
                fat: 0.2,
                fiber: 2.8,
                sugar: 4.7,
                vitaminA: 835,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0.7,
                vitaminK: 13,
                thiamin: 0.07,
                riboflavin: 0.06,
                niacin: 1.0,
                vitaminB6: 0.14,
                vitaminB12: 0,
                folate: 19,
                calcium: 33,
                iron: 0.3,
                magnesium: 12,
                phosphorus: 35,
                potassium: 320,
                sodium: 69,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Excellent source of beta-carotene, sweet and crunchy",
            nameFr: "Carottes",
            nameEs: "Zanahorias",
            nameHe: "גזר",
            notesFr: "Excellente source de bêta-carotène, douce et croquante",
            notesEs: "Excelente fuente de beta-caroteno, dulce y crujiente",
            notesHe: "מקור מעולה לבטא-קרוטן, מתוק ופריך"
        ),
        
        // Bell Peppers (Red)
        FoodItem(
            id: UUID(),
            name: "Red Bell Peppers",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 1.0,
                carbohydrates: 7,
                fat: 0.3,
                fiber: 2.5,
                sugar: 4.2,
                vitaminA: 157,
                vitaminC: 128,
                vitaminD: 0,
                vitaminE: 1.6,
                vitaminK: 5,
                thiamin: 0.05,
                riboflavin: 0.09,
                niacin: 1.0,
                vitaminB6: 0.29,
                vitaminB12: 0,
                folate: 46,
                calcium: 7,
                iron: 0.4,
                magnesium: 12,
                phosphorus: 26,
                potassium: 211,
                sodium: 4,
                zinc: 0.3,
                selenium: 0.1,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very high in vitamin C, sweet and colorful",
            nameFr: "Poivrons rouges",
            nameEs: "Pimientos rojos",
            nameHe: "פלפל אדום",
            notesFr: "Très riche en vitamine C, doux et coloré",
            notesEs: "Muy alto en vitamina C, dulce y colorido",
            notesHe: "עשיר מאוד בוויטמין C, מתוק וצבעוני"
        ),
        
        // Tomatoes
        FoodItem(
            id: UUID(),
            name: "Tomatoes",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 18,
                protein: 0.9,
                carbohydrates: 3.9,
                fat: 0.2,
                fiber: 1.2,
                sugar: 2.6,
                vitaminA: 42,
                vitaminC: 14,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 8,
                thiamin: 0.04,
                riboflavin: 0.02,
                niacin: 0.6,
                vitaminB6: 0.08,
                vitaminB12: 0,
                folate: 15,
                calcium: 10,
                iron: 0.3,
                magnesium: 11,
                phosphorus: 24,
                potassium: 237,
                sodium: 5,
                zinc: 0.2,
                selenium: 0,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Rich in lycopene, versatile for cooking and salads",
            nameFr: "Tomates",
            nameEs: "Tomates",
            nameHe: "עגבניות",
            notesFr: "Riche en lycopène, polyvalent pour la cuisine et les salades",
            notesEs: "Rico en licopeno, versátil para cocinar y ensaladas",
            notesHe: "עשיר בליקופן, רב-תכליתי לבישול וסלטים"
        ),
        
        // Cucumber
        FoodItem(
            id: UUID(),
            name: "Cucumber",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 16,
                protein: 0.7,
                carbohydrates: 4,
                fat: 0.1,
                fiber: 0.5,
                sugar: 1.7,
                vitaminA: 5,
                vitaminC: 3,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 16,
                thiamin: 0.03,
                riboflavin: 0.03,
                niacin: 0.1,
                vitaminB6: 0.04,
                vitaminB12: 0,
                folate: 7,
                calcium: 16,
                iron: 0.3,
                magnesium: 13,
                phosphorus: 24,
                potassium: 147,
                sodium: 2,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very hydrating, low calorie, refreshing in salads",
            nameFr: "Concombre",
            nameEs: "Pepino",
            nameHe: "מלפפון",
            notesFr: "Très hydratant, faible en calories, rafraîchissant en salade",
            notesEs: "Muy hidratante, bajo en calorías, refrescante en ensaladas",
            notesHe: "מאוד מרטיב, דל קלוריות, מרענן בסלטים"
        ),
        
        // Lettuce (Romaine)
        FoodItem(
            id: UUID(),
            name: "Romaine Lettuce",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 17,
                protein: 1.2,
                carbohydrates: 3.3,
                fat: 0.3,
                fiber: 2.1,
                sugar: 1.2,
                vitaminA: 436,
                vitaminC: 4,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 103,
                thiamin: 0.07,
                riboflavin: 0.07,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 136,
                calcium: 33,
                iron: 1.0,
                magnesium: 14,
                phosphorus: 30,
                potassium: 247,
                sodium: 8,
                zinc: 0.2,
                selenium: 0.4,
                omega3: 0.1,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate and vitamin K, crisp texture",
            nameFr: "Laitue romaine",
            nameEs: "Lechuga romana",
            nameHe: "חסה רומית",
            notesFr: "Riche en folate et vitamine K, texture croquante",
            notesEs: "Alto en folato y vitamina K, textura crujiente",
            notesHe: "עשיר בחומצה פולית ווויטמין K, מרקם פריך"
        ),
        
        // Zucchini
        FoodItem(
            id: UUID(),
            name: "Zucchini",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 17,
                protein: 1.2,
                carbohydrates: 3.1,
                fat: 0.3,
                fiber: 1.0,
                sugar: 2.5,
                vitaminA: 10,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 4,
                thiamin: 0.05,
                riboflavin: 0.09,
                niacin: 0.5,
                vitaminB6: 0.16,
                vitaminB12: 0,
                folate: 24,
                calcium: 16,
                iron: 0.4,
                magnesium: 18,
                phosphorus: 38,
                potassium: 261,
                sodium: 8,
                zinc: 0.3,
                selenium: 0.2,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild flavor, versatile for grilling, baking, or spiralizing",
            nameFr: "Courgette",
            nameEs: "Calabacín",
            nameHe: "קישוא",
            notesFr: "Saveur douce, polyvalent pour griller, cuire ou spiraler",
            notesEs: "Sabor suave, versátil para asar, hornear o espiralizar",
            notesHe: "טעם עדין, רב-תכליתי לצלייה, אפייה או ספירליזציה"
        ),
        
        // Cauliflower
        FoodItem(
            id: UUID(),
            name: "Cauliflower",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.9,
                carbohydrates: 5,
                fat: 0.3,
                fiber: 2.0,
                sugar: 1.9,
                vitaminA: 0,
                vitaminC: 48,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 16,
                thiamin: 0.05,
                riboflavin: 0.06,
                niacin: 0.5,
                vitaminB6: 0.18,
                vitaminB12: 0,
                folate: 57,
                calcium: 22,
                iron: 0.4,
                magnesium: 15,
                phosphorus: 44,
                potassium: 299,
                sodium: 30,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of vitamin C, great rice substitute when riced",
            nameFr: "Chou-fleur",
            nameEs: "Coliflor",
            nameHe: "כרובית",
            notesFr: "Bonne source de vitamine C, excellent substitut de riz haché",
            notesEs: "Buena fuente de vitamina C, excelente sustituto del arroz rallado",
            notesHe: "מקור טוב לוויטמין C, תחליף מעולה לאורז כשקצוץ"
        ),
        
        // Brussels Sprouts
        FoodItem(
            id: UUID(),
            name: "Brussels Sprouts",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 43,
                protein: 3.4,
                carbohydrates: 9,
                fat: 0.3,
                fiber: 3.8,
                sugar: 2.2,
                vitaminA: 38,
                vitaminC: 85,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 177,
                thiamin: 0.14,
                riboflavin: 0.09,
                niacin: 0.7,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 61,
                calcium: 42,
                iron: 1.4,
                magnesium: 23,
                phosphorus: 69,
                potassium: 389,
                sodium: 25,
                zinc: 0.4,
                selenium: 1.6,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in vitamin K and fiber, delicious roasted with olive oil",
            nameFr: "Choux de Bruxelles",
            nameEs: "Coles de Bruselas",
            nameHe: "כרוב ניצנים",
            notesFr: "Riche en vitamine K et fibres, délicieux rôti à l'huile d'olive",
            notesEs: "Alto en vitamina K y fibra, delicioso asado con aceite de oliva",
            notesHe: "עשיר בוויטמין K וסיבים, טעים צלוי עם שמן זית"
        ),
        
        // Asparagus
        FoodItem(
            id: UUID(),
            name: "Asparagus",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 20,
                protein: 2.2,
                carbohydrates: 3.9,
                fat: 0.1,
                fiber: 2.1,
                sugar: 1.9,
                vitaminA: 38,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 1.1,
                vitaminK: 42,
                thiamin: 0.14,
                riboflavin: 0.14,
                niacin: 1.0,
                vitaminB6: 0.09,
                vitaminB12: 0,
                folate: 52,
                calcium: 24,
                iron: 2.1,
                magnesium: 14,
                phosphorus: 52,
                potassium: 202,
                sodium: 2,
                zinc: 0.5,
                selenium: 2.3,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate, elegant vegetable perfect for grilling",
            nameFr: "Asperges",
            nameEs: "Espárragos",
            nameHe: "אספרגוס",
            notesFr: "Riche en folate, légume élégant parfait pour griller",
            notesEs: "Alto en folato, vegetal elegante perfecto para asar",
            notesHe: "עשיר בחומצה פולית, ירק אלגנטי מושלם לצלייה"
        ),
        
        // Green Beans
        FoodItem(
            id: UUID(),
            name: "Green Beans",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 1.8,
                carbohydrates: 7,
                fat: 0.2,
                fiber: 2.7,
                sugar: 3.3,
                vitaminA: 35,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 43,
                thiamin: 0.08,
                riboflavin: 0.10,
                niacin: 0.7,
                vitaminB6: 0.14,
                vitaminB12: 0,
                folate: 33,
                calcium: 37,
                iron: 1.0,
                magnesium: 25,
                phosphorus: 38,
                potassium: 211,
                sodium: 6,
                zinc: 0.2,
                selenium: 0.6,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of fiber, tender when steamed or sautéed",
            nameFr: "Haricots verts",
            nameEs: "Judías verdes",
            nameHe: "שעועית ירוקה",
            notesFr: "Bonne source de fibres, tendres à la vapeur ou sautés",
            notesEs: "Buena fuente de fibra, tiernos al vapor o salteados",
            notesHe: "מקור טוב לסיבים, רכים כשמאודים או מוקפצים"
        ),
        
        // Sweet Potato
        FoodItem(
            id: UUID(),
            name: "Sweet Potato",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 86,
                protein: 1.6,
                carbohydrates: 20,
                fat: 0.1,
                fiber: 3.0,
                sugar: 4.2,
                vitaminA: 709,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 2,
                thiamin: 0.08,
                riboflavin: 0.06,
                niacin: 0.6,
                vitaminB6: 0.21,
                vitaminB12: 0,
                folate: 11,
                calcium: 30,
                iron: 0.6,
                magnesium: 25,
                phosphorus: 47,
                potassium: 337,
                sodium: 54,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very high in vitamin A, naturally sweet and nutritious",
            nameFr: "Patate douce",
            nameEs: "Batata",
            nameHe: "בטטה",
            notesFr: "Très riche en vitamine A, naturellement douce et nutritive",
            notesEs: "Muy alto en vitamina A, naturalmente dulce y nutritivo",
            notesHe: "עשיר מאוד בוויטמין A, מתוק באופן טבעי ומזין"
        ),
        
        // Beets
        FoodItem(
            id: UUID(),
            name: "Beets",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 43,
                protein: 1.6,
                carbohydrates: 10,
                fat: 0.2,
                fiber: 2.8,
                sugar: 6.8,
                vitaminA: 2,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 0.2,
                thiamin: 0.03,
                riboflavin: 0.04,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 109,
                calcium: 16,
                iron: 0.8,
                magnesium: 23,
                phosphorus: 40,
                potassium: 325,
                sodium: 78,
                zinc: 0.4,
                selenium: 0.7,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate and natural nitrates, earthy sweet flavor",
            nameFr: "Betteraves",
            nameEs: "Remolachas",
            nameHe: "סלק",
            notesFr: "Riche en folate et nitrates naturels, saveur douce terreuse",
            notesEs: "Alto en folato y nitratos naturales, sabor dulce terroso",
            notesHe: "עשיר בחומצה פולית וחנקות טבעיות, טעם מתוק אדמתי"
        ),
        
        // Cabbage
        FoodItem(
            id: UUID(),
            name: "Cabbage",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.3,
                carbohydrates: 6,
                fat: 0.1,
                fiber: 2.5,
                sugar: 3.2,
                vitaminA: 5,
                vitaminC: 37,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 76,
                thiamin: 0.06,
                riboflavin: 0.04,
                niacin: 0.2,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 43,
                calcium: 40,
                iron: 0.5,
                magnesium: 12,
                phosphorus: 26,
                potassium: 170,
                sodium: 18,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of vitamin C and K, excellent for coleslaw",
            nameFr: "Chou",
            nameEs: "Repollo",
            nameHe: "כרוב",
            notesFr: "Bonne source de vitamine C et K, excellent pour la salade de chou",
            notesEs: "Buena fuente de vitamina C y K, excelente para ensalada de col",
            notesHe: "מקור טוב לוויטמין C ו-K, מעולה לסלט כרוב"
        ),
        
        // Kale
        FoodItem(
            id: UUID(),
            name: "Kale",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 49,
                protein: 4.3,
                carbohydrates: 9,
                fat: 0.9,
                fiber: 3.6,
                sugar: 2.3,
                vitaminA: 681,
                vitaminC: 120,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 704,
                thiamin: 0.11,
                riboflavin: 0.13,
                niacin: 1.2,
                vitaminB6: 0.27,
                vitaminB12: 0,
                folate: 141,
                calcium: 150,
                iron: 1.5,
                magnesium: 47,
                phosphorus: 92,
                potassium: 491,
                sodium: 38,
                zinc: 0.6,
                selenium: 0.9,
                omega3: 0.2,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Superfood high in vitamins A, C, and K, great in smoothies",
            nameFr: "Chou frisé",
            nameEs: "Col rizada",
            nameHe: "קייל",
            notesFr: "Superaliment riche en vitamines A, C et K, excellent en smoothies",
            notesEs: "Superalimento alto en vitaminas A, C y K, excelente en batidos",
            notesHe: "סופרפוד עשיר בוויטמינים A, C ו-K, מעולה בשייקים"
        ),
        
        // Radishes
        FoodItem(
            id: UUID(),
            name: "Radishes",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 16,
                protein: 0.7,
                carbohydrates: 3.4,
                fat: 0.1,
                fiber: 1.6,
                sugar: 1.9,
                vitaminA: 0,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 1.3,
                thiamin: 0.01,
                riboflavin: 0.04,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 25,
                calcium: 25,
                iron: 0.3,
                magnesium: 10,
                phosphorus: 20,
                potassium: 233,
                sodium: 39,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Crisp and peppery, adds crunch to salads",
            nameFr: "Radis",
            nameEs: "Rábanos",
            nameHe: "צנון",
            notesFr: "Croquant et poivré, ajoute du croquant aux salades",
            notesEs: "Crujiente y picante, añade textura a las ensaladas",
            notesHe: "פריך וחריף, מוסיף פריכות לסלטים"
        ),
        
        // Celery
        FoodItem(
            id: UUID(),
            name: "Celery",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 14,
                protein: 0.7,
                carbohydrates: 3,
                fat: 0.2,
                fiber: 1.6,
                sugar: 1.3,
                vitaminA: 22,
                vitaminC: 3,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 29,
                thiamin: 0.02,
                riboflavin: 0.06,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 36,
                calcium: 40,
                iron: 0.2,
                magnesium: 11,
                phosphorus: 24,
                potassium: 260,
                sodium: 80,
                zinc: 0.1,
                selenium: 0.4,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very low calorie, crunchy, great with peanut butter",
            nameFr: "Céleri",
            nameEs: "Apio",
            nameHe: "סלרי",
            notesFr: "Très faible en calories, croquant, excellent avec du beurre d'arachide",
            notesEs: "Muy bajo en calorías, crujiente, excelente con mantequilla de maní",
            notesHe: "דל קלוריות מאוד, פריך, מעולה עם חמאת בוטנים"
        ),
        
        // Onions
        FoodItem(
            id: UUID(),
            name: "Onions",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 40,
                protein: 1.1,
                carbohydrates: 9.3,
                fat: 0.1,
                fiber: 1.7,
                sugar: 4.2,
                vitaminA: 0,
                vitaminC: 7,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 0.4,
                thiamin: 0.05,
                riboflavin: 0.03,
                niacin: 0.1,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 19,
                calcium: 23,
                iron: 0.2,
                magnesium: 10,
                phosphorus: 29,
                potassium: 146,
                sodium: 4,
                zinc: 0.2,
                selenium: 0.5,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Fundamental cooking ingredient, rich in antioxidants",
            nameFr: "Oignons",
            nameEs: "Cebollas",
            nameHe: "בצל",
            notesFr: "Ingrédient de cuisine fondamental, riche en antioxydants",
            notesEs: "Ingrediente fundamental de cocina, rico en antioxidantes",
            notesHe: "מרכיב בישול בסיסי, עשיר בנוגדי חמצון"
        ),
        
        // Garlic
        FoodItem(
            id: UUID(),
            name: "Garlic",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 149,
                protein: 6.4,
                carbohydrates: 33,
                fat: 0.5,
                fiber: 2.1,
                sugar: 1.0,
                vitaminA: 0,
                vitaminC: 31,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 1.7,
                thiamin: 0.20,
                riboflavin: 0.11,
                niacin: 0.7,
                vitaminB6: 1.24,
                vitaminB12: 0,
                folate: 3,
                calcium: 181,
                iron: 1.7,
                magnesium: 25,
                phosphorus: 153,
                potassium: 401,
                sodium: 17,
                zinc: 1.2,
                selenium: 14.2,
                omega3: 0.0,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Potent flavor enhancer with antimicrobial properties",
            nameFr: "Ail",
            nameEs: "Ajo",
            nameHe: "שום",
            notesFr: "Exhausteur de goût puissant avec propriétés antimicrobiennes",
            notesEs: "Potente realzador de sabor con propiedades antimicrobianas",
            notesHe: "מעצים טעם חזק עם תכונות אנטי-מיקרוביאליות"
        ),
        
        // Mushrooms (Button)
        FoodItem(
            id: UUID(),
            name: "Button Mushrooms",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 22,
                protein: 3.1,
                carbohydrates: 3.3,
                fat: 0.3,
                fiber: 1.0,
                sugar: 2.0,
                vitaminA: 0,
                vitaminC: 2,
                vitaminD: 0.2,
                vitaminE: 0.0,
                vitaminK: 0,
                thiamin: 0.08,
                riboflavin: 0.40,
                niacin: 3.6,
                vitaminB6: 0.10,
                vitaminB12: 0.04,
                folate: 17,
                calcium: 3,
                iron: 0.5,
                magnesium: 9,
                phosphorus: 86,
                potassium: 318,
                sodium: 5,
                zinc: 0.5,
                selenium: 9.3,
                omega3: 0.0,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of selenium and B vitamins, umami flavor",
            nameFr: "Champignons de Paris",
            nameEs: "Champiñones",
            nameHe: "פטריות",
            notesFr: "Bonne source de sélénium et vitamines B, saveur umami",
            notesEs: "Buena fuente de selenio y vitaminas B, sabor umami",
            notesHe: "מקור טוב לסלניום ווויטמיני B, טעם אומאמי"
        ),
        
        // Eggplant
        FoodItem(
            id: UUID(),
            name: "Eggplant",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.0,
                carbohydrates: 6,
                fat: 0.2,
                fiber: 3.0,
                sugar: 3.5,
                vitaminA: 1,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 3.5,
                thiamin: 0.04,
                riboflavin: 0.04,
                niacin: 0.6,
                vitaminB6: 0.08,
                vitaminB12: 0,
                folate: 22,
                calcium: 9,
                iron: 0.2,
                magnesium: 14,
                phosphorus: 24,
                potassium: 229,
                sodium: 2,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Absorbs flavors well, great for Mediterranean dishes",
            nameFr: "Aubergine",
            nameEs: "Berenjena",
            nameHe: "חציל",
            notesFr: "Absorbe bien les saveurs, excellent pour les plats méditerranéens",
            notesEs: "Absorbe bien los sabores, excelente para platos mediterráneos",
            notesHe: "סופג טעמים היטב, מעולה למנות ים-תיכוניות"
        ),
        
        // Artichoke
        FoodItem(
            id: UUID(),
            name: "Artichoke",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 47,
                protein: 3.3,
                carbohydrates: 11,
                fat: 0.2,
                fiber: 5.4,
                sugar: 1.0,
                vitaminA: 13,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 15,
                thiamin: 0.07,
                riboflavin: 0.07,
                niacin: 1.0,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 68,
                calcium: 44,
                iron: 1.3,
                magnesium: 60,
                phosphorus: 90,
                potassium: 370,
                sodium: 94,
                zinc: 0.5,
                selenium: 0.2,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very high in fiber and folate, elegant appetizer",
            nameFr: "Artichaut",
            nameEs: "Alcachofa",
            nameHe: "ארטישוק",
            notesFr: "Très riche en fibres et folate, apéritif élégant",
            notesEs: "Muy alto en fibra y folato, aperitivo elegante",
            notesHe: "עשיר מאוד בסיבים וחומצה פולית, מתאבן אלגנטי"
        ),
        
        // Leeks
        FoodItem(
            id: UUID(),
            name: "Leeks",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 61,
                protein: 1.5,
                carbohydrates: 14,
                fat: 0.3,
                fiber: 1.8,
                sugar: 3.9,
                vitaminA: 83,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 47,
                thiamin: 0.06,
                riboflavin: 0.03,
                niacin: 0.4,
                vitaminB6: 0.23,
                vitaminB12: 0,
                folate: 64,
                calcium: 59,
                iron: 2.1,
                magnesium: 28,
                phosphorus: 35,
                potassium: 180,
                sodium: 20,
                zinc: 0.1,
                selenium: 1.0,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild onion flavor, excellent in soups and stews",
            nameFr: "Poireaux",
            nameEs: "Puerros",
            nameHe: "כרישה",
            notesFr: "Saveur d'oignon douce, excellent dans les soupes et ragoûts",
            notesEs: "Sabor suave a cebolla, excelente en sopas y guisos",
            notesHe: "טעם בצל עדין, מעולה במרקים ותבשילים"
        ),
        
        // Turnips
        FoodItem(
            id: UUID(),
            name: "Turnips",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 28,
                protein: 0.9,
                carbohydrates: 6.4,
                fat: 0.1,
                fiber: 1.8,
                sugar: 3.8,
                vitaminA: 0,
                vitaminC: 21,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 0.1,
                thiamin: 0.04,
                riboflavin: 0.03,
                niacin: 0.4,
                vitaminB6: 0.09,
                vitaminB12: 0,
                folate: 15,
                calcium: 30,
                iron: 0.3,
                magnesium: 11,
                phosphorus: 27,
                potassium: 191,
                sodium: 67,
                zinc: 0.3,
                selenium: 0.7,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Root vegetable with peppery flavor, good roasted",
            nameFr: "Navets",
            nameEs: "Nabos",
            nameHe: "לפת",
            notesFr: "Légume racine au goût poivré, bon rôti",
            notesEs: "Vegetal de raíz con sabor picante, bueno asado",
            notesHe: "ירק שורש עם טעם חריף, טוב צלוי"
        ),
        
        // Parsnips
        FoodItem(
            id: UUID(),
            name: "Parsnips",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 75,
                protein: 1.2,
                carbohydrates: 18,
                fat: 0.3,
                fiber: 4.9,
                sugar: 4.8,
                vitaminA: 0,
                vitaminC: 17,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 22,
                thiamin: 0.09,
                riboflavin: 0.05,
                niacin: 0.7,
                vitaminB6: 0.09,
                vitaminB12: 0,
                folate: 67,
                calcium: 36,
                iron: 0.6,
                magnesium: 29,
                phosphorus: 71,
                potassium: 375,
                sodium: 10,
                zinc: 0.6,
                selenium: 1.8,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Sweet root vegetable, excellent roasted or in soups",
            nameFr: "Panais",
            nameEs: "Chirivías",
            nameHe: "גזר לבן",
            notesFr: "Légume racine sucré, excellent rôti ou dans les soupes",
            notesEs: "Vegetal de raíz dulce, excelente asado o en sopas",
            notesHe: "ירק שורש מתוק, מעולה צלוי או במרקים"
        ),
        
        // Okra
        FoodItem(
            id: UUID(),
            name: "Okra",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 33,
                protein: 1.9,
                carbohydrates: 7.5,
                fat: 0.2,
                fiber: 3.2,
                sugar: 1.5,
                vitaminA: 36,
                vitaminC: 23,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 32,
                thiamin: 0.20,
                riboflavin: 0.06,
                niacin: 1.0,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 60,
                calcium: 82,
                iron: 0.6,
                magnesium: 57,
                phosphorus: 61,
                potassium: 299,
                sodium: 7,
                zinc: 0.6,
                selenium: 0.7,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate and vitamin C, popular in Southern cuisine",
            nameFr: "Gombo",
            nameEs: "Quimbombó",
            nameHe: "במיה",
            notesFr: "Riche en folate et vitamine C, populaire dans la cuisine du Sud",
            notesEs: "Alto en folato y vitamina C, popular en la cocina sureña",
            notesHe: "עשיר בחומצה פולית ווויטמין C, פופולרי במטבח הדרומי"
        ),
        
        // Swiss Chard
        FoodItem(
            id: UUID(),
            name: "Swiss Chard",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 19,
                protein: 1.8,
                carbohydrates: 3.7,
                fat: 0.2,
                fiber: 1.6,
                sugar: 1.1,
                vitaminA: 306,
                vitaminC: 30,
                vitaminD: 0,
                vitaminE: 1.9,
                vitaminK: 830,
                thiamin: 0.04,
                riboflavin: 0.09,
                niacin: 0.4,
                vitaminB6: 0.10,
                vitaminB12: 0,
                folate: 14,
                calcium: 51,
                iron: 1.8,
                magnesium: 81,
                phosphorus: 46,
                potassium: 379,
                sodium: 213,
                zinc: 0.4,
                selenium: 0.9,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Extremely high in vitamin K, colorful stems and leaves",
            nameFr: "Bette à carde",
            nameEs: "Acelga",
            nameHe: "מנגולד",
            notesFr: "Extrêmement riche en vitamine K, tiges et feuilles colorées",
            notesEs: "Extremadamente alto en vitamina K, tallos y hojas coloridos",
            notesHe: "עשיר במיוחד בוויטמין K, גבעולים ועלים צבעוניים"
        ),
        
        // Bok Choy
        FoodItem(
            id: UUID(),
            name: "Bok Choy",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 13,
                protein: 1.5,
                carbohydrates: 2.2,
                fat: 0.2,
                fiber: 1.0,
                sugar: 1.2,
                vitaminA: 223,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 46,
                thiamin: 0.04,
                riboflavin: 0.07,
                niacin: 0.5,
                vitaminB6: 0.19,
                vitaminB12: 0,
                folate: 66,
                calcium: 105,
                iron: 0.8,
                magnesium: 19,
                phosphorus: 37,
                potassium: 252,
                sodium: 65,
                zinc: 0.2,
                selenium: 0.5,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Asian green high in calcium and vitamin C, mild flavor",
            nameFr: "Pak-choï",
            nameEs: "Bok choy",
            nameHe: "בוק צ'וי",
            notesFr: "Légume vert asiatique riche en calcium et vitamine C, saveur douce",
            notesEs: "Verde asiático alto en calcio y vitamina C, sabor suave",
            notesHe: "ירק אסייתי עשיר בסידן ווויטמין C, טעם עדין"
        ),
        
        // Watercress
        FoodItem(
            id: UUID(),
            name: "Watercress",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 11,
                protein: 2.3,
                carbohydrates: 1.3,
                fat: 0.1,
                fiber: 0.5,
                sugar: 0.2,
                vitaminA: 160,
                vitaminC: 43,
                vitaminD: 0,
                vitaminE: 1.0,
                vitaminK: 250,
                thiamin: 0.09,
                riboflavin: 0.12,
                niacin: 0.2,
                vitaminB6: 0.13,
                vitaminB12: 0,
                folate: 9,
                calcium: 120,
                iron: 0.2,
                magnesium: 21,
                phosphorus: 60,
                potassium: 330,
                sodium: 41,
                zinc: 0.1,
                selenium: 0.3,
                omega3: 0.2,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Peppery superfood, very high in vitamin K and calcium",
            nameFr: "Cresson",
            nameEs: "Berro",
            nameHe: "גרגיר מים",
            notesFr: "Superaliment poivré, très riche en vitamine K et calcium",
            notesEs: "Superalimento picante, muy alto en vitamina K y calcio",
            notesHe: "סופרפוד חריף, עשיר מאוד בוויטמין K וסידן"
        ),
        
        // NEW VEGETABLES - 30 Additional Varieties
        
        // Arugula
        FoodItem(
            id: UUID(),
            name: "Arugula",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 2.6,
                carbohydrates: 3.7,
                fat: 0.7,
                fiber: 1.6,
                sugar: 2.1,
                vitaminA: 2373,
                vitaminC: 15,
                vitaminK: 109,
                folate: 97,
                calcium: 160,
                iron: 1.5,
                magnesium: 47,
                potassium: 369
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Peppery leafy green, excellent in salads",
            nameFr: "Roquette",
            nameEs: "Rúcula",
            nameHe: "רוקט",
            notesFr: "Légume-feuille poivré, excellent en salade",
            notesEs: "Hoja verde picante, excelente en ensaladas",
            notesHe: "עלה ירוק חריף, מעולה בסלטים"
        ),
        
        // Collard Greens
        FoodItem(
            id: UUID(),
            name: "Collard Greens",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 32,
                protein: 3.0,
                carbohydrates: 5.4,
                fat: 0.6,
                fiber: 4.0,
                sugar: 0.5,
                vitaminA: 5019,
                vitaminC: 35,
                vitaminK: 437,
                folate: 129,
                calcium: 232,
                iron: 0.5,
                magnesium: 27,
                potassium: 213
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Nutrient-dense leafy green, traditional Southern vegetable",
            nameFr: "Chou cavalier",
            nameEs: "Berza",
            nameHe: "עלי כרוב",
            notesFr: "Légume-feuille riche en nutriments, légume traditionnel du Sud",
            notesEs: "Hoja verde rica en nutrientes, vegetal tradicional del Sur",
            notesHe: "עלה ירוק עשיר בחומרי מזון, ירק מסורתי דרומי"
        ),
        
        // Fennel
        FoodItem(
            id: UUID(),
            name: "Fennel",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 1.2,
                carbohydrates: 7.3,
                fat: 0.2,
                fiber: 3.1,
                sugar: 3.9,
                vitaminA: 48,
                vitaminC: 12,
                folate: 27,
                calcium: 49,
                iron: 0.7,
                magnesium: 15,
                potassium: 414
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Anise-flavored bulb vegetable, can be eaten raw or cooked",
            nameFr: "Fenouil",
            nameEs: "Hinojo",
            nameHe: "שומר",
            notesFr: "Légume-bulbe au goût d'anis, peut être mangé cru ou cuit",
            notesEs: "Vegetal de bulbo con sabor a anís, se puede comer crudo o cocido",
            notesHe: "ירק בצל בטעם אניס, ניתן לאכול נא או מבושל"
        ),
        
        // Kohlrabi
        FoodItem(
            id: UUID(),
            name: "Kohlrabi",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 27,
                protein: 1.7,
                carbohydrates: 6.2,
                fat: 0.1,
                fiber: 3.6,
                sugar: 2.6,
                vitaminA: 2,
                vitaminC: 62,
                folate: 16,
                calcium: 24,
                iron: 0.4,
                magnesium: 19,
                potassium: 350
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild, sweet flavor, can be eaten raw or cooked",
            nameFr: "Chou-rave",
            nameEs: "Colinabo",
            nameHe: "כרוב קלח",
            notesFr: "Saveur douce et sucrée, peut être mangé cru ou cuit",
            notesEs: "Sabor suave y dulce, se puede comer crudo o cocido",
            notesHe: "טעם עדין ומתוק, ניתן לאכול נא או מבושל"
        ),
        
        // Rutabaga
        FoodItem(
            id: UUID(),
            name: "Rutabaga",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 36,
                protein: 1.2,
                carbohydrates: 8.7,
                fat: 0.2,
                fiber: 2.3,
                sugar: 4.5,
                vitaminA: 0,
                vitaminC: 25,
                folate: 21,
                calcium: 43,
                iron: 0.5,
                magnesium: 20,
                potassium: 305
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Root vegetable with sweet, earthy flavor",
            nameFr: "Rutabaga",
            nameEs: "Colinabo sueco",
            nameHe: "לפת שבדי",
            notesFr: "Légume-racine au goût sucré et terreux",
            notesEs: "Vegetal de raíz con sabor dulce y terroso",
            notesHe: "ירק שורש בטעם מתוק וארצי"
        ),
        
        // Endive
        FoodItem(
            id: UUID(),
            name: "Endive",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 17,
                protein: 1.3,
                carbohydrates: 3.4,
                fat: 0.2,
                fiber: 3.1,
                sugar: 0.3,
                vitaminA: 108,
                vitaminC: 6.5,
                vitaminK: 231,
                folate: 142,
                calcium: 52,
                iron: 0.8,
                magnesium: 15,
                potassium: 314
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Slightly bitter leafy green, great in salads",
            nameFr: "Endive",
            nameEs: "Endivia",
            nameHe: "עולש",
            notesFr: "Légume-feuille légèrement amer, excellent en salade",
            notesEs: "Hoja verde ligeramente amarga, excelente en ensaladas",
            notesHe: "עלה ירוק מעט מר, מעולה בסלטים"
        ),
        
        // Radicchio
        FoodItem(
            id: UUID(),
            name: "Radicchio",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 23,
                protein: 1.4,
                carbohydrates: 4.5,
                fat: 0.3,
                fiber: 0.9,
                sugar: 0.6,
                vitaminA: 0,
                vitaminC: 8,
                vitaminK: 255,
                folate: 60,
                calcium: 19,
                iron: 0.6,
                magnesium: 13,
                potassium: 302
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Purple-red bitter leaf, adds color to salads",
            nameFr: "Radicchio",
            nameEs: "Radicchio",
            nameHe: "רדיקיו",
            notesFr: "Feuille amère rouge-violet, ajoute de la couleur aux salades",
            notesEs: "Hoja amarga rojo-púrpura, añade color a las ensaladas",
            notesHe: "עלה מר אדום-סגול, מוסיף צבע לסלטים"
        ),
        
        // Daikon Radish
        FoodItem(
            id: UUID(),
            name: "Daikon Radish",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 18,
                protein: 0.6,
                carbohydrates: 4.1,
                fat: 0.1,
                fiber: 1.6,
                sugar: 2.5,
                vitaminA: 0,
                vitaminC: 22,
                folate: 28,
                calcium: 27,
                iron: 0.4,
                magnesium: 16,
                potassium: 227
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Large white radish, mild flavor, popular in Asian cuisine",
            nameFr: "Radis daikon",
            nameEs: "Rábano daikon",
            nameHe: "צנון דייקון",
            notesFr: "Grand radis blanc, saveur douce, populaire dans la cuisine asiatique",
            notesEs: "Rábano blanco grande, sabor suave, popular en la cocina asiática",
            notesHe: "צנון לבן גדול, טעם עדין, פופולרי במטבח האסייתי"
        ),
        
        // Jicama
        FoodItem(
            id: UUID(),
            name: "Jicama",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 38,
                protein: 0.7,
                carbohydrates: 8.8,
                fat: 0.1,
                fiber: 4.9,
                sugar: 1.8,
                vitaminA: 0,
                vitaminC: 20,
                folate: 12,
                calcium: 12,
                iron: 0.6,
                magnesium: 12,
                potassium: 150
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy root vegetable with sweet, nutty flavor",
            nameFr: "Jicama",
            nameEs: "Jícama",
            nameHe: "ג'יקמה",
            notesFr: "Légume-racine croquant au goût sucré et de noix",
            notesEs: "Vegetal de raíz crujiente con sabor dulce y a nuez",
            notesHe: "ירק שורש פריך בטעם מתוק ואגוזי"
        ),
        
        // Celeriac
        FoodItem(
            id: UUID(),
            name: "Celeriac",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 42,
                protein: 1.5,
                carbohydrates: 9.2,
                fat: 0.3,
                fiber: 1.8,
                sugar: 1.6,
                vitaminA: 0,
                vitaminC: 8,
                vitaminK: 41,
                folate: 8,
                calcium: 43,
                iron: 0.7,
                magnesium: 20,
                potassium: 300
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Celery root with mild celery flavor, great mashed or roasted",
            nameFr: "Céleri-rave",
            nameEs: "Apio nabo",
            nameHe: "כרפס שורש",
            notesFr: "Racine de céleri au goût doux de céleri, excellent en purée ou rôti",
            notesEs: "Raíz de apio con sabor suave a apio, excelente en puré o asado",
            notesHe: "שורש כרפס בטעם כרפס עדין, מעולה במחית או צלוי"
        ),
        
        // Napa Cabbage
        FoodItem(
            id: UUID(),
            name: "Napa Cabbage",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 16,
                protein: 1.2,
                carbohydrates: 3.2,
                fat: 0.2,
                fiber: 1.2,
                sugar: 1.4,
                vitaminA: 223,
                vitaminC: 12,
                vitaminK: 43,
                folate: 79,
                calcium: 77,
                iron: 0.3,
                magnesium: 9,
                potassium: 238
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild, tender cabbage variety, excellent for kimchi or stir-fries",
            nameFr: "Chou chinois",
            nameEs: "Col china",
            nameHe: "כרוב סיני",
            notesFr: "Variété de chou douce et tendre, excellente pour le kimchi ou les sautés",
            notesEs: "Variedad de col suave y tierna, excelente para kimchi o salteados",
            notesHe: "זן כרוב עדין ורך, מעולה לקימצ'י או למוקפצים"
        ),
        
        // Butternut Squash
        FoodItem(
            id: UUID(),
            name: "Butternut Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 45,
                protein: 1.0,
                carbohydrates: 11.7,
                fat: 0.1,
                fiber: 2.0,
                sugar: 2.2,
                vitaminA: 10630,
                vitaminC: 21,
                vitaminE: 1.4,
                folate: 27,
                calcium: 48,
                iron: 0.7,
                magnesium: 34,
                potassium: 352
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Sweet winter squash, rich in beta-carotene",
            nameFr: "Courge butternut",
            nameEs: "Calabaza butternut",
            nameHe: "דלעת אגוזית",
            notesFr: "Courge d'hiver douce, riche en bêta-carotène",
            notesEs: "Calabaza de invierno dulce, rica en beta-caroteno",
            notesHe: "דלעת חורף מתוקה, עשירה בבטא-קרוטן"
        ),
        
        // Acorn Squash
        FoodItem(
            id: UUID(),
            name: "Acorn Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 40,
                protein: 0.8,
                carbohydrates: 10.4,
                fat: 0.1,
                fiber: 1.6,
                sugar: 0.9,
                vitaminA: 444,
                vitaminC: 11,
                thiamin: 0.1,
                folate: 19,
                calcium: 33,
                iron: 0.7,
                magnesium: 32,
                potassium: 347
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild, slightly sweet winter squash",
            nameFr: "Courge gland",
            nameEs: "Calabaza bellota",
            nameHe: "דלעת בלוט",
            notesFr: "Courge d'hiver douce et légèrement sucrée",
            notesEs: "Calabaza de invierno suave y ligeramente dulce",
            notesHe: "דלעת חורף עדינה ומעט מתוקה"
        ),
        
        // Delicata Squash
        FoodItem(
            id: UUID(),
            name: "Delicata Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 30,
                protein: 0.9,
                carbohydrates: 7.6,
                fat: 0.1,
                fiber: 1.4,
                sugar: 3.8,
                vitaminA: 2167,
                vitaminC: 9,
                folate: 10,
                calcium: 28,
                iron: 0.5,
                magnesium: 16,
                potassium: 287
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Cream-colored squash with green stripes, edible skin",
            nameFr: "Courge delicata",
            nameEs: "Calabaza delicata",
            nameHe: "דלעת דליקטה",
            notesFr: "Courge couleur crème avec des rayures vertes, peau comestible",
            notesEs: "Calabaza color crema con rayas verdes, piel comestible",
            notesHe: "דלעת בצבע קרם עם פסים ירוקים, קליפה אכילה"
        ),
        
        // Spaghetti Squash
        FoodItem(
            id: UUID(),
            name: "Spaghetti Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 0.6,
                carbohydrates: 7.0,
                fat: 0.6,
                fiber: 1.4,
                sugar: 2.8,
                vitaminA: 171,
                vitaminC: 2.8,
                folate: 12,
                calcium: 26,
                iron: 0.3,
                magnesium: 11,
                potassium: 108
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Unique squash that separates into spaghetti-like strands when cooked",
            nameFr: "Courge spaghetti",
            nameEs: "Calabaza espagueti",
            nameHe: "דלעת ספגטי",
            notesFr: "Courge unique qui se sépare en brins semblables à des spaghettis quand elle est cuite",
            notesEs: "Calabaza única que se separa en hebras como espaguetis cuando se cocina",
            notesHe: "דלעת ייחודית שמתפרדת לחוטים דמויי ספגטי כשמבשלים אותה"
        ),
        
        // Kabocha Squash
        FoodItem(
            id: UUID(),
            name: "Kabocha Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 34,
                protein: 1.1,
                carbohydrates: 8.1,
                fat: 0.1,
                fiber: 1.2,
                sugar: 3.5,
                vitaminA: 1104,
                vitaminC: 4,
                folate: 11,
                calcium: 13,
                iron: 0.4,
                magnesium: 13,
                potassium: 350
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Japanese pumpkin with sweet, creamy texture",
            nameFr: "Courge kabocha",
            nameEs: "Calabaza kabocha",
            nameHe: "דלעת קבוצ'ה",
            notesFr: "Citrouille japonaise à la texture douce et crémeuse",
            notesEs: "Calabaza japonesa con textura dulce y cremosa",
            notesHe: "דלעת יפנית במרקם מתוק וקרמי"
        ),
        
        // Hubbard Squash
        FoodItem(
            id: UUID(),
            name: "Hubbard Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 50,
                protein: 2.5,
                carbohydrates: 10.8,
                fat: 0.6,
                fiber: 2.9,
                sugar: 4.3,
                vitaminA: 5755,
                vitaminC: 15,
                folate: 16,
                calcium: 17,
                iron: 0.5,
                magnesium: 15,
                potassium: 358
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Large winter squash with blue-gray or orange skin",
            nameFr: "Courge hubbard",
            nameEs: "Calabaza hubbard",
            nameHe: "דלעת האברד",
            notesFr: "Grande courge d'hiver à la peau bleu-gris ou orange",
            notesEs: "Calabaza de invierno grande con piel azul-gris o naranja",
            notesHe: "דלעת חורף גדולה עם קליפה כחולה-אפורה או כתומה"
        ),
        
        // Pattypan Squash
        FoodItem(
            id: UUID(),
            name: "Pattypan Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 18,
                protein: 1.2,
                carbohydrates: 3.8,
                fat: 0.2,
                fiber: 1.2,
                sugar: 2.5,
                vitaminA: 200,
                vitaminC: 17,
                folate: 29,
                calcium: 15,
                iron: 0.4,
                magnesium: 17,
                potassium: 262
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Small, round, scalloped summer squash",
            nameFr: "Courge pâtisson",
            nameEs: "Calabaza pattypan",
            nameHe: "דלעת פטיפן",
            notesFr: "Petite courge d'été ronde et festonnée",
            notesEs: "Calabaza de verano pequeña, redonda y festoneada",
            notesHe: "דלעת קיץ קטנה, עגולה ומשוננת"
        ),
        
        // Yellow Squash
        FoodItem(
            id: UUID(),
            name: "Yellow Squash",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 16,
                protein: 1.2,
                carbohydrates: 3.4,
                fat: 0.2,
                fiber: 1.1,
                sugar: 2.3,
                vitaminA: 200,
                vitaminC: 17,
                folate: 29,
                calcium: 15,
                iron: 0.4,
                magnesium: 17,
                potassium: 262
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild summer squash with tender skin",
            nameFr: "Courge jaune",
            nameEs: "Calabaza amarilla",
            nameHe: "דלעת צהובה",
            notesFr: "Courge d'été douce à la peau tendre",
            notesEs: "Calabaza de verano suave con piel tierna",
            notesHe: "דלעת קיץ עדינה עם קליפה רכה"
        ),
        
        // Chayote
        FoodItem(
            id: UUID(),
            name: "Chayote",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 19,
                protein: 0.8,
                carbohydrates: 4.5,
                fat: 0.1,
                fiber: 1.7,
                sugar: 1.7,
                vitaminA: 0,
                vitaminC: 7.7,
                folate: 93,
                calcium: 17,
                iron: 0.3,
                magnesium: 12,
                potassium: 125
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild-flavored gourd, popular in Latin American cuisine",
            nameFr: "Chayote",
            nameEs: "Chayote",
            nameHe: "צ'איוטה",
            notesFr: "Courge au goût doux, populaire dans la cuisine latino-américaine",
            notesEs: "Calabaza de sabor suave, popular en la cocina latinoamericana",
            notesHe: "דלעת בטעם עדין, פופולרית במטבח הלטיני-אמריקאי"
        ),
        
        // Plantain
        FoodItem(
            id: UUID(),
            name: "Plantain",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 122,
                protein: 1.3,
                carbohydrates: 31.9,
                fat: 0.4,
                fiber: 2.3,
                sugar: 15.0,
                vitaminA: 1127,
                vitaminC: 18.4,
                vitaminB6: 0.3,
                folate: 22,
                calcium: 3,
                iron: 0.6,
                magnesium: 37,
                potassium: 499
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Starchy cooking banana, can be fried, boiled, or baked",
            nameFr: "Banane plantain",
            nameEs: "Plátano macho",
            nameHe: "בננת בישול",
            notesFr: "Banane féculente à cuire, peut être frite, bouillie ou cuite au four",
            notesEs: "Plátano con almidón para cocinar, se puede freír, hervir o hornear",
            notesHe: "בננת עמילן לבישול, ניתן לטגן, לבשל או לאפות"
        ),
        
        // Cassava
        FoodItem(
            id: UUID(),
            name: "Cassava",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 160,
                protein: 1.4,
                carbohydrates: 38.1,
                fat: 0.3,
                fiber: 1.8,
                sugar: 1.7,
                vitaminA: 13,
                vitaminC: 20.6,
                folate: 27,
                calcium: 16,
                iron: 0.3,
                magnesium: 21,
                potassium: 271
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Starchy root vegetable, must be cooked before eating",
            nameFr: "Manioc",
            nameEs: "Yuca",
            nameHe: "קסאווה",
            notesFr: "Légume-racine féculent, doit être cuit avant consommation",
            notesEs: "Vegetal de raíz con almidón, debe cocinarse antes de comer",
            notesHe: "ירק שורש עמילני, חייב להיות מבושל לפני אכילה"
        ),
        
        // Taro
        FoodItem(
            id: UUID(),
            name: "Taro",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 112,
                protein: 1.5,
                carbohydrates: 26.5,
                fat: 0.2,
                fiber: 4.1,
                sugar: 0.4,
                vitaminA: 76,
                vitaminC: 4.5,
                vitaminE: 2.4,
                folate: 22,
                calcium: 18,
                iron: 0.6,
                magnesium: 33,
                potassium: 591
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Starchy root vegetable, popular in Pacific and Asian cuisines",
            nameFr: "Taro",
            nameEs: "Taro",
            nameHe: "טארו",
            notesFr: "Légume-racine féculent, populaire dans les cuisines du Pacifique et d'Asie",
            notesEs: "Vegetal de raíz con almidón, popular en cocinas del Pacífico y asiáticas",
            notesHe: "ירק שורש עמילני, פופולרי במטבחים של האוקיינוס השקט ואסיה"
        ),
        
        // Yam
        FoodItem(
            id: UUID(),
            name: "Yam",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 118,
                protein: 1.5,
                carbohydrates: 27.9,
                fat: 0.2,
                fiber: 4.1,
                sugar: 0.5,
                vitaminA: 138,
                vitaminC: 17.1,
                thiamin: 0.1,
                folate: 23,
                calcium: 17,
                iron: 0.5,
                magnesium: 21,
                potassium: 816
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Starchy tuber, different from sweet potato",
            nameFr: "Igname",
            nameEs: "Ñame",
            nameHe: "בטטת יער",
            notesFr: "Tubercule féculent, différent de la patate douce",
            notesEs: "Tubérculo con almidón, diferente del camote",
            notesHe: "פקעת עמילנית, שונה מבטטה"
        ),
        
        // Malanga
        FoodItem(
            id: UUID(),
            name: "Malanga",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 98,
                protein: 1.6,
                carbohydrates: 22.3,
                fat: 0.2,
                fiber: 1.5,
                sugar: 0.4,
                vitaminA: 35,
                vitaminC: 11.2,
                folate: 22,
                calcium: 84,
                iron: 0.9,
                magnesium: 25,
                potassium: 319
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Starchy root vegetable, popular in Caribbean cuisine",
            nameFr: "Malanga",
            nameEs: "Malanga",
            nameHe: "מלנגה",
            notesFr: "Légume-racine féculent, populaire dans la cuisine caribéenne",
            notesEs: "Vegetal de raíz con almidón, popular en la cocina caribeña",
            notesHe: "ירק שורש עמילני, פופולרי במטבח הקריבי"
        ),
        
        // Lotus Root
        FoodItem(
            id: UUID(),
            name: "Lotus Root",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 74,
                protein: 2.6,
                carbohydrates: 17.2,
                fat: 0.1,
                fiber: 4.9,
                sugar: 0.5,
                vitaminA: 0,
                vitaminC: 44,
                thiamin: 0.2,
                folate: 13,
                calcium: 45,
                iron: 1.2,
                magnesium: 23,
                potassium: 556
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Crunchy aquatic vegetable with distinctive holes, popular in Asian cuisine",
            nameFr: "Racine de lotus",
            nameEs: "Raíz de loto",
            nameHe: "שורש לוטוס",
            notesFr: "Légume aquatique croquant avec des trous distinctifs, populaire dans la cuisine asiatique",
            notesEs: "Vegetal acuático crujiente con agujeros distintivos, popular en la cocina asiática",
            notesHe: "ירק מימי פריך עם חורים מאפיינים, פופולרי במטבח האסייתי"
        ),
        
        // Water Chestnuts
        FoodItem(
            id: UUID(),
            name: "Water Chestnuts",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 97,
                protein: 1.4,
                carbohydrates: 23.9,
                fat: 0.1,
                fiber: 3.0,
                sugar: 4.8,
                vitaminA: 0,
                vitaminC: 4,
                thiamin: 0.1,
                folate: 16,
                calcium: 11,
                iron: 0.6,
                magnesium: 22,
                potassium: 584
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Crunchy aquatic vegetable, stays crisp when cooked",
            nameFr: "Châtaignes d'eau",
            nameEs: "Castañas de agua",
            nameHe: "ערמונים מימיים",
            notesFr: "Légume aquatique croquant, reste croustillant quand cuit",
            notesEs: "Vegetal acuático crujiente, se mantiene crujiente cuando se cocina",
            notesHe: "ירק מימי פריך, נשאר פריך כשמבשלים"
        ),
        
        // Bamboo Shoots
        FoodItem(
            id: UUID(),
            name: "Bamboo Shoots",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 27,
                protein: 2.6,
                carbohydrates: 5.2,
                fat: 0.3,
                fiber: 2.2,
                sugar: 3.0,
                vitaminA: 20,
                vitaminC: 4,
                thiamin: 0.2,
                folate: 7,
                calcium: 13,
                iron: 0.5,
                magnesium: 3,
                potassium: 533
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Young bamboo shoots, tender and mild flavor",
            nameFr: "Pousses de bambou",
            nameEs: "Brotes de bambú",
            nameHe: "נבטי במבוק",
            notesFr: "Jeunes pousses de bambou, tendres et au goût doux",
            notesEs: "Brotes jóvenes de bambú, tiernos y de sabor suave",
            notesHe: "נבטי במבוק צעירים, רכים ובטעם עדין"
        ),
        
        // Hearts of Palm
        FoodItem(
            id: UUID(),
            name: "Hearts of Palm",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 28,
                protein: 2.7,
                carbohydrates: 4.6,
                fat: 0.2,
                fiber: 2.4,
                sugar: 0.0,
                vitaminA: 0,
                vitaminC: 7.9,
                folate: 25,
                calcium: 58,
                iron: 0.6,
                magnesium: 37,
                potassium: 177
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Tender inner core of palm trees, mild artichoke-like flavor",
            nameFr: "Cœurs de palmier",
            nameEs: "Palmitos",
            nameHe: "לבבות דקל",
            notesFr: "Cœur tendre intérieur des palmiers, goût doux semblable à l'artichaut",
            notesEs: "Núcleo tierno interior de las palmeras, sabor suave parecido a la alcachofa",
            notesHe: "ליבה רכה פנימית של עצי דקל, טעם עדין דומה לארטישוק"
        ),
        
        // Mustard Greens
        FoodItem(
            id: UUID(),
            name: "Mustard Greens",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 27,
                protein: 2.9,
                carbohydrates: 4.7,
                fat: 0.4,
                fiber: 3.2,
                sugar: 1.3,
                vitaminA: 3024,
                vitaminC: 70,
                vitaminK: 257,
                folate: 12,
                calcium: 115,
                iron: 1.6,
                magnesium: 32,
                potassium: 384
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Peppery leafy green, rich in vitamins A and K",
            nameFr: "Feuilles de moutarde",
            nameEs: "Hojas de mostaza",
            nameHe: "עלי חרדל",
            notesFr: "Légume-feuille poivré, riche en vitamines A et K",
            notesEs: "Hoja verde picante, rica en vitaminas A y K",
            notesHe: "עלה ירוק חריף, עשיר בויטמינים A ו-K"
        ),
        
        // Turnip Greens
        FoodItem(
            id: UUID(),
            name: "Turnip Greens",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 32,
                protein: 1.5,
                carbohydrates: 7.1,
                fat: 0.3,
                fiber: 3.2,
                sugar: 0.8,
                vitaminA: 579,
                vitaminC: 60,
                vitaminK: 251,
                folate: 194,
                calcium: 190,
                iron: 1.1,
                magnesium: 31,
                potassium: 296
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Leafy tops of turnips, slightly bitter and nutritious",
            nameFr: "Fanes de navet",
            nameEs: "Hojas de nabo",
            nameHe: "עלי לפת",
            notesFr: "Feuilles de navet, légèrement amères et nutritives",
            notesEs: "Hojas de nabo, ligeramente amargas y nutritivas",
            notesHe: "עלי לפת, מעט מרים ומזינים"
        ),
        
        // Dandelion Greens
        FoodItem(
            id: UUID(),
            name: "Dandelion Greens",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 45,
                protein: 2.7,
                carbohydrates: 9.2,
                fat: 0.7,
                fiber: 3.5,
                sugar: 0.7,
                vitaminA: 5588,
                vitaminC: 35,
                vitaminK: 778,
                folate: 27,
                calcium: 187,
                iron: 3.1,
                magnesium: 36,
                potassium: 397
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Wild edible green, very bitter but highly nutritious",
            nameFr: "Feuilles de pissenlit",
            nameEs: "Hojas de diente de león",
            nameHe: "עלי שן הארי",
            notesFr: "Légume sauvage comestible, très amer mais très nutritif",
            notesEs: "Verde silvestre comestible, muy amargo pero altamente nutritivo",
            notesHe: "ירק בר אכיל, מר מאוד אך מזין ביותר"
        )
    ]
}
