import Foundation

struct GrainDishItems {
    static let foods: [FoodItem] = [
        // Quinoa Bowl
        FoodItem(
            id: UUID(),
            name: "Quinoa Bowl with Vegetables",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 8.5,
                carbohydrates: 39,
                fat: 4.2,
                fiber: 5.8,
                sugar: 2.1,
                vitaminA: 450,
                vitaminC: 25,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 15,
                thiamin: 0.2,
                riboflavin: 0.3,
                niacin: 2.1,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 78,
                calcium: 45,
                iron: 3.2,
                magnesium: 120,
                phosphorus: 200,
                potassium: 400,
                sodium: 180,
                zinc: 2.1,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Cooked quinoa with mixed vegetables and herbs",
            nameFr: "Bol de Quinoa aux Légumes",
            nameEs: "Tazón de Quinua con Verduras",
            nameHe: "קערת קינואה עם ירקות",
            notesFr: "Quinoa cuit avec légumes mélangés et herbes",
            notesEs: "Quinua cocida con verduras mixtas y hierbas",
            notesHe: "קינואה מבושלת עם ירקות מעורבים ועשבי תיבול"
        ),
        
        // Brown Rice Pilaf
        FoodItem(
            id: UUID(),
            name: "Brown Rice Pilaf",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 4.2,
                carbohydrates: 38,
                fat: 2.8,
                fiber: 3.5,
                sugar: 0.8,
                vitaminA: 120,
                vitaminC: 8,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 2.5,
                thiamin: 0.3,
                riboflavin: 0.1,
                niacin: 3.2,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 25,
                calcium: 20,
                iron: 1.8,
                magnesium: 85,
                phosphorus: 150,
                potassium: 200,
                sodium: 250,
                zinc: 1.5,
                selenium: 12,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Brown rice cooked with onions, garlic, and herbs",
            nameFr: "Pilaf de Riz Brun",
            nameEs: "Pilaf de Arroz Integral",
            nameHe: "פילאף אורז חום",
            notesFr: "Riz brun cuit avec oignons, ail et herbes",
            notesEs: "Arroz integral cocido con cebollas, ajo y hierbas",
            notesHe: "אורז חום מבושל עם בצל, שום ועשבי תיבול"
        ),
        
        // Couscous Salad
        FoodItem(
            id: UUID(),
            name: "Mediterranean Couscous Salad",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 195,
                protein: 6.8,
                carbohydrates: 35,
                fat: 4.5,
                fiber: 3.2,
                sugar: 3.8,
                vitaminA: 680,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 2.1,
                vitaminK: 25,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.8,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 35,
                calcium: 45,
                iron: 1.5,
                magnesium: 55,
                phosphorus: 120,
                potassium: 280,
                sodium: 320,
                zinc: 1.2,
                selenium: 15,
                omega3: 0.4,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Couscous with tomatoes, cucumbers, olives, and feta cheese",
            nameFr: "Salade de Couscous Méditerranéenne",
            nameEs: "Ensalada de Cuscús Mediterránea",
            nameHe: "סלט קוסקוס ים תיכוני",
            notesFr: "Couscous avec tomates, concombres, olives et feta",
            notesEs: "Cuscús con tomates, pepinos, aceitunas y queso feta",
            notesHe: "קוסקוס עם עגבניות, מלפפונים, זיתים וגבינת פטה"
        ),
        
        // Farro Risotto
        FoodItem(
            id: UUID(),
            name: "Farro Risotto with Mushrooms",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 9.2,
                carbohydrates: 42,
                fat: 6.8,
                fiber: 4.5,
                sugar: 2.2,
                vitaminA: 180,
                vitaminC: 12,
                vitaminD: 0.8,
                vitaminE: 1.5,
                vitaminK: 8,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 4.2,
                vitaminB6: 0.5,
                vitaminB12: 0.1,
                folate: 45,
                calcium: 35,
                iron: 2.8,
                magnesium: 95,
                phosphorus: 180,
                potassium: 320,
                sodium: 380,
                zinc: 2.1,
                selenium: 18,
                omega3: 0.2,
                omega6: 1.5,
                cholesterol: 8
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Creamy farro risotto with sautéed mushrooms and parmesan",
            nameFr: "Risotto de Farro aux Champignons",
            nameEs: "Risotto de Farro con Champiñones",
            nameHe: "ריזוטו פארו עם פטריות",
            notesFr: "Risotto crémeux de farro avec champignons sautés et parmesan",
            notesEs: "Risotto cremoso de farro con champiñones salteados y parmesano",
            notesHe: "ריזוטו פארו קרמי עם פטריות מוקפצות ופרמזן"
        ),
        
        // Bulgur Wheat Tabouleh
        FoodItem(
            id: UUID(),
            name: "Bulgur Wheat Tabouleh",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 5.5,
                carbohydrates: 28,
                fat: 4.2,
                fiber: 6.8,
                sugar: 2.5,
                vitaminA: 1200,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 180,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.5,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 55,
                calcium: 65,
                iron: 2.2,
                magnesium: 75,
                phosphorus: 120,
                potassium: 420,
                sodium: 280,
                zinc: 1.8,
                selenium: 12,
                omega3: 0.3,
                omega6: 1.1,
                cholesterol: 0
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional Middle Eastern salad with bulgur, parsley, and tomatoes",
            nameFr: "Taboulé de Blé Boulgour",
            nameEs: "Tabulé de Trigo Bulgur",
            nameHe: "טאבולה בורגול",
            notesFr: "Salade traditionnelle du Moyen-Orient avec boulgour, persil et tomates",
            notesEs: "Ensalada tradicional del Medio Oriente con bulgur, perejil y tomates",
            notesHe: "סלט מסורתי מהמזרח התיכון עם בורגול, פטרוזיליה ועגבניות"
        ),
        
        // Wild Rice Blend
        FoodItem(
            id: UUID(),
            name: "Wild Rice Blend with Herbs",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 195,
                protein: 7.8,
                carbohydrates: 38,
                fat: 1.2,
                fiber: 4.2,
                sugar: 1.5,
                vitaminA: 85,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 3.2,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 4.5,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 35,
                calcium: 25,
                iron: 2.1,
                magnesium: 95,
                phosphorus: 180,
                potassium: 280,
                sodium: 180,
                zinc: 2.2,
                selenium: 15,
                omega3: 0.2,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 160,
            servingUnit: "g",
            isCustom: true,
            notes: "Mixed wild rice with fresh herbs and lemon",
            nameFr: "Mélange de Riz Sauvage aux Herbes",
            nameEs: "Mezcla de Arroz Salvaje con Hierbas",
            nameHe: "תערובת אורז בר עם עשבי תיבול",
            notesFr: "Mélange de riz sauvage avec herbes fraîches et citron",
            notesEs: "Mezcla de arroz salvaje con hierbas frescas y limón",
            notesHe: "תערובת אורז בר עם עשבי תיבול טריים ולימון"
        ),
        
        // Barley Soup
        FoodItem(
            id: UUID(),
            name: "Barley and Vegetable Soup",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 145,
                protein: 6.2,
                carbohydrates: 28,
                fat: 2.1,
                fiber: 5.8,
                sugar: 3.2,
                vitaminA: 680,
                vitaminC: 22,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 25,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 3.2,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 45,
                calcium: 35,
                iron: 2.5,
                magnesium: 65,
                phosphorus: 120,
                potassium: 380,
                sodium: 420,
                zinc: 1.8,
                selenium: 12,
                omega3: 0.2,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Hearty soup with pearl barley, carrots, celery, and herbs",
            nameFr: "Soupe d'Orge et Légumes",
            nameEs: "Sopa de Cebada y Verduras",
            nameHe: "מרק שעורה וירקות",
            notesFr: "Soupe copieuse avec orge perlé, carottes, céleri et herbes",
            notesEs: "Sopa sustanciosa con cebada perlada, zanahorias, apio y hierbas",
            notesHe: "מרק משביע עם שעורה פנינה, גזר, סלרי ועשבי תיבול"
        ),
        
        // Millet Porridge
        FoodItem(
            id: UUID(),
            name: "Millet Porridge with Berries",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.5,
                carbohydrates: 32,
                fat: 3.8,
                fiber: 4.2,
                sugar: 8.5,
                vitaminA: 120,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 2.5,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 2.8,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 35,
                calcium: 45,
                iron: 2.1,
                magnesium: 85,
                phosphorus: 150,
                potassium: 220,
                sodium: 85,
                zinc: 1.5,
                selenium: 8,
                omega3: 0.3,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Warm millet porridge topped with fresh berries and honey",
            nameFr: "Bouillie de Millet aux Baies",
            nameEs: "Gachas de Mijo con Bayas",
            nameHe: "דייסת דוחן עם פירות יער",
            notesFr: "Bouillie chaude de millet garnie de baies fraîches et miel",
            notesEs: "Gachas calientes de mijo con bayas frescas y miel",
            notesHe: "דייסת דוחן חמה עם פירות יער טריים ודבש"
        ),
        
        // Sorghum Pilaf
        FoodItem(
            id: UUID(),
            name: "Sorghum Pilaf with Nuts",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 8.8,
                carbohydrates: 38,
                fat: 6.5,
                fiber: 5.2,
                sugar: 2.8,
                vitaminA: 95,
                vitaminC: 8,
                vitaminD: 0,
                vitaminE: 2.5,
                vitaminK: 3.8,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.8,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 42,
                calcium: 35,
                iron: 2.8,
                magnesium: 95,
                phosphorus: 180,
                potassium: 320,
                sodium: 220,
                zinc: 2.2,
                selenium: 15,
                omega3: 0.4,
                omega6: 2.1,
                cholesterol: 0
            ),
            servingSize: 170,
            servingUnit: "g",
            isCustom: true,
            notes: "Nutty sorghum pilaf with almonds and dried cranberries",
            nameFr: "Pilaf de Sorgho aux Noix",
            nameEs: "Pilaf de Sorgo con Frutos Secos",
            nameHe: "פילאף דורה עם אגוזים",
            notesFr: "Pilaf de sorgho aux amandes et canneberges séchées",
            notesEs: "Pilaf de sorgo con almendras y arándanos secos",
            notesHe: "פילאף דורה עם שקדים וחמוציות מיובשות"
        ),
        
        // Teff Pancakes
        FoodItem(
            id: UUID(),
            name: "Teff Pancakes",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 195,
                protein: 7.2,
                carbohydrates: 28,
                fat: 6.8,
                fiber: 3.5,
                sugar: 4.2,
                vitaminA: 85,
                vitaminC: 2,
                vitaminD: 0.8,
                vitaminE: 1.2,
                vitaminK: 1.5,
                thiamin: 0.2,
                riboflavin: 0.3,
                niacin: 2.5,
                vitaminB6: 0.3,
                vitaminB12: 0.2,
                folate: 35,
                calcium: 85,
                iron: 3.2,
                magnesium: 75,
                phosphorus: 150,
                potassium: 220,
                sodium: 280,
                zinc: 1.8,
                selenium: 12,
                omega3: 0.2,
                omega6: 1.5,
                cholesterol: 45
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Gluten-free teff flour pancakes with maple syrup",
            nameFr: "Crêpes de Teff",
            nameEs: "Panqueques de Teff",
            nameHe: "פנקייק טף",
            notesFr: "Crêpes sans gluten à base de farine de teff avec sirop d'érable",
            notesEs: "Panqueques sin gluten de harina de teff con jarabe de arce",
            notesHe: "פנקייק טף ללא גלוטן עם סירופ מייפל"
        ),
        
        // Amaranth Porridge
        FoodItem(
            id: UUID(),
            name: "Amaranth Porridge with Cinnamon",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 175,
                protein: 7.8,
                carbohydrates: 28,
                fat: 4.2,
                fiber: 4.8,
                sugar: 2.5,
                vitaminA: 65,
                vitaminC: 3,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 1.8,
                thiamin: 0.2,
                riboflavin: 0.3,
                niacin: 2.8,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 45,
                calcium: 95,
                iron: 4.2,
                magnesium: 120,
                phosphorus: 180,
                potassium: 280,
                sodium: 65,
                zinc: 2.5,
                selenium: 8,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 160,
            servingUnit: "g",
            isCustom: true,
            notes: "Warm amaranth porridge with cinnamon and brown sugar",
            nameFr: "Bouillie d'Amarante à la Cannelle",
            nameEs: "Gachas de Amaranto con Canela",
            nameHe: "דייסת אמרנט עם קינמון",
            notesFr: "Bouillie chaude d'amarante avec cannelle et cassonade",
            notesEs: "Gachas calientes de amaranto con canela y azúcar moreno",
            notesHe: "דייסת אמרנט חמה עם קינמון וסוכר חום"
        ),
        
        // Buckwheat Noodles
        FoodItem(
            id: UUID(),
            name: "Buckwheat Soba Noodles",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 8.5,
                carbohydrates: 32,
                fat: 2.2,
                fiber: 3.8,
                sugar: 1.5,
                vitaminA: 45,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 1.2,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.5,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 35,
                calcium: 25,
                iron: 2.8,
                magnesium: 85,
                phosphorus: 150,
                potassium: 220,
                sodium: 280,
                zinc: 1.8,
                selenium: 12,
                omega3: 0.2,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Japanese soba noodles made from buckwheat flour",
            nameFr: "Nouilles Soba de Sarrasin",
            nameEs: "Fideos Soba de Trigo Sarraceno",
            nameHe: "נודלס סובה כוסמת",
            notesFr: "Nouilles soba japonaises à base de farine de sarrasin",
            notesEs: "Fideos soba japoneses de harina de trigo sarraceno",
            notesHe: "נודלס סובה יפניים מקמח כוסמת"
        ),
        
        // Spelt Bread
        FoodItem(
            id: UUID(),
            name: "Spelt Bread",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 10.5,
                carbohydrates: 42,
                fat: 4.8,
                fiber: 5.2,
                sugar: 2.8,
                vitaminA: 25,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 2.5,
                thiamin: 0.4,
                riboflavin: 0.3,
                niacin: 4.2,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 55,
                calcium: 45,
                iron: 3.5,
                magnesium: 95,
                phosphorus: 180,
                potassium: 280,
                sodium: 380,
                zinc: 2.2,
                selenium: 25,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Whole grain spelt bread, sliced",
            nameFr: "Pain d'Épeautre",
            nameEs: "Pan de Espelta",
            nameHe: "לחם כוסמין",
            notesFr: "Pain de grains entiers d'épeautre, tranché",
            notesEs: "Pan de espelta integral, rebanado",
            notesHe: "לחם כוסמין מלא, פרוס"
        ),
        
        // Rye Bread
        FoodItem(
            id: UUID(),
            name: "Dark Rye Bread",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 235,
                protein: 9.8,
                carbohydrates: 45,
                fat: 3.2,
                fiber: 6.8,
                sugar: 2.2,
                vitaminA: 15,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 3.2,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.8,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 65,
                calcium: 55,
                iron: 3.8,
                magnesium: 85,
                phosphorus: 180,
                potassium: 320,
                sodium: 420,
                zinc: 2.5,
                selenium: 28,
                omega3: 0.3,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional dark rye bread with caraway seeds",
            nameFr: "Pain de Seigle Noir",
            nameEs: "Pan de Centeno Oscuro",
            nameHe: "לחם שיפון כהה",
            notesFr: "Pain de seigle noir traditionnel avec graines de carvi",
            notesEs: "Pan de centeno oscuro tradicional con semillas de alcaravea",
            notesHe: "לחם שיפון כהה מסורתי עם זרעי כרוויה"
        )
    ]
} 