import Foundation

struct IndianCuisineFoodItems {
    static let foods: [FoodItem] = [
        // Chicken Tikka Masala
        FoodItem(
            id: UUID(),
            name: "Chicken Tikka Masala",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 24.5,
                carbohydrates: 12,
                fat: 22.8,
                fiber: 2.8,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 15,
                vitaminD: 0.3,
                vitaminE: 2.2,
                vitaminK: 12,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 8.5,
                vitaminB6: 0.52,
                vitaminB12: 2.2,
                folate: 28,
                calcium: 125,
                iron: 2.8,
                magnesium: 45,
                phosphorus: 225,
                potassium: 485,
                sodium: 685,
                zinc: 3.2,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 75
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Tender chicken in creamy tomato-based curry with aromatic spices",
            nameFr: "Poulet Tikka Masala",
            nameEs: "Pollo Tikka Masala",
            nameHe: "עוף טיקה מסאלה",
            notesFr: "Poulet tendre dans un curry crémeux à base de tomate avec des épices aromatiques",
            notesEs: "Pollo tierno en curry cremoso a base de tomate con especias aromáticas",
            notesHe: "עוף רך בקארי קרמי על בסיס עגבניות עם תבלינים ארומטיים"
        ),
        
        // Dal Tadka
        FoodItem(
            id: UUID(),
            name: "Dal Tadka",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 12.5,
                carbohydrates: 28,
                fat: 4.2,
                fiber: 8.5,
                sugar: 3.2,
                vitaminA: 45,
                vitaminC: 8,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 5,
                thiamin: 0.22,
                riboflavin: 0.15,
                niacin: 2.8,
                vitaminB6: 0.28,
                vitaminB12: 0,
                folate: 185,
                calcium: 65,
                iron: 3.8,
                magnesium: 85,
                phosphorus: 185,
                potassium: 485,
                sodium: 485,
                zinc: 2.2,
                selenium: 8.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Yellow lentils tempered with cumin, mustard seeds, and curry leaves",
            nameFr: "Dal Tadka",
            nameEs: "Dal Tadka",
            nameHe: "דאל טאדקה",
            notesFr: "Lentilles jaunes tempérées avec du cumin, des graines de moutarde et des feuilles de curry",
            notesEs: "Lentejas amarillas temperadas con comino, semillas de mostaza y hojas de curry",
            notesHe: "עדשים צהובות מתובלות בכמון, זרעי חרדל ועלי קארי"
        ),
        
        // Biryani
        FoodItem(
            id: UUID(),
            name: "Chicken Biryani",
            category: .grains,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 22.8,
                carbohydrates: 45,
                fat: 12.5,
                fiber: 3.2,
                sugar: 6.8,
                vitaminA: 125,
                vitaminC: 12,
                vitaminD: 0.2,
                vitaminE: 1.8,
                vitaminK: 8,
                thiamin: 0.25,
                riboflavin: 0.18,
                niacin: 6.8,
                vitaminB6: 0.45,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 85,
                iron: 2.8,
                magnesium: 55,
                phosphorus: 205,
                potassium: 385,
                sodium: 585,
                zinc: 3.5,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 65
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Fragrant basmati rice layered with spiced chicken and aromatic herbs",
            nameFr: "Biryani de Poulet",
            nameEs: "Biryani de Pollo",
            nameHe: "ביריאני עוף",
            notesFr: "Riz basmati parfumé en couches avec du poulet épicé et des herbes aromatiques",
            notesEs: "Arroz basmati fragante en capas con pollo especiado y hierbas aromáticas",
            notesHe: "אורז בסמטי ארומטי בשכבות עם עוף מתובל ועשבי תיבול"
        ),
        
        // Palak Paneer
        FoodItem(
            id: UUID(),
            name: "Palak Paneer",
            category: .vegetables,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 14.5,
                carbohydrates: 12,
                fat: 16.8,
                fiber: 4.2,
                sugar: 6.8,
                vitaminA: 485,
                vitaminC: 45,
                vitaminD: 0.2,
                vitaminE: 2.8,
                vitaminK: 185,
                thiamin: 0.12,
                riboflavin: 0.32,
                niacin: 2.2,
                vitaminB6: 0.25,
                vitaminB12: 0.8,
                folate: 125,
                calcium: 285,
                iron: 4.2,
                magnesium: 85,
                phosphorus: 185,
                potassium: 585,
                sodium: 485,
                zinc: 2.8,
                selenium: 12.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 25
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Creamy spinach curry with cubes of fresh cottage cheese",
            nameFr: "Palak Paneer",
            nameEs: "Palak Paneer",
            nameHe: "פאלק פאניר",
            notesFr: "Curry d'épinards crémeux avec des cubes de fromage cottage frais",
            notesEs: "Curry cremoso de espinacas con cubos de queso cottage fresco",
            notesHe: "קארי תרד קרמי עם קוביות גבינת קוטג' טרייה"
        ),
        
        // Butter Chicken
        FoodItem(
            id: UUID(),
            name: "Butter Chicken",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 365,
                protein: 26.5,
                carbohydrates: 8,
                fat: 26.8,
                fiber: 2.2,
                sugar: 6.5,
                vitaminA: 225,
                vitaminC: 12,
                vitaminD: 0.8,
                vitaminE: 2.8,
                vitaminK: 8,
                thiamin: 0.15,
                riboflavin: 0.28,
                niacin: 9.2,
                vitaminB6: 0.55,
                vitaminB12: 2.5,
                folate: 22,
                calcium: 145,
                iron: 2.2,
                magnesium: 38,
                phosphorus: 245,
                potassium: 385,
                sodium: 685,
                zinc: 3.8,
                selenium: 25.5,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 85
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Rich and creamy tomato-based curry with tender chicken pieces",
            nameFr: "Poulet au Beurre",
            nameEs: "Pollo a la Mantequilla",
            nameHe: "עוף חמאה",
            notesFr: "Curry riche et crémeux à base de tomate avec des morceaux de poulet tendres",
            notesEs: "Curry rico y cremoso a base de tomate con trozos de pollo tierno",
            notesHe: "קארי עשיר וקרמי על בסיס עגבניות עם חתיכות עוף רכות"
        ),
        
        // Naan Bread
        FoodItem(
            id: UUID(),
            name: "Garlic Naan",
            category: .grains,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 8.5,
                carbohydrates: 45,
                fat: 8.2,
                fiber: 2.8,
                sugar: 3.5,
                vitaminA: 45,
                vitaminC: 2,
                vitaminD: 0.2,
                vitaminE: 1.2,
                vitaminK: 4,
                thiamin: 0.35,
                riboflavin: 0.18,
                niacin: 4.2,
                vitaminB6: 0.15,
                vitaminB12: 0.2,
                folate: 85,
                calcium: 125,
                iron: 2.8,
                magnesium: 35,
                phosphorus: 125,
                potassium: 185,
                sodium: 485,
                zinc: 1.8,
                selenium: 12.5,
                omega3: 0.2,
                omega6: 2.8,
                cholesterol: 15
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Soft leavened flatbread baked in tandoor with garlic and herbs",
            nameFr: "Naan à l'Ail",
            nameEs: "Naan de Ajo",
            nameHe: "נאן שום",
            notesFr: "Pain plat levé et moelleux cuit au tandoor avec de l'ail et des herbes",
            notesEs: "Pan plano suave leudado horneado en tandoor con ajo y hierbas",
            notesHe: "לחם שטוח רך ותפוח אפוי בתנדור עם שום ועשבי תיבול"
        ),
        
        // Samosas
        FoodItem(
            id: UUID(),
            name: "Vegetable Samosas",
            category: .snacks,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 265,
                protein: 6.8,
                carbohydrates: 32,
                fat: 12.5,
                fiber: 4.2,
                sugar: 4.8,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0,
                vitaminE: 2.2,
                vitaminK: 15,
                thiamin: 0.18,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.28,
                vitaminB12: 0,
                folate: 45,
                calcium: 85,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 125,
                potassium: 385,
                sodium: 485,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 4.2,
                cholesterol: 0
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy triangular pastries filled with spiced potatoes and peas",
            nameFr: "Samosas aux Légumes",
            nameEs: "Samosas de Verduras",
            nameHe: "סמוסות ירקות",
            notesFr: "Pâtisseries triangulaires croustillantes farcies de pommes de terre épicées et de petits pois",
            notesEs: "Pasteles triangulares crujientes rellenos de papas especiadas y guisantes",
            notesHe: "מאפים משולשים פריכים ממולאים תפוחי אדמה מתובלים ואפונה"
        ),
        
        // Tandoori Chicken
        FoodItem(
            id: UUID(),
            name: "Tandoori Chicken",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 28.5,
                carbohydrates: 4,
                fat: 12.8,
                fiber: 0.8,
                sugar: 2.5,
                vitaminA: 125,
                vitaminC: 8,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 5,
                thiamin: 0.15,
                riboflavin: 0.22,
                niacin: 9.8,
                vitaminB6: 0.58,
                vitaminB12: 2.8,
                folate: 18,
                calcium: 65,
                iron: 2.2,
                magnesium: 35,
                phosphorus: 225,
                potassium: 385,
                sodium: 585,
                zinc: 3.8,
                selenium: 28.5,
                omega3: 0.2,
                omega6: 2.2,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Marinated chicken roasted in clay oven with yogurt and spices",
            nameFr: "Poulet Tandoori",
            nameEs: "Pollo Tandoori",
            nameHe: "עוף טנדורי",
            notesFr: "Poulet mariné rôti dans un four en argile avec du yaourt et des épices",
            notesEs: "Pollo marinado asado en horno de barro con yogur y especias",
            notesHe: "עוף מרינדה צלוי בתנור חימר עם יוגורט ותבלינים"
        ),
        
        // Rajma
        FoodItem(
            id: UUID(),
            name: "Rajma",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 14.8,
                carbohydrates: 32,
                fat: 5.2,
                fiber: 9.8,
                sugar: 4.2,
                vitaminA: 65,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 8,
                thiamin: 0.25,
                riboflavin: 0.18,
                niacin: 3.2,
                vitaminB6: 0.32,
                vitaminB12: 0,
                folate: 185,
                calcium: 85,
                iron: 4.2,
                magnesium: 125,
                phosphorus: 185,
                potassium: 585,
                sodium: 485,
                zinc: 2.8,
                selenium: 12.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Red kidney beans in spiced tomato-onion gravy",
            nameFr: "Rajma",
            nameEs: "Rajma",
            nameHe: "ראג'מה",
            notesFr: "Haricots rouges dans une sauce épicée tomate-oignon",
            notesEs: "Frijoles rojos en salsa especiada de tomate y cebolla",
            notesHe: "שעועית אדומה ברוטב מתובל עגבניות ובצל"
        ),
        
        // Chole
        FoodItem(
            id: UUID(),
            name: "Chole",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 205,
                protein: 12.8,
                carbohydrates: 28,
                fat: 6.2,
                fiber: 8.5,
                sugar: 5.2,
                vitaminA: 85,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 12,
                thiamin: 0.22,
                riboflavin: 0.15,
                niacin: 2.8,
                vitaminB6: 0.28,
                vitaminB12: 0,
                folate: 165,
                calcium: 125,
                iron: 3.8,
                magnesium: 85,
                phosphorus: 165,
                potassium: 485,
                sodium: 585,
                zinc: 2.5,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 0
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Spiced chickpeas in tangy tomato-based curry",
            nameFr: "Chole",
            nameEs: "Chole",
            nameHe: "צ'ולה",
            notesFr: "Pois chiches épicés dans un curry acidulé à base de tomate",
            notesEs: "Garbanzos especiados en curry ácido a base de tomate",
            notesHe: "חומוס מתובל בקארי חמצמץ על בסיס עגבניות"
        ),
        
        // Aloo Gobi
        FoodItem(
            id: UUID(),
            name: "Aloo Gobi",
            category: .vegetables,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 145,
                protein: 4.2,
                carbohydrates: 22,
                fat: 5.8,
                fiber: 4.8,
                sugar: 6.2,
                vitaminA: 25,
                vitaminC: 85,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 18,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 1.8,
                vitaminB6: 0.28,
                vitaminB12: 0,
                folate: 65,
                calcium: 45,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 85,
                potassium: 485,
                sodium: 385,
                zinc: 1.2,
                selenium: 2.8,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 160,
            servingUnit: "g",
            isCustom: true,
            notes: "Dry curry of potatoes and cauliflower with turmeric and spices",
            nameFr: "Aloo Gobi",
            nameEs: "Aloo Gobi",
            nameHe: "אלו גובי",
            notesFr: "Curry sec de pommes de terre et chou-fleur avec curcuma et épices",
            notesEs: "Curry seco de papas y coliflor con cúrcuma y especias",
            notesHe: "קארי יבש של תפוחי אדמה וכרובית עם כורכום ותבלינים"
        ),
        
        // Masala Dosa
        FoodItem(
            id: UUID(),
            name: "Masala Dosa",
            category: .grains,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 8.5,
                carbohydrates: 48,
                fat: 6.8,
                fiber: 3.8,
                sugar: 4.2,
                vitaminA: 65,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 8,
                thiamin: 0.28,
                riboflavin: 0.15,
                niacin: 3.2,
                vitaminB6: 0.22,
                vitaminB12: 0.8,
                folate: 125,
                calcium: 85,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 145,
                potassium: 285,
                sodium: 485,
                zinc: 1.8,
                selenium: 12.5,
                omega3: 0.2,
                omega6: 2.2,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy fermented crepe filled with spiced potato curry",
            nameFr: "Masala Dosa",
            nameEs: "Masala Dosa",
            nameHe: "מסאלה דוסה",
            notesFr: "Crêpe fermentée croustillante farcie de curry de pommes de terre épicé",
            notesEs: "Crepe fermentada crujiente rellena de curry de papa especiado",
            notesHe: "קרפ מותסס פריך ממולא קארי תפוחי אדמה מתובל"
        ),
        
        // Rogan Josh
        FoodItem(
            id: UUID(),
            name: "Rogan Josh",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 315,
                protein: 26.8,
                carbohydrates: 8,
                fat: 20.5,
                fiber: 2.2,
                sugar: 5.8,
                vitaminA: 125,
                vitaminC: 12,
                vitaminD: 0.2,
                vitaminE: 2.2,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.25,
                niacin: 7.8,
                vitaminB6: 0.45,
                vitaminB12: 3.2,
                folate: 22,
                calcium: 85,
                iron: 3.2,
                magnesium: 42,
                phosphorus: 225,
                potassium: 385,
                sodium: 585,
                zinc: 4.8,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Aromatic lamb curry with yogurt and Kashmiri spices",
            nameFr: "Rogan Josh",
            nameEs: "Rogan Josh",
            nameHe: "רוגן ג'וש",
            notesFr: "Curry d'agneau aromatique avec yaourt et épices du Cachemire",
            notesEs: "Curry aromático de cordero con yogur y especias de Cachemira",
            notesHe: "קארי כבש ארומטי עם יוגורט ותבלינים קשמיריים"
        ),
        
        // Idli
        FoodItem(
            id: UUID(),
            name: "Idli",
            category: .grains,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 6.2,
                carbohydrates: 32,
                fat: 1.8,
                fiber: 2.8,
                sugar: 2.2,
                vitaminA: 8,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 2,
                thiamin: 0.22,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.15,
                vitaminB12: 0.5,
                folate: 85,
                calcium: 65,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 125,
                potassium: 185,
                sodium: 285,
                zinc: 1.2,
                selenium: 8.5,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Steamed rice and lentil cakes, light and fluffy",
            nameFr: "Idli",
            nameEs: "Idli",
            nameHe: "אידלי",
            notesFr: "Gâteaux de riz et lentilles cuits à la vapeur, légers et moelleux",
            notesEs: "Pasteles de arroz y lentejas al vapor, ligeros y esponjosos",
            notesHe: "עוגות אורז ועדשים מאודות, קלות ואוורירות"
        ),
        
        // Vindaloo
        FoodItem(
            id: UUID(),
            name: "Pork Vindaloo",
            category: .protein,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 24.5,
                carbohydrates: 12,
                fat: 16.8,
                fiber: 2.8,
                sugar: 8.2,
                vitaminA: 85,
                vitaminC: 25,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 8,
                thiamin: 0.45,
                riboflavin: 0.28,
                niacin: 6.8,
                vitaminB6: 0.48,
                vitaminB12: 2.8,
                folate: 18,
                calcium: 65,
                iron: 2.8,
                magnesium: 35,
                phosphorus: 225,
                potassium: 385,
                sodium: 685,
                zinc: 3.8,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 75
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Spicy and tangy Goan curry with vinegar and red chilies",
            nameFr: "Vindaloo de Porc",
            nameEs: "Vindaloo de Cerdo",
            nameHe: "וינדלו חזיר",
            notesFr: "Curry épicé et acidulé de Goa avec vinaigre et piments rouges",
            notesEs: "Curry picante y ácido de Goa con vinagre y chiles rojos",
            notesHe: "קארי חריף וחמצמץ גואני עם חומץ וצ'ילי אדום"
        ),
        
        // Matar Paneer
        FoodItem(
            id: UUID(),
            name: "Matar Paneer",
            category: .vegetables,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 12.8,
                carbohydrates: 15,
                fat: 14.2,
                fiber: 4.8,
                sugar: 8.5,
                vitaminA: 125,
                vitaminC: 35,
                vitaminD: 0.2,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.15,
                riboflavin: 0.28,
                niacin: 2.2,
                vitaminB6: 0.22,
                vitaminB12: 0.8,
                folate: 85,
                calcium: 245,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 165,
                potassium: 485,
                sodium: 485,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 25
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Green peas and cottage cheese in spiced tomato gravy",
            nameFr: "Matar Paneer",
            nameEs: "Matar Paneer",
            nameHe: "מטאר פאניר",
            notesFr: "Petits pois et fromage cottage dans une sauce tomate épicée",
            notesEs: "Guisantes y queso cottage en salsa de tomate especiada",
            notesHe: "אפונה וגבינת קוטג' ברוטב עגבניות מתובל"
        ),
        
        // Lassi
        FoodItem(
            id: UUID(),
            name: "Mango Lassi",
            category: .beverages,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 5.8,
                carbohydrates: 28,
                fat: 3.5,
                fiber: 1.2,
                sugar: 25.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 2,
                thiamin: 0.08,
                riboflavin: 0.25,
                niacin: 0.8,
                vitaminB6: 0.15,
                vitaminB12: 0.8,
                folate: 22,
                calcium: 185,
                iron: 0.5,
                magnesium: 35,
                phosphorus: 145,
                potassium: 285,
                sodium: 85,
                zinc: 0.8,
                selenium: 5.8,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 15
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Refreshing yogurt-based drink blended with sweet mango",
            nameFr: "Lassi à la Mangue",
            nameEs: "Lassi de Mango",
            nameHe: "לאסי מנגו",
            notesFr: "Boisson rafraîchissante à base de yaourt mélangée avec de la mangue sucrée",
            notesEs: "Bebida refrescante a base de yogur mezclada con mango dulce",
            notesHe: "משקה מרענן על בסיס יוגורט מעורב עם מנגו מתוק"
        ),
        
        // Korma
        FoodItem(
            id: UUID(),
            name: "Vegetable Korma",
            category: .vegetables,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.8,
                carbohydrates: 18,
                fat: 10.5,
                fiber: 5.2,
                sugar: 8.8,
                vitaminA: 285,
                vitaminC: 45,
                vitaminD: 0.2,
                vitaminE: 2.8,
                vitaminK: 35,
                thiamin: 0.15,
                riboflavin: 0.18,
                niacin: 2.2,
                vitaminB6: 0.32,
                vitaminB12: 0.3,
                folate: 85,
                calcium: 125,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 125,
                potassium: 485,
                sodium: 485,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 12
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Mixed vegetables in rich cashew and coconut cream sauce",
            nameFr: "Korma de Légumes",
            nameEs: "Korma de Verduras",
            nameHe: "קורמה ירקות",
            notesFr: "Légumes mélangés dans une sauce riche à la crème de noix de cajou et de coco",
            notesEs: "Verduras mixtas en salsa rica de crema de anacardo y coco",
            notesHe: "ירקות מעורבים ברוטב עשיר של קשיו וקרם קוקוס"
        ),
        
        // Gulab Jamun
        FoodItem(
            id: UUID(),
            name: "Gulab Jamun",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 5.2,
                carbohydrates: 42,
                fat: 11.5,
                fiber: 0.8,
                sugar: 38.5,
                vitaminA: 85,
                vitaminC: 2,
                vitaminD: 0.5,
                vitaminE: 0.8,
                vitaminK: 2,
                thiamin: 0.05,
                riboflavin: 0.18,
                niacin: 0.8,
                vitaminB6: 0.05,
                vitaminB12: 0.5,
                folate: 12,
                calcium: 145,
                iron: 0.8,
                magnesium: 18,
                phosphorus: 125,
                potassium: 145,
                sodium: 85,
                zinc: 0.8,
                selenium: 5.2,
                omega3: 0.1,
                omega6: 1.2,
                cholesterol: 25
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Sweet milk dumplings soaked in rose-flavored sugar syrup",
            nameFr: "Gulab Jamun",
            nameEs: "Gulab Jamun",
            nameHe: "גולאב ג'מון",
            notesFr: "Boulettes de lait sucrées trempées dans un sirop de sucre parfumé à la rose",
            notesEs: "Albóndigas dulces de leche empapadas en jarabe de azúcar con sabor a rosa",
            notesHe: "כדורי חלב מתוקים ספוגים בסירופ סוכר בטעם ורד"
        ),
        
        // Chai
        FoodItem(
            id: UUID(),
            name: "Masala Chai",
            category: .beverages,
            cuisineType: .indian,
            nutritionalInfo: NutritionalInfo(
                calories: 85,
                protein: 2.8,
                carbohydrates: 12,
                fat: 2.5,
                fiber: 0.2,
                sugar: 10.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0.2,
                vitaminE: 0.2,
                vitaminK: 1,
                thiamin: 0.05,
                riboflavin: 0.12,
                niacin: 0.2,
                vitaminB6: 0.02,
                vitaminB12: 0.3,
                folate: 5,
                calcium: 85,
                iron: 0.5,
                magnesium: 18,
                phosphorus: 65,
                potassium: 125,
                sodium: 45,
                zinc: 0.3,
                selenium: 2.8,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 8
            ),
            servingSize: 200,
            servingUnit: "ml",
            isCustom: true,
            notes: "Spiced tea with milk, cardamom, ginger, and cinnamon",
            nameFr: "Chai Masala",
            nameEs: "Chai Masala",
            nameHe: "צ'אי מסאלה",
            notesFr: "Thé épicé avec du lait, de la cardamome, du gingembre et de la cannelle",
            notesEs: "Té especiado con leche, cardamomo, jengibre y canela",
            notesHe: "תה מתובל עם חלב, הל, זנגביל וקינמון"
        )
    ]
}
