import Foundation

struct ItalianCuisineItems {
    static let foods: [FoodItem] = [
        // Spaghetti Carbonara
        FoodItem(
            id: UUID(),
            name: "Spaghetti Carbonara",
            category: .grains,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 18.5,
                carbohydrates: 42,
                fat: 16.8,
                fiber: 2.8,
                sugar: 2.1,
                vitaminA: 180,
                vitaminC: 2,
                vitaminD: 0.8,
                vitaminE: 1.2,
                vitaminK: 3.5,
                thiamin: 0.3,
                riboflavin: 0.4,
                niacin: 4.2,
                vitaminB6: 0.3,
                vitaminB12: 0.6,
                folate: 45,
                calcium: 85,
                iron: 2.8,
                magnesium: 55,
                phosphorus: 220,
                potassium: 280,
                sodium: 680,
                zinc: 2.1,
                selenium: 18,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 125
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional Roman pasta with eggs, pancetta, and Pecorino Romano cheese",
            nameFr: "Spaghetti à la Carbonara",
            nameEs: "Espaguetis a la Carbonara",
            nameHe: "ספגטי קרבונרה",
            notesFr: "Pâtes romaines traditionnelles aux œufs, pancetta et Pecorino Romano",
            notesEs: "Pasta romana tradicional con huevos, panceta y queso Pecorino Romano",
            notesHe: "פסטה רומית מסורתית עם ביצים, פנצ'טה וגבינת פקורינו רומנו"
        ),
        
        // Risotto alla Milanese
        FoodItem(
            id: UUID(),
            name: "Risotto alla Milanese",
            category: .grains,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 320,
                protein: 12.5,
                carbohydrates: 48,
                fat: 9.8,
                fiber: 1.8,
                sugar: 2.5,
                vitaminA: 220,
                vitaminC: 5,
                vitaminD: 0.3,
                vitaminE: 0.8,
                vitaminK: 2.1,
                thiamin: 0.2,
                riboflavin: 0.3,
                niacin: 3.5,
                vitaminB6: 0.2,
                vitaminB12: 0.4,
                folate: 35,
                calcium: 150,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 180,
                potassium: 220,
                sodium: 580,
                zinc: 1.5,
                selenium: 12,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 25
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Creamy saffron risotto from Milan with Arborio rice and Parmigiano-Reggiano",
            nameFr: "Risotto à la Milanaise",
            nameEs: "Risotto a la Milanesa",
            nameHe: "ריזוטו מילנזה",
            notesFr: "Risotto crémeux au safran de Milan avec riz Arborio et Parmigiano-Reggiano",
            notesEs: "Risotto cremoso con azafrán de Milán con arroz Arborio y Parmigiano-Reggiano",
            notesHe: "ריזוטו קרמי עם זעפרן ממילאנו עם אורז ארבוריו ופרמיג'אנו רג'אנו"
        ),
        
        // Osso Buco
        FoodItem(
            id: UUID(),
            name: "Osso Buco alla Milanese",
            category: .protein,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 28.5,
                carbohydrates: 8.2,
                fat: 15.8,
                fiber: 2.1,
                sugar: 4.5,
                vitaminA: 850,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 12,
                thiamin: 0.2,
                riboflavin: 0.4,
                niacin: 6.8,
                vitaminB6: 0.5,
                vitaminB12: 2.8,
                folate: 25,
                calcium: 45,
                iron: 4.2,
                magnesium: 35,
                phosphorus: 280,
                potassium: 520,
                sodium: 720,
                zinc: 5.2,
                selenium: 25,
                omega3: 0.3,
                omega6: 1.2,
                cholesterol: 95
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Braised veal shanks with vegetables, white wine, and gremolata",
            nameFr: "Osso Buco à la Milanaise",
            nameEs: "Osso Buco a la Milanesa",
            nameHe: "אוסו בוקו מילנזה",
            notesFr: "Jarrets de veau braisés aux légumes, vin blanc et gremolata",
            notesEs: "Jarrete de ternera estofado con verduras, vino blanco y gremolata",
            notesHe: "שוק עגל מבושל עם ירקות, יין לבן וגרמולטה"
        ),
        
        // Chicken Parmigiana
        FoodItem(
            id: UUID(),
            name: "Chicken Parmigiana",
            category: .protein,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 420,
                protein: 32.5,
                carbohydrates: 18.5,
                fat: 24.8,
                fiber: 2.8,
                sugar: 8.2,
                vitaminA: 680,
                vitaminC: 15,
                vitaminD: 0.2,
                vitaminE: 2.5,
                vitaminK: 8.5,
                thiamin: 0.2,
                riboflavin: 0.3,
                niacin: 12.5,
                vitaminB6: 0.8,
                vitaminB12: 0.4,
                folate: 35,
                calcium: 285,
                iron: 2.8,
                magnesium: 45,
                phosphorus: 320,
                potassium: 480,
                sodium: 950,
                zinc: 2.5,
                selenium: 28,
                omega3: 0.2,
                omega6: 2.8,
                cholesterol: 95
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Breaded chicken breast with marinara sauce and melted mozzarella",
            nameFr: "Poulet Parmigiana",
            nameEs: "Pollo a la Parmesana",
            nameHe: "עוף פרמיג'אנה",
            notesFr: "Blanc de poulet pané avec sauce marinara et mozzarella fondue",
            notesEs: "Pechuga de pollo empanizada con salsa marinara y mozzarella derretida",
            notesHe: "חזה עוף פרוס עם רוטב מרינרה ומוצרלה מומסת"
        ),
        
        // Minestrone Soup
        FoodItem(
            id: UUID(),
            name: "Minestrone Soup",
            category: .vegetables,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 145,
                protein: 6.8,
                carbohydrates: 22,
                fat: 4.2,
                fiber: 5.8,
                sugar: 6.5,
                vitaminA: 1250,
                vitaminC: 28,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 45,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.8,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 65,
                calcium: 85,
                iron: 2.5,
                magnesium: 55,
                phosphorus: 120,
                potassium: 480,
                sodium: 620,
                zinc: 1.2,
                selenium: 8,
                omega3: 0.3,
                omega6: 1.1,
                cholesterol: 0
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional Italian vegetable soup with beans, pasta, and herbs",
            nameFr: "Soupe Minestrone",
            nameEs: "Sopa Minestrone",
            nameHe: "מרק מינסטרונה",
            notesFr: "Soupe italienne traditionnelle aux légumes, haricots, pâtes et herbes",
            notesEs: "Sopa italiana tradicional con verduras, frijoles, pasta y hierbas",
            notesHe: "מרק ירקות איטלקי מסורתי עם שעועיות, פסטה ועשבי תיבול"
        ),
        
        // Eggplant Parmigiana
        FoodItem(
            id: UUID(),
            name: "Eggplant Parmigiana",
            category: .vegetables,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 14.5,
                carbohydrates: 22,
                fat: 18.2,
                fiber: 6.8,
                sugar: 12.5,
                vitaminA: 420,
                vitaminC: 8,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 15,
                thiamin: 0.1,
                riboflavin: 0.3,
                niacin: 2.1,
                vitaminB6: 0.2,
                vitaminB12: 0.2,
                folate: 35,
                calcium: 320,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 220,
                potassium: 380,
                sodium: 780,
                zinc: 1.8,
                selenium: 12,
                omega3: 0.2,
                omega6: 2.1,
                cholesterol: 35
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Layers of breaded eggplant with marinara sauce and melted cheese",
            nameFr: "Aubergines à la Parmigiana",
            nameEs: "Berenjenas a la Parmesana",
            nameHe: "חציל פרמיג'אנה",
            notesFr: "Couches d'aubergines panées avec sauce marinara et fromage fondu",
            notesEs: "Capas de berenjena empanizada con salsa marinara y queso derretido",
            notesHe: "שכבות חציל פרוס עם רוטב מרינרה וגבינה מומסת"
        ),
        
        // Gnocchi with Sage Butter
        FoodItem(
            id: UUID(),
            name: "Gnocchi with Sage Butter",
            category: .grains,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 315,
                protein: 8.5,
                carbohydrates: 48,
                fat: 11.2,
                fiber: 2.1,
                sugar: 1.8,
                vitaminA: 280,
                vitaminC: 12,
                vitaminD: 0.2,
                vitaminE: 1.5,
                vitaminK: 8.5,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.2,
                vitaminB6: 0.4,
                vitaminB12: 0.1,
                folate: 45,
                calcium: 85,
                iron: 2.1,
                magnesium: 35,
                phosphorus: 150,
                potassium: 280,
                sodium: 520,
                zinc: 1.2,
                selenium: 15,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 45
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Potato dumplings with brown butter and fresh sage leaves",
            nameFr: "Gnocchis au Beurre de Sauge",
            nameEs: "Ñoquis con Mantequilla de Salvia",
            nameHe: "ניוקי עם חמאת מרווה",
            notesFr: "Boulettes de pommes de terre au beurre noisette et feuilles de sauge fraîches",
            notesEs: "Dumplings de papa con mantequilla dorada y hojas de salvia frescas",
            notesHe: "כופתאות תפוחי אדמה עם חמאה חומה ועלי מרווה טריים"
        ),
        
        // Lasagna Bolognese
        FoodItem(
            id: UUID(),
            name: "Lasagna Bolognese",
            category: .grains,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 22.5,
                carbohydrates: 28,
                fat: 21.8,
                fiber: 2.8,
                sugar: 6.2,
                vitaminA: 680,
                vitaminC: 12,
                vitaminD: 0.5,
                vitaminE: 2.1,
                vitaminK: 12,
                thiamin: 0.2,
                riboflavin: 0.4,
                niacin: 5.2,
                vitaminB6: 0.4,
                vitaminB12: 1.2,
                folate: 45,
                calcium: 285,
                iron: 3.2,
                magnesium: 45,
                phosphorus: 280,
                potassium: 420,
                sodium: 850,
                zinc: 3.2,
                selenium: 22,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 85
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Layered pasta with meat sauce, béchamel, and melted cheese",
            nameFr: "Lasagnes Bolognaise",
            nameEs: "Lasaña Boloñesa",
            nameHe: "לזניה בולונז",
            notesFr: "Pâtes en couches avec sauce à la viande, béchamel et fromage fondu",
            notesEs: "Pasta en capas con salsa de carne, bechamel y queso derretido",
            notesHe: "פסטה בשכבות עם רוטב בשר, בשמל וגבינה מומסת"
        ),
        
        // Caprese Salad
        FoodItem(
            id: UUID(),
            name: "Caprese Salad",
            category: .vegetables,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 12.5,
                carbohydrates: 8.2,
                fat: 12.8,
                fiber: 2.1,
                sugar: 6.5,
                vitaminA: 850,
                vitaminC: 28,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 45,
                thiamin: 0.1,
                riboflavin: 0.3,
                niacin: 1.2,
                vitaminB6: 0.2,
                vitaminB12: 0.4,
                folate: 25,
                calcium: 220,
                iron: 1.2,
                magnesium: 25,
                phosphorus: 180,
                potassium: 320,
                sodium: 420,
                zinc: 1.5,
                selenium: 8,
                omega3: 0.4,
                omega6: 1.2,
                cholesterol: 25
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Fresh mozzarella, tomatoes, and basil with olive oil and balsamic",
            nameFr: "Salade Caprese",
            nameEs: "Ensalada Caprese",
            nameHe: "סלט קפרזה",
            notesFr: "Mozzarella fraîche, tomates et basilic à l'huile d'olive et vinaigre balsamique",
            notesEs: "Mozzarella fresca, tomates y albahaca con aceite de oliva y balsámico",
            notesHe: "מוצרלה טרייה, עגבניות ובזיליקום עם שמן זית ובלסמי"
        ),
        
        // Veal Marsala
        FoodItem(
            id: UUID(),
            name: "Veal Marsala",
            category: .protein,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 28.5,
                carbohydrates: 6.8,
                fat: 18.2,
                fiber: 1.2,
                sugar: 3.5,
                vitaminA: 120,
                vitaminC: 8,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 5.2,
                thiamin: 0.3,
                riboflavin: 0.4,
                niacin: 8.5,
                vitaminB6: 0.6,
                vitaminB12: 2.1,
                folate: 18,
                calcium: 25,
                iron: 3.8,
                magnesium: 35,
                phosphorus: 250,
                potassium: 420,
                sodium: 580,
                zinc: 4.2,
                selenium: 22,
                omega3: 0.2,
                omega6: 1.5,
                cholesterol: 95
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Tender veal cutlets in Marsala wine sauce with mushrooms",
            nameFr: "Veau au Marsala",
            nameEs: "Ternera al Marsala",
            nameHe: "עגל מרסלה",
            notesFr: "Escalopes de veau tendres dans une sauce au vin de Marsala avec champignons",
            notesEs: "Chuletas de ternera tiernas en salsa de vino Marsala con champiñones",
            notesHe: "קציצות עגל רכות ברוטב יין מרסלה עם פטריות"
        ),
        
        // Bruschetta
        FoodItem(
            id: UUID(),
            name: "Bruschetta al Pomodoro",
            category: .snacks,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 5.2,
                carbohydrates: 22,
                fat: 6.8,
                fiber: 3.2,
                sugar: 4.5,
                vitaminA: 680,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 2.1,
                vitaminK: 25,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.5,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 35,
                calcium: 45,
                iron: 1.8,
                magnesium: 25,
                phosphorus: 85,
                potassium: 280,
                sodium: 380,
                zinc: 0.8,
                selenium: 12,
                omega3: 0.3,
                omega6: 1.1,
                cholesterol: 0
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled bread topped with fresh tomatoes, garlic, and basil",
            nameFr: "Bruschetta aux Tomates",
            nameEs: "Bruschetta de Tomate",
            nameHe: "ברושטה עגבניות",
            notesFr: "Pain grillé garni de tomates fraîches, ail et basilic",
            notesEs: "Pan tostado cubierto con tomates frescos, ajo y albahaca",
            notesHe: "לחם קלוי עם עגבניות טריות, שום ובזיליקום"
        ),
        
        // Tiramisu
        FoodItem(
            id: UUID(),
            name: "Tiramisu",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 6.8,
                carbohydrates: 28,
                fat: 16.5,
                fiber: 1.2,
                sugar: 22,
                vitaminA: 180,
                vitaminC: 1,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 1.8,
                thiamin: 0.1,
                riboflavin: 0.3,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0.4,
                folate: 15,
                calcium: 120,
                iron: 1.2,
                magnesium: 25,
                phosphorus: 140,
                potassium: 180,
                sodium: 85,
                zinc: 0.8,
                selenium: 8,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 125
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Classic Italian dessert with mascarpone, coffee, and cocoa",
            nameFr: "Tiramisu",
            nameEs: "Tiramisú",
            nameHe: "טירמיסו",
            notesFr: "Dessert italien classique au mascarpone, café et cacao",
            notesEs: "Postre italiano clásico con mascarpone, café y cacao",
            notesHe: "קינוח איטלקי קלאסי עם מסקרפונה, קפה וקקאו"
        ),
        
        // Prosciutto e Melone
        FoodItem(
            id: UUID(),
            name: "Prosciutto e Melone",
            category: .protein,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 145,
                protein: 12.5,
                carbohydrates: 8.5,
                fat: 7.8,
                fiber: 0.8,
                sugar: 8.2,
                vitaminA: 320,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 2.1,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.5,
                vitaminB6: 0.2,
                vitaminB12: 0.8,
                folate: 25,
                calcium: 12,
                iron: 1.2,
                magnesium: 18,
                phosphorus: 120,
                potassium: 380,
                sodium: 720,
                zinc: 1.8,
                selenium: 15,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 25
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Thinly sliced prosciutto with fresh cantaloupe melon",
            nameFr: "Prosciutto et Melon",
            nameEs: "Prosciutto y Melón",
            nameHe: "פרושוטו ומלון",
            notesFr: "Prosciutto finement tranché avec melon cantaloup frais",
            notesEs: "Prosciutto finamente rebanado con melón cantalupo fresco",
            notesHe: "פרושוטו פרוס דק עם מלון קנטלופ טרי"
        ),
        
        // Polenta
        FoodItem(
            id: UUID(),
            name: "Polenta with Mushrooms",
            category: .grains,
            cuisineType: .italian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.2,
                carbohydrates: 32,
                fat: 4.8,
                fiber: 2.8,
                sugar: 2.1,
                vitaminA: 180,
                vitaminC: 8,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 5.2,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 2.8,
                vitaminB6: 0.3,
                vitaminB12: 0.2,
                folate: 25,
                calcium: 65,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 120,
                potassium: 280,
                sodium: 420,
                zinc: 1.2,
                selenium: 12,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 15
            ),
            servingSize: 160,
            servingUnit: "g",
            isCustom: true,
            notes: "Creamy cornmeal porridge topped with sautéed mushrooms and Parmesan",
            nameFr: "Polenta aux Champignons",
            nameEs: "Polenta con Champiñones",
            nameHe: "פולנטה עם פטריות",
            notesFr: "Bouillie de semoule de maïs crémeuse garnie de champignons sautés et Parmesan",
            notesEs: "Papilla cremosa de harina de maíz cubierta con champiñones salteados y parmesano",
            notesHe: "דייסת קמח תירס קרמית עם פטריות מוקפצות ופרמזן"
        )
    ]
} 