import Foundation

struct JapaneseCuisineFoodItems {
    static let foods: [FoodItem] = [
        // Sushi - Salmon Nigiri
        FoodItem(
            id: UUID(),
            name: "Salmon Nigiri",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 18.5,
                carbohydrates: 15,
                fat: 4.8,
                fiber: 0.8,
                sugar: 3.2,
                vitaminA: 45,
                vitaminC: 2,
                vitaminD: 12.5,
                vitaminE: 1.8,
                vitaminK: 2,
                thiamin: 0.15,
                riboflavin: 0.18,
                niacin: 8.2,
                vitaminB6: 0.52,
                vitaminB12: 4.8,
                folate: 18,
                calcium: 25,
                iron: 0.8,
                magnesium: 35,
                phosphorus: 285,
                potassium: 385,
                sodium: 485,
                zinc: 1.8,
                selenium: 35.5,
                omega3: 1.8,
                omega6: 0.5,
                cholesterol: 45
            ),
            servingSize: 40,
            servingUnit: "g",
            isCustom: true,
            notes: "Fresh salmon over seasoned sushi rice",
            nameFr: "Nigiri au Saumon",
            nameEs: "Nigiri de Salmón",
            nameHe: "ניגירי סלמון",
            notesFr: "Saumon frais sur riz à sushi assaisonné",
            notesEs: "Salmón fresco sobre arroz de sushi sazonado",
            notesHe: "סלמון טרי על אורז סושי מתובל"
        ),
        
        // Ramen
        FoodItem(
            id: UUID(),
            name: "Tonkotsu Ramen",
            category: .grains,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 485,
                protein: 24.5,
                carbohydrates: 52,
                fat: 18.8,
                fiber: 4.2,
                sugar: 6.8,
                vitaminA: 125,
                vitaminC: 15,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 35,
                thiamin: 0.35,
                riboflavin: 0.28,
                niacin: 8.8,
                vitaminB6: 0.45,
                vitaminB12: 2.8,
                folate: 85,
                calcium: 125,
                iron: 3.8,
                magnesium: 85,
                phosphorus: 285,
                potassium: 585,
                sodium: 1285,
                zinc: 4.2,
                selenium: 22.5,
                omega3: 0.5,
                omega6: 3.8,
                cholesterol: 65
            ),
            servingSize: 350,
            servingUnit: "ml",
            isCustom: true,
            notes: "Rich pork bone broth with wheat noodles, chashu pork, and soft-boiled egg",
            nameFr: "Ramen Tonkotsu",
            nameEs: "Ramen Tonkotsu",
            nameHe: "ראמן טונקוצו",
            notesFr: "Bouillon riche d'os de porc avec nouilles de blé, porc chashu et œuf mollet",
            notesEs: "Caldo rico de hueso de cerdo con fideos de trigo, cerdo chashu y huevo pasado",
            notesHe: "מרק עשיר מעצמות חזיר עם אטריות חיטה, חזיר צ'אשו וביצה רכה"
        ),
        
        // Tempura
        FoodItem(
            id: UUID(),
            name: "Shrimp Tempura",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 16.8,
                carbohydrates: 22,
                fat: 14.5,
                fiber: 1.8,
                sugar: 2.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.5,
                vitaminE: 3.8,
                vitaminK: 8,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 3.8,
                vitaminB6: 0.22,
                vitaminB12: 1.8,
                folate: 25,
                calcium: 85,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 185,
                potassium: 285,
                sodium: 485,
                zinc: 2.2,
                selenium: 28.5,
                omega3: 0.8,
                omega6: 4.2,
                cholesterol: 125
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Lightly battered and fried shrimp with crispy coating",
            nameFr: "Tempura de Crevettes",
            nameEs: "Tempura de Camarones",
            nameHe: "טמפורה שרימפס",
            notesFr: "Crevettes légèrement panées et frites avec enrobage croustillant",
            notesEs: "Camarones ligeramente empanizados y fritos con cobertura crujiente",
            notesHe: "שרימפס בציפוי קל ומטוגן עם ציפוי פריך"
        ),
        
        // Teriyaki Chicken
        FoodItem(
            id: UUID(),
            name: "Chicken Teriyaki",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 28.5,
                carbohydrates: 18,
                fat: 16.8,
                fiber: 1.2,
                sugar: 15.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0.5,
                vitaminE: 1.8,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 12.5,
                vitaminB6: 0.65,
                vitaminB12: 2.8,
                folate: 22,
                calcium: 45,
                iron: 2.2,
                magnesium: 42,
                phosphorus: 245,
                potassium: 385,
                sodium: 785,
                zinc: 3.8,
                selenium: 28.5,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled chicken glazed with sweet soy-based teriyaki sauce",
            nameFr: "Poulet Teriyaki",
            nameEs: "Pollo Teriyaki",
            nameHe: "עוף טריאקי",
            notesFr: "Poulet grillé glacé avec sauce teriyaki sucrée à base de soja",
            notesEs: "Pollo a la parrilla glaseado con salsa teriyaki dulce a base de soja",
            notesHe: "עוף צלוי מצופה ברוטב טריאקי מתוק על בסיס סויה"
        ),
        
        // Miso Soup
        FoodItem(
            id: UUID(),
            name: "Miso Soup",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 85,
                protein: 6.8,
                carbohydrates: 8,
                fat: 2.8,
                fiber: 2.2,
                sugar: 3.5,
                vitaminA: 45,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 12,
                thiamin: 0.08,
                riboflavin: 0.12,
                niacin: 1.8,
                vitaminB6: 0.15,
                vitaminB12: 0.8,
                folate: 25,
                calcium: 125,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 85,
                potassium: 285,
                sodium: 685,
                zinc: 1.2,
                selenium: 8.5,
                omega3: 0.2,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional soybean paste soup with tofu, seaweed, and scallions",
            nameFr: "Soupe Miso",
            nameEs: "Sopa Miso",
            nameHe: "מרק מיסו",
            notesFr: "Soupe traditionnelle de pâte de soja avec tofu, algues et oignons verts",
            notesEs: "Sopa tradicional de pasta de soja con tofu, algas y cebolletas",
            notesHe: "מרק מסורתי ממשחת סויה עם טופו, אצות ובצל ירוק"
        ),
        
        // California Roll
        FoodItem(
            id: UUID(),
            name: "California Roll",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 12.5,
                carbohydrates: 28,
                fat: 8.8,
                fiber: 2.8,
                sugar: 4.5,
                vitaminA: 185,
                vitaminC: 8,
                vitaminD: 0.3,
                vitaminE: 2.2,
                vitaminK: 15,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 3.8,
                vitaminB6: 0.25,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 85,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 145,
                potassium: 285,
                sodium: 585,
                zinc: 2.2,
                selenium: 18.5,
                omega3: 0.8,
                omega6: 2.2,
                cholesterol: 35
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Inside-out sushi roll with crab, avocado, and cucumber",
            nameFr: "Rouleau California",
            nameEs: "Rollo California",
            nameHe: "רול קליפורניה",
            notesFr: "Rouleau de sushi inversé avec crabe, avocat et concombre",
            notesEs: "Rollo de sushi invertido con cangrejo, aguacate y pepino",
            notesHe: "רול סושי הפוך עם סרטן, אבוקדו ומלפפון"
        ),
        
        // Yakitori
        FoodItem(
            id: UUID(),
            name: "Yakitori",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 22.5,
                carbohydrates: 8,
                fat: 7.8,
                fiber: 0.5,
                sugar: 6.5,
                vitaminA: 45,
                vitaminC: 5,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 5,
                thiamin: 0.12,
                riboflavin: 0.18,
                niacin: 9.8,
                vitaminB6: 0.52,
                vitaminB12: 2.2,
                folate: 18,
                calcium: 25,
                iron: 1.8,
                magnesium: 28,
                phosphorus: 185,
                potassium: 285,
                sodium: 485,
                zinc: 2.8,
                selenium: 22.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 75
            ),
            servingSize: 80,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled chicken skewers with sweet tare sauce",
            nameFr: "Yakitori",
            nameEs: "Yakitori",
            nameHe: "יאקיטורי",
            notesFr: "Brochettes de poulet grillées avec sauce tare sucrée",
            notesEs: "Brochetas de pollo a la parrilla con salsa tare dulce",
            notesHe: "שיפודי עוף צלויים ברוטב טארה מתוק"
        ),
        
        // Katsu Curry
        FoodItem(
            id: UUID(),
            name: "Chicken Katsu Curry",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 485,
                protein: 26.5,
                carbohydrates: 45,
                fat: 22.8,
                fiber: 3.8,
                sugar: 8.5,
                vitaminA: 125,
                vitaminC: 25,
                vitaminD: 0.5,
                vitaminE: 3.2,
                vitaminK: 12,
                thiamin: 0.25,
                riboflavin: 0.22,
                niacin: 11.8,
                vitaminB6: 0.58,
                vitaminB12: 2.5,
                folate: 35,
                calcium: 85,
                iron: 3.2,
                magnesium: 65,
                phosphorus: 285,
                potassium: 485,
                sodium: 885,
                zinc: 3.8,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 6.8,
                cholesterol: 85
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Breaded fried chicken cutlet with Japanese curry sauce over rice",
            nameFr: "Curry Katsu de Poulet",
            nameEs: "Curry Katsu de Pollo",
            nameHe: "קארי קאצו עוף",
            notesFr: "Escalope de poulet panée frite avec sauce curry japonaise sur riz",
            notesEs: "Chuleta de pollo empanizada frita con salsa de curry japonés sobre arroz",
            notesHe: "קציצת עוף מטוגנת בציפוי עם רוטב קארי יפני על אורז"
        ),
        
        // Sashimi
        FoodItem(
            id: UUID(),
            name: "Tuna Sashimi",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 145,
                protein: 25.8,
                carbohydrates: 0,
                fat: 3.8,
                fiber: 0,
                sugar: 0,
                vitaminA: 85,
                vitaminC: 2,
                vitaminD: 8.5,
                vitaminE: 1.2,
                vitaminK: 2,
                thiamin: 0.22,
                riboflavin: 0.28,
                niacin: 12.5,
                vitaminB6: 0.85,
                vitaminB12: 8.5,
                folate: 8,
                calcium: 15,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 285,
                potassium: 485,
                sodium: 45,
                zinc: 1.2,
                selenium: 85.5,
                omega3: 2.8,
                omega6: 0.3,
                cholesterol: 45
            ),
            servingSize: 80,
            servingUnit: "g",
            isCustom: true,
            notes: "Fresh raw tuna sliced thin, served without rice",
            nameFr: "Sashimi de Thon",
            nameEs: "Sashimi de Atún",
            nameHe: "סשימי טונה",
            notesFr: "Thon cru frais tranché finement, servi sans riz",
            notesEs: "Atún crudo fresco cortado fino, servido sin arroz",
            notesHe: "טונה גולמית טרייה פרוסה דק, מוגשת ללא אורז"
        ),
        
        // Udon
        FoodItem(
            id: UUID(),
            name: "Beef Udon",
            category: .grains,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 22.5,
                carbohydrates: 48,
                fat: 12.8,
                fiber: 3.2,
                sugar: 5.8,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 25,
                thiamin: 0.28,
                riboflavin: 0.25,
                niacin: 8.8,
                vitaminB6: 0.45,
                vitaminB12: 3.2,
                folate: 65,
                calcium: 85,
                iron: 3.8,
                magnesium: 65,
                phosphorus: 225,
                potassium: 485,
                sodium: 985,
                zinc: 4.2,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 65
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Thick wheat noodles in savory dashi broth with sliced beef",
            nameFr: "Udon au Bœuf",
            nameEs: "Udon de Carne",
            nameHe: "אודון בקר",
            notesFr: "Nouilles de blé épaisses dans un bouillon dashi savoureux avec bœuf tranché",
            notesEs: "Fideos de trigo gruesos en caldo dashi sabroso con carne en rodajas",
            notesHe: "אטריות חיטה עבות במרק דאשי טעים עם בקר פרוס"
        ),
        
        // Onigiri
        FoodItem(
            id: UUID(),
            name: "Salmon Onigiri",
            category: .grains,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 8.5,
                carbohydrates: 32,
                fat: 3.8,
                fiber: 1.2,
                sugar: 2.5,
                vitaminA: 45,
                vitaminC: 2,
                vitaminD: 3.2,
                vitaminE: 1.2,
                vitaminK: 5,
                thiamin: 0.18,
                riboflavin: 0.12,
                niacin: 4.8,
                vitaminB6: 0.25,
                vitaminB12: 1.8,
                folate: 25,
                calcium: 25,
                iron: 1.2,
                magnesium: 35,
                phosphorus: 125,
                potassium: 185,
                sodium: 485,
                zinc: 1.8,
                selenium: 18.5,
                omega3: 0.8,
                omega6: 0.5,
                cholesterol: 25
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Rice ball filled with salted salmon and wrapped in nori seaweed",
            nameFr: "Onigiri au Saumon",
            nameEs: "Onigiri de Salmón",
            nameHe: "אוניגירי סלמון",
            notesFr: "Boule de riz farcie au saumon salé et enveloppée dans algue nori",
            notesEs: "Bola de arroz rellena de salmón salado y envuelta en alga nori",
            notesHe: "כדור אורז ממולא סלמון מלוח ועטוף באצת נורי"
        ),
        
        // Gyoza
        FoodItem(
            id: UUID(),
            name: "Pork Gyoza",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 265,
                protein: 14.8,
                carbohydrates: 22,
                fat: 13.8,
                fiber: 2.2,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0.3,
                vitaminE: 1.8,
                vitaminK: 18,
                thiamin: 0.35,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.32,
                vitaminB12: 1.8,
                folate: 35,
                calcium: 65,
                iron: 2.8,
                magnesium: 45,
                phosphorus: 185,
                potassium: 285,
                sodium: 685,
                zinc: 2.8,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 4.2,
                cholesterol: 45
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Pan-fried pork dumplings with crispy bottom and tender filling",
            nameFr: "Gyoza au Porc",
            nameEs: "Gyoza de Cerdo",
            nameHe: "גיוזה חזיר",
            notesFr: "Raviolis de porc poêlés avec fond croustillant et garniture tendre",
            notesEs: "Dumplings de cerdo a la sartén con fondo crujiente y relleno tierno",
            notesHe: "כיסוני חזיר מטוגנים במחבת עם תחתית פריכה ומילוי רך"
        ),
        
        // Donburi
        FoodItem(
            id: UUID(),
            name: "Chicken Oyakodon",
            category: .grains,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 425,
                protein: 24.5,
                carbohydrates: 52,
                fat: 12.8,
                fiber: 2.2,
                sugar: 8.5,
                vitaminA: 285,
                vitaminC: 8,
                vitaminD: 2.8,
                vitaminE: 2.2,
                vitaminK: 15,
                thiamin: 0.25,
                riboflavin: 0.35,
                niacin: 9.8,
                vitaminB6: 0.48,
                vitaminB12: 3.2,
                folate: 85,
                calcium: 85,
                iron: 2.8,
                magnesium: 55,
                phosphorus: 285,
                potassium: 385,
                sodium: 785,
                zinc: 3.2,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 3.8,
                cholesterol: 285
            ),
            servingSize: 280,
            servingUnit: "g",
            isCustom: true,
            notes: "Chicken and egg bowl - simmered chicken and onions over rice with beaten egg",
            nameFr: "Oyakodon au Poulet",
            nameEs: "Oyakodon de Pollo",
            nameHe: "אויאקודון עוף",
            notesFr: "Bol de poulet et œuf - poulet et oignons mijotés sur riz avec œuf battu",
            notesEs: "Tazón de pollo y huevo - pollo y cebollas cocidos sobre arroz con huevo batido",
            notesHe: "קערת עוף וביצה - עוף ובצל מבושלים על אורז עם ביצה טרופה"
        ),
        
        // Takoyaki
        FoodItem(
            id: UUID(),
            name: "Takoyaki",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 12.5,
                carbohydrates: 28,
                fat: 8.8,
                fiber: 1.8,
                sugar: 4.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 8,
                thiamin: 0.15,
                riboflavin: 0.18,
                niacin: 3.8,
                vitaminB6: 0.22,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 125,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 185,
                potassium: 285,
                sodium: 585,
                zinc: 2.2,
                selenium: 18.5,
                omega3: 0.5,
                omega6: 2.8,
                cholesterol: 125
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Octopus balls - round batter balls with diced octopus, topped with sauce",
            nameFr: "Takoyaki",
            nameEs: "Takoyaki",
            nameHe: "טאקויאקי",
            notesFr: "Boules de poulpe - boules de pâte rondes avec poulpe en dés, nappées de sauce",
            notesEs: "Bolas de pulpo - bolas redondas de masa con pulpo en cubos, cubiertas con salsa",
            notesHe: "כדורי תמנון - כדורי בצק עגולים עם תמנון חתוך, מכוסים ברוטב"
        ),
        
        // Chirashi
        FoodItem(
            id: UUID(),
            name: "Chirashi Bowl",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 28.5,
                carbohydrates: 32,
                fat: 14.8,
                fiber: 2.8,
                sugar: 5.5,
                vitaminA: 185,
                vitaminC: 12,
                vitaminD: 8.5,
                vitaminE: 3.2,
                vitaminK: 15,
                thiamin: 0.22,
                riboflavin: 0.25,
                niacin: 9.8,
                vitaminB6: 0.65,
                vitaminB12: 6.8,
                folate: 45,
                calcium: 85,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 285,
                potassium: 485,
                sodium: 585,
                zinc: 2.8,
                selenium: 45.5,
                omega3: 2.2,
                omega6: 1.8,
                cholesterol: 85
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Scattered sushi bowl with assorted sashimi over seasoned rice",
            nameFr: "Bol Chirashi",
            nameEs: "Tazón Chirashi",
            nameHe: "קערת צ'יראשי",
            notesFr: "Bol de sushi dispersé avec sashimi assorti sur riz assaisonné",
            notesEs: "Tazón de sushi disperso con sashimi variado sobre arroz sazonado",
            notesHe: "קערת סושי מפוזרת עם סשימי מגוון על אורז מתובל"
        ),
        
        // Agedashi Tofu
        FoodItem(
            id: UUID(),
            name: "Agedashi Tofu",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 12.8,
                carbohydrates: 12,
                fat: 11.8,
                fiber: 2.2,
                sugar: 4.5,
                vitaminA: 45,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 12,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 1.8,
                vitaminB6: 0.15,
                vitaminB12: 0,
                folate: 35,
                calcium: 285,
                iron: 2.8,
                magnesium: 85,
                phosphorus: 185,
                potassium: 285,
                sodium: 485,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.5,
                omega6: 3.8,
                cholesterol: 0
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Lightly fried tofu in savory dashi broth with grated daikon",
            nameFr: "Tofu Agedashi",
            nameEs: "Tofu Agedashi",
            nameHe: "טופו אגדאשי",
            notesFr: "Tofu légèrement frit dans bouillon dashi savoureux avec daikon râpé",
            notesEs: "Tofu ligeramente frito en caldo dashi sabroso con daikon rallado",
            notesHe: "טופו מטוגן קלות במרק דאשי טעים עם דייקון מגורד"
        ),
        
        // Okonomiyaki
        FoodItem(
            id: UUID(),
            name: "Okonomiyaki",
            category: .grains,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 16.8,
                carbohydrates: 35,
                fat: 14.8,
                fiber: 4.2,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 1.2,
                vitaminE: 2.8,
                vitaminK: 85,
                thiamin: 0.22,
                riboflavin: 0.25,
                niacin: 4.8,
                vitaminB6: 0.35,
                vitaminB12: 2.2,
                folate: 85,
                calcium: 125,
                iron: 3.2,
                magnesium: 65,
                phosphorus: 185,
                potassium: 385,
                sodium: 785,
                zinc: 2.8,
                selenium: 18.5,
                omega3: 0.8,
                omega6: 4.8,
                cholesterol: 125
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Savory pancake with cabbage, meat, and seafood topped with sauce",
            nameFr: "Okonomiyaki",
            nameEs: "Okonomiyaki",
            nameHe: "אוקונומיאקי",
            notesFr: "Crêpe salée avec chou, viande et fruits de mer nappée de sauce",
            notesEs: "Panqueque salado con repollo, carne y mariscos cubierto con salsa",
            notesHe: "פנקייק מלוח עם כרוב, בשר ופירות ים מכוסה ברוטב"
        ),
        
        // Mochi
        FoodItem(
            id: UUID(),
            name: "Daifuku Mochi",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 125,
                protein: 2.8,
                carbohydrates: 28,
                fat: 0.8,
                fiber: 1.2,
                sugar: 18.5,
                vitaminA: 15,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 2,
                thiamin: 0.05,
                riboflavin: 0.03,
                niacin: 0.8,
                vitaminB6: 0.05,
                vitaminB12: 0,
                folate: 8,
                calcium: 25,
                iron: 0.8,
                magnesium: 15,
                phosphorus: 45,
                potassium: 85,
                sodium: 25,
                zinc: 0.5,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.3,
                cholesterol: 0
            ),
            servingSize: 50,
            servingUnit: "g",
            isCustom: true,
            notes: "Soft rice cake filled with sweet red bean paste",
            nameFr: "Mochi Daifuku",
            nameEs: "Mochi Daifuku",
            nameHe: "מוצ'י דייפוקו",
            notesFr: "Gâteau de riz moelleux fourré à la pâte de haricots rouges sucrée",
            notesEs: "Pastel de arroz suave relleno de pasta dulce de frijoles rojos",
            notesHe: "עוגת אורז רכה ממולאת ממרח שעועית אדומה מתוק"
        ),
        
        // Taiyaki
        FoodItem(
            id: UUID(),
            name: "Taiyaki",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 4.8,
                carbohydrates: 32,
                fat: 4.8,
                fiber: 1.8,
                sugar: 15.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 3,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 1.8,
                vitaminB6: 0.08,
                vitaminB12: 0.3,
                folate: 25,
                calcium: 65,
                iron: 1.8,
                magnesium: 25,
                phosphorus: 85,
                potassium: 125,
                sodium: 185,
                zinc: 0.8,
                selenium: 8.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 35
            ),
            servingSize: 80,
            servingUnit: "g",
            isCustom: true,
            notes: "Fish-shaped pastry filled with sweet red bean paste",
            nameFr: "Taiyaki",
            nameEs: "Taiyaki",
            nameHe: "טאיאקי",
            notesFr: "Pâtisserie en forme de poisson fourré à la pâte de haricots rouges sucrée",
            notesEs: "Pastelería en forma de pez rellena de pasta dulce de frijoles rojos",
            notesHe: "מאפה בצורת דג ממולא ממרח שעועית אדומה מתוק"
        ),
        
        // Soba
        FoodItem(
            id: UUID(),
            name: "Zaru Soba",
            category: .grains,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.8,
                carbohydrates: 58,
                fat: 2.8,
                fiber: 4.8,
                sugar: 3.5,
                vitaminA: 25,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 8,
                thiamin: 0.35,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.25,
                vitaminB12: 0,
                folate: 45,
                calcium: 45,
                iron: 2.8,
                magnesium: 125,
                phosphorus: 185,
                potassium: 285,
                sodium: 485,
                zinc: 2.2,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Cold buckwheat noodles served with dipping sauce",
            nameFr: "Soba Zaru",
            nameEs: "Soba Zaru",
            nameHe: "סובה זארו",
            notesFr: "Nouilles de sarrasin froides servies avec sauce de trempage",
            notesEs: "Fideos de trigo sarraceno fríos servidos con salsa para mojar",
            notesHe: "אטריות כוסמת קרות מוגשות עם רוטב טבילה"
        ),
        
        // Unagi
        FoodItem(
            id: UUID(),
            name: "Unagi Don",
            category: .protein,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 485,
                protein: 28.5,
                carbohydrates: 48,
                fat: 18.8,
                fiber: 1.8,
                sugar: 12.5,
                vitaminA: 485,
                vitaminC: 5,
                vitaminD: 18.5,
                vitaminE: 3.8,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.35,
                niacin: 4.8,
                vitaminB6: 0.22,
                vitaminB12: 2.8,
                folate: 25,
                calcium: 85,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 285,
                potassium: 385,
                sodium: 885,
                zinc: 2.8,
                selenium: 22.5,
                omega3: 1.8,
                omega6: 2.8,
                cholesterol: 185
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled eel glazed with sweet sauce over rice",
            nameFr: "Unagi Don",
            nameEs: "Unagi Don",
            nameHe: "אונאגי דון",
            notesFr: "Anguille grillée glacée avec sauce sucrée sur riz",
            notesEs: "Anguila a la parrilla glaseada con salsa dulce sobre arroz",
            notesHe: "צלופח צלוי מצופה ברוטב מתוק על אורז"
        ),
        
        // Matcha Ice Cream
        FoodItem(
            id: UUID(),
            name: "Matcha Ice Cream",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 4.8,
                carbohydrates: 28,
                fat: 10.8,
                fiber: 1.2,
                sugar: 22.5,
                vitaminA: 125,
                vitaminC: 2,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 8,
                thiamin: 0.05,
                riboflavin: 0.22,
                niacin: 0.8,
                vitaminB6: 0.08,
                vitaminB12: 1.2,
                folate: 15,
                calcium: 185,
                iron: 1.2,
                magnesium: 35,
                phosphorus: 125,
                potassium: 185,
                sodium: 85,
                zinc: 0.8,
                selenium: 5.5,
                omega3: 0.2,
                omega6: 0.8,
                cholesterol: 45
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Creamy green tea flavored ice cream with earthy matcha taste",
            nameFr: "Glace au Matcha",
            nameEs: "Helado de Matcha",
            nameHe: "גלידת מאצ'ה",
            notesFr: "Glace crémeuse au thé vert avec goût terreux de matcha",
            notesEs: "Helado cremoso con sabor a té verde con sabor terroso de matcha",
            notesHe: "גלידה קרמית בטעם תה ירוק עם טעם עפרירי של מאצ'ה"
        ),
        
        // Edamame
        FoodItem(
            id: UUID(),
            name: "Edamame",
            category: .vegetables,
            cuisineType: .japanese,
            nutritionalInfo: NutritionalInfo(
                calories: 125,
                protein: 11.8,
                carbohydrates: 8,
                fat: 5.8,
                fiber: 5.2,
                sugar: 2.8,
                vitaminA: 15,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 26,
                thiamin: 0.2,
                riboflavin: 0.15,
                niacin: 0.9,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 311,
                calcium: 63,
                iron: 2.3,
                magnesium: 64,
                phosphorus: 169,
                potassium: 436,
                sodium: 6,
                zinc: 1.4,
                selenium: 1.2,
                omega3: 0.6,
                omega6: 2.8,
                cholesterol: 0
            ),
            servingSize: 85,
            servingUnit: "g",
            isCustom: true,
            notes: "Boiled young soybeans in pods, lightly salted",
            nameFr: "Edamame",
            nameEs: "Edamame",
            nameHe: "אדמאמה",
            notesFr: "Jeunes graines de soja bouillies dans leurs gousses, légèrement salées",
            notesEs: "Granos de soja jóvenes hervidos en sus vainas, ligeramente salados",
            notesHe: "פולי סויה צעירים מבושלים בתרמילים, מומלחים קלות"
        )
    ]
}
