import Foundation

struct KoreanCuisineFoodItems {
    static let foods: [FoodItem] = [
        // Kimchi
        FoodItem(
            id: UUID(),
            name: "Kimchi",
            category: .vegetables,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 45,
                protein: 2.8,
                carbohydrates: 8,
                fat: 0.5,
                fiber: 2.8,
                sugar: 4.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 85,
                thiamin: 0.08,
                riboflavin: 0.12,
                niacin: 1.2,
                vitaminB6: 0.15,
                vitaminB12: 0,
                folate: 45,
                calcium: 85,
                iron: 1.8,
                magnesium: 25,
                phosphorus: 45,
                potassium: 285,
                sodium: 685,
                zinc: 0.8,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Fermented cabbage with Korean spices - traditional side dish",
            nameFr: "Kimchi",
            nameEs: "Kimchi",
            nameHe: "קימצ'י",
            notesFr: "Chou fermenté aux épices coréennes - accompagnement traditionnel",
            notesEs: "Repollo fermentado con especias coreanas - acompañamiento tradicional",
            notesHe: "כרוב מותסס עם תבלינים קוריאניים - תוספת מסורתית"
        ),
        
        // Bulgogi
        FoodItem(
            id: UUID(),
            name: "Bulgogi",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 26.5,
                carbohydrates: 12,
                fat: 18.8,
                fiber: 1.2,
                sugar: 8.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.5,
                vitaminE: 1.8,
                vitaminK: 12,
                thiamin: 0.22,
                riboflavin: 0.28,
                niacin: 8.8,
                vitaminB6: 0.45,
                vitaminB12: 3.2,
                folate: 25,
                calcium: 45,
                iron: 3.2,
                magnesium: 42,
                phosphorus: 245,
                potassium: 385,
                sodium: 785,
                zinc: 4.8,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Marinated grilled beef in sweet soy sauce",
            nameFr: "Bulgogi",
            nameEs: "Bulgogi",
            nameHe: "בולגוגי",
            notesFr: "Bœuf grillé mariné dans une sauce soja sucrée",
            notesEs: "Carne de res marinada a la parrilla en salsa de soja dulce",
            notesHe: "בקר צלוי במרינדה ברוטב סויה מתוק"
        ),
        
        // Bibimbap
        FoodItem(
            id: UUID(),
            name: "Bibimbap",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 485,
                protein: 18.5,
                carbohydrates: 68,
                fat: 14.8,
                fiber: 5.2,
                sugar: 8.5,
                vitaminA: 285,
                vitaminC: 35,
                vitaminD: 1.8,
                vitaminE: 3.2,
                vitaminK: 125,
                thiamin: 0.28,
                riboflavin: 0.35,
                niacin: 6.8,
                vitaminB6: 0.45,
                vitaminB12: 2.8,
                folate: 125,
                calcium: 185,
                iron: 4.2,
                magnesium: 85,
                phosphorus: 285,
                potassium: 585,
                sodium: 885,
                zinc: 3.8,
                selenium: 18.5,
                omega3: 0.8,
                omega6: 4.2,
                cholesterol: 185
            ),
            servingSize: 300,
            servingUnit: "g",
            isCustom: true,
            notes: "Mixed rice bowl with vegetables, meat, and fried egg",
            nameFr: "Bibimbap",
            nameEs: "Bibimbap",
            nameHe: "ביבימבאפ",
            notesFr: "Bol de riz mélangé avec légumes, viande et œuf frit",
            notesEs: "Tazón de arroz mixto con verduras, carne y huevo frito",
            notesHe: "קערת אורז מעורב עם ירקות, בשר וביצה מטוגנת"
        ),
        
        // Korean Fried Chicken
        FoodItem(
            id: UUID(),
            name: "Korean Fried Chicken",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 24.5,
                carbohydrates: 18,
                fat: 24.8,
                fiber: 1.2,
                sugar: 12.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 11.8,
                vitaminB6: 0.58,
                vitaminB12: 2.5,
                folate: 22,
                calcium: 45,
                iron: 2.8,
                magnesium: 38,
                phosphorus: 225,
                potassium: 325,
                sodium: 885,
                zinc: 3.2,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 8.8,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy double-fried chicken with sweet and spicy glaze",
            nameFr: "Poulet Frit Coréen",
            nameEs: "Pollo Frito Coreano",
            nameHe: "עוף מטוגן קוריאני",
            notesFr: "Poulet croustillant frit deux fois avec glaçage sucré et épicé",
            notesEs: "Pollo crujiente frito dos veces con glaseado dulce y picante",
            notesHe: "עוף פריך מטוגן פעמיים עם ציפוי מתוק וחריף"
        ),
        
        // Japchae
        FoodItem(
            id: UUID(),
            name: "Japchae",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 8.5,
                carbohydrates: 52,
                fat: 6.8,
                fiber: 3.8,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0,
                vitaminE: 2.2,
                vitaminK: 85,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.25,
                vitaminB12: 0,
                folate: 45,
                calcium: 85,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 125,
                potassium: 385,
                sodium: 685,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Sweet potato starch noodles with vegetables and sesame oil",
            nameFr: "Japchae",
            nameEs: "Japchae",
            nameHe: "ג'אפצ'ה",
            notesFr: "Nouilles d'amidon de patate douce avec légumes et huile de sésame",
            notesEs: "Fideos de almidón de batata con verduras y aceite de sésamo",
            notesHe: "אטריות עמילן בטטה עם ירקות ושמן שומשום"
        ),
        
        // Galbi
        FoodItem(
            id: UUID(),
            name: "Galbi",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 425,
                protein: 28.5,
                carbohydrates: 15,
                fat: 28.8,
                fiber: 1.2,
                sugar: 12.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 12,
                thiamin: 0.25,
                riboflavin: 0.32,
                niacin: 9.8,
                vitaminB6: 0.48,
                vitaminB12: 3.8,
                folate: 25,
                calcium: 65,
                iron: 3.8,
                magnesium: 48,
                phosphorus: 285,
                potassium: 385,
                sodium: 785,
                zinc: 5.2,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 95
            ),
            servingSize: 160,
            servingUnit: "g",
            isCustom: true,
            notes: "Marinated grilled beef short ribs",
            nameFr: "Galbi",
            nameEs: "Galbi",
            nameHe: "גלבי",
            notesFr: "Côtes de bœuf grillées marinées",
            notesEs: "Costillas de res marinadas a la parrilla",
            notesHe: "צלעות בקר צלויות במרינדה"
        ),
        
        // Tteokbokki
        FoodItem(
            id: UUID(),
            name: "Tteokbokki",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 6.8,
                carbohydrates: 48,
                fat: 2.8,
                fiber: 2.2,
                sugar: 12.5,
                vitaminA: 125,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 25,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 2.2,
                vitaminB6: 0.18,
                vitaminB12: 0,
                folate: 35,
                calcium: 85,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 125,
                potassium: 285,
                sodium: 885,
                zinc: 1.2,
                selenium: 5.5,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Spicy rice cakes in gochujang sauce",
            nameFr: "Tteokbokki",
            nameEs: "Tteokbokki",
            nameHe: "טוקבוקי",
            notesFr: "Gâteaux de riz épicés dans une sauce gochujang",
            notesEs: "Pasteles de arroz picantes en salsa gochujang",
            notesHe: "עוגות אורז חריפות ברוטב גוצ'וג'אנג"
        ),
        
        // Sundubu Jjigae
        FoodItem(
            id: UUID(),
            name: "Sundubu Jjigae",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 14.8,
                carbohydrates: 12,
                fat: 9.8,
                fiber: 2.8,
                sugar: 5.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 1.2,
                vitaminE: 2.2,
                vitaminK: 35,
                thiamin: 0.15,
                riboflavin: 0.18,
                niacin: 3.8,
                vitaminB6: 0.25,
                vitaminB12: 1.8,
                folate: 65,
                calcium: 285,
                iron: 3.2,
                magnesium: 85,
                phosphorus: 185,
                potassium: 385,
                sodium: 985,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.5,
                omega6: 2.8,
                cholesterol: 125
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Spicy soft tofu stew with vegetables and egg",
            nameFr: "Sundubu Jjigae",
            nameEs: "Sundubu Jjigae",
            nameHe: "סונדובו ג'יגה",
            notesFr: "Ragoût de tofu mou épicé avec légumes et œuf",
            notesEs: "Guiso de tofu suave picante con verduras y huevo",
            notesHe: "תבשיל טופו רך חריף עם ירקות וביצה"
        ),
        
        // Korean BBQ Pork
        FoodItem(
            id: UUID(),
            name: "Samgyeopsal",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 485,
                protein: 22.5,
                carbohydrates: 2,
                fat: 42.8,
                fiber: 0,
                sugar: 1.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0.8,
                vitaminE: 1.2,
                vitaminK: 2,
                thiamin: 0.65,
                riboflavin: 0.25,
                niacin: 5.8,
                vitaminB6: 0.42,
                vitaminB12: 2.8,
                folate: 8,
                calcium: 25,
                iron: 1.8,
                magnesium: 28,
                phosphorus: 185,
                potassium: 285,
                sodium: 485,
                zinc: 3.2,
                selenium: 18.5,
                omega3: 0.5,
                omega6: 4.8,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled pork belly slices - Korean BBQ staple",
            nameFr: "Samgyeopsal",
            nameEs: "Samgyeopsal",
            nameHe: "סמגיופסל",
            notesFr: "Tranches de poitrine de porc grillées - base du BBQ coréen",
            notesEs: "Rebanadas de panceta de cerdo a la parrilla - básico del BBQ coreano",
            notesHe: "פרוסות בטן חזיר צלויות - בסיס הבברקיו הקוריאני"
        ),
        
        // Mandu
        FoodItem(
            id: UUID(),
            name: "Mandu",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 12.8,
                carbohydrates: 28,
                fat: 9.8,
                fiber: 2.8,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0.3,
                vitaminE: 1.8,
                vitaminK: 25,
                thiamin: 0.22,
                riboflavin: 0.15,
                niacin: 4.2,
                vitaminB6: 0.28,
                vitaminB12: 1.2,
                folate: 45,
                calcium: 65,
                iron: 2.8,
                magnesium: 45,
                phosphorus: 145,
                potassium: 285,
                sodium: 685,
                zinc: 2.2,
                selenium: 15.5,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 35
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Korean dumplings filled with meat and vegetables",
            nameFr: "Mandu",
            nameEs: "Mandu",
            nameHe: "מנדו",
            notesFr: "Raviolis coréens farcis de viande et légumes",
            notesEs: "Dumplings coreanos rellenos de carne y verduras",
            notesHe: "כיסוני בצק קוריאניים ממולאים בשר וירקות"
        ),
        
        // Naengmyeon
        FoodItem(
            id: UUID(),
            name: "Naengmyeon",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.8,
                carbohydrates: 52,
                fat: 4.8,
                fiber: 3.2,
                sugar: 8.5,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 25,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 3.8,
                vitaminB6: 0.25,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 85,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 145,
                potassium: 385,
                sodium: 785,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 25
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Cold buckwheat noodles in chilled broth",
            nameFr: "Naengmyeon",
            nameEs: "Naengmyeon",
            nameHe: "נאנגמיון",
            notesFr: "Nouilles de sarrasin froides dans un bouillon glacé",
            notesEs: "Fideos de trigo sarraceno fríos en caldo helado",
            notesHe: "אטריות כוסמת קרות במרק קר"
        ),
        
        // Bossam
        FoodItem(
            id: UUID(),
            name: "Bossam",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 28.5,
                carbohydrates: 8,
                fat: 20.8,
                fiber: 2.8,
                sugar: 4.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 125,
                thiamin: 0.58,
                riboflavin: 0.22,
                niacin: 6.8,
                vitaminB6: 0.45,
                vitaminB12: 2.8,
                folate: 85,
                calcium: 185,
                iron: 2.8,
                magnesium: 48,
                phosphorus: 225,
                potassium: 485,
                sodium: 785,
                zinc: 3.8,
                selenium: 22.5,
                omega3: 0.5,
                omega6: 3.8,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Boiled pork belly wrapped in napa cabbage leaves",
            nameFr: "Bossam",
            nameEs: "Bossam",
            nameHe: "בוסאם",
            notesFr: "Poitrine de porc bouillie enveloppée dans des feuilles de chou napa",
            notesEs: "Panceta de cerdo hervida envuelta en hojas de repollo napa",
            notesHe: "בטן חזיר מבושלת עטופה בעלי כרוב נאפה"
        ),
        
        // Korean Corn Dog
        FoodItem(
            id: UUID(),
            name: "Korean Corn Dog",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 14.8,
                carbohydrates: 35,
                fat: 22.8,
                fiber: 2.2,
                sugar: 8.5,
                vitaminA: 85,
                vitaminC: 5,
                vitaminD: 0.8,
                vitaminE: 2.8,
                vitaminK: 8,
                thiamin: 0.25,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.22,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 125,
                iron: 2.8,
                magnesium: 35,
                phosphorus: 185,
                potassium: 285,
                sodium: 885,
                zinc: 2.8,
                selenium: 15.5,
                omega3: 0.3,
                omega6: 8.8,
                cholesterol: 65
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Deep-fried hot dog on stick with various coatings",
            nameFr: "Corn Dog Coréen",
            nameEs: "Corn Dog Coreano",
            nameHe: "קורן דוג קוריאני",
            notesFr: "Hot-dog frit sur bâton avec divers enrobages",
            notesEs: "Perro caliente frito en palo con varios recubrimientos",
            notesHe: "נקניקייה מטוגנת על מקל עם ציפויים שונים"
        ),
        
        // Kimchi Jjigae
        FoodItem(
            id: UUID(),
            name: "Kimchi Jjigae",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 12.8,
                carbohydrates: 15,
                fat: 8.8,
                fiber: 3.8,
                sugar: 6.5,
                vitaminA: 285,
                vitaminC: 45,
                vitaminD: 0.3,
                vitaminE: 1.8,
                vitaminK: 125,
                thiamin: 0.35,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.28,
                vitaminB12: 1.8,
                folate: 85,
                calcium: 125,
                iron: 3.2,
                magnesium: 65,
                phosphorus: 145,
                potassium: 485,
                sodium: 1085,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 35
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Spicy kimchi stew with pork and tofu",
            nameFr: "Kimchi Jjigae",
            nameEs: "Kimchi Jjigae",
            nameHe: "קימצ'י ג'יגה",
            notesFr: "Ragoût de kimchi épicé avec porc et tofu",
            notesEs: "Guiso de kimchi picante con cerdo y tofu",
            notesHe: "תבשיל קימצ'י חריף עם חזיר וטופו"
        ),
        
        // Pajeon
        FoodItem(
            id: UUID(),
            name: "Pajeon",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 8.8,
                carbohydrates: 32,
                fat: 7.8,
                fiber: 2.8,
                sugar: 3.5,
                vitaminA: 125,
                vitaminC: 25,
                vitaminD: 1.2,
                vitaminE: 2.2,
                vitaminK: 85,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 3.2,
                vitaminB6: 0.22,
                vitaminB12: 1.2,
                folate: 65,
                calcium: 85,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 125,
                potassium: 285,
                sodium: 685,
                zinc: 1.8,
                selenium: 12.5,
                omega3: 0.5,
                omega6: 3.2,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Korean scallion pancake with seafood",
            nameFr: "Pajeon",
            nameEs: "Pajeon",
            nameHe: "פאג'ון",
            notesFr: "Crêpe coréenne aux oignons verts avec fruits de mer",
            notesEs: "Panqueque coreano de cebolletas con mariscos",
            notesHe: "פנקייק קוריאני בצל ירוק עם פירות ים"
        ),
        
        // Gimbap
        FoodItem(
            id: UUID(),
            name: "Gimbap",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.8,
                carbohydrates: 42,
                fat: 8.8,
                fiber: 3.2,
                sugar: 5.5,
                vitaminA: 185,
                vitaminC: 15,
                vitaminD: 1.2,
                vitaminE: 2.8,
                vitaminK: 45,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.28,
                vitaminB12: 2.2,
                folate: 65,
                calcium: 125,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 185,
                potassium: 385,
                sodium: 685,
                zinc: 2.8,
                selenium: 18.5,
                omega3: 0.8,
                omega6: 3.2,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Korean rice rolls with vegetables and meat wrapped in seaweed",
            nameFr: "Gimbap",
            nameEs: "Gimbap",
            nameHe: "גימבאפ",
            notesFr: "Rouleaux de riz coréens avec légumes et viande enveloppés dans des algues",
            notesEs: "Rollos de arroz coreanos con verduras y carne envueltos en algas",
            notesHe: "רולי אורז קוריאניים עם ירקות ובשר עטופים באצות"
        ),
        
        // Hotteok
        FoodItem(
            id: UUID(),
            name: "Hotteok",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 4.8,
                carbohydrates: 38,
                fat: 6.8,
                fiber: 1.8,
                sugar: 18.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 3,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.2,
                vitaminB6: 0.08,
                vitaminB12: 0.3,
                folate: 35,
                calcium: 85,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 85,
                potassium: 125,
                sodium: 285,
                zinc: 0.8,
                selenium: 8.5,
                omega3: 0.2,
                omega6: 2.8,
                cholesterol: 35
            ),
            servingSize: 80,
            servingUnit: "g",
            isCustom: true,
            notes: "Sweet Korean pancake filled with brown sugar and nuts",
            nameFr: "Hotteok",
            nameEs: "Hotteok",
            nameHe: "הוטוק",
            notesFr: "Crêpe sucrée coréenne fourrée au sucre brun et aux noix",
            notesEs: "Panqueque dulce coreano relleno de azúcar moreno y nueces",
            notesHe: "פנקייק מתוק קוריאני ממולא סוכר חום ואגוזים"
        ),
        
        // Dakgalbi
        FoodItem(
            id: UUID(),
            name: "Dakgalbi",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 26.5,
                carbohydrates: 18,
                fat: 16.8,
                fiber: 3.2,
                sugar: 12.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 0.5,
                vitaminE: 2.8,
                vitaminK: 85,
                thiamin: 0.22,
                riboflavin: 0.25,
                niacin: 11.8,
                vitaminB6: 0.65,
                vitaminB12: 2.8,
                folate: 65,
                calcium: 85,
                iron: 3.2,
                magnesium: 58,
                phosphorus: 245,
                potassium: 485,
                sodium: 885,
                zinc: 3.8,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 4.8,
                cholesterol: 85
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Spicy stir-fried chicken with vegetables and rice cakes",
            nameFr: "Dakgalbi",
            nameEs: "Dakgalbi",
            nameHe: "דקגלבי",
            notesFr: "Poulet sauté épicé avec légumes et gâteaux de riz",
            notesEs: "Pollo salteado picante con verduras y pasteles de arroz",
            notesHe: "עוף מוקפץ חריף עם ירקות ועוגות אורז"
        ),
        
        // Bungeoppang
        FoodItem(
            id: UUID(),
            name: "Bungeoppang",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 4.8,
                carbohydrates: 32,
                fat: 4.8,
                fiber: 2.2,
                sugar: 15.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 3,
                thiamin: 0.12,
                riboflavin: 0.08,
                niacin: 1.8,
                vitaminB6: 0.08,
                vitaminB12: 0.3,
                folate: 25,
                calcium: 65,
                iron: 1.8,
                magnesium: 25,
                phosphorus: 85,
                potassium: 125,
                sodium: 185,
                zinc: 0.8,
                selenium: 8.5,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 35
            ),
            servingSize: 80,
            servingUnit: "g",
            isCustom: true,
            notes: "Fish-shaped pastry filled with sweet red bean paste",
            nameFr: "Bungeoppang",
            nameEs: "Bungeoppang",
            nameHe: "בונגאופאנג",
            notesFr: "Pâtisserie en forme de poisson fourrée à la pâte de haricots rouges sucrée",
            notesEs: "Pastelería en forma de pez rellena de pasta dulce de frijoles rojos",
            notesHe: "מאפה בצורת דג ממולא ממרח שעועית אדומה מתוק"
        ),
        
        // Seolleongtang
        FoodItem(
            id: UUID(),
            name: "Seolleongtang",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 18.5,
                carbohydrates: 8,
                fat: 12.8,
                fiber: 1.2,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.8,
                vitaminE: 1.2,
                vitaminK: 12,
                thiamin: 0.15,
                riboflavin: 0.22,
                niacin: 6.8,
                vitaminB6: 0.32,
                vitaminB12: 2.8,
                folate: 25,
                calcium: 125,
                iron: 2.8,
                magnesium: 45,
                phosphorus: 185,
                potassium: 385,
                sodium: 785,
                zinc: 3.8,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 65
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Milky white ox bone soup with rice and scallions",
            nameFr: "Seolleongtang",
            nameEs: "Seolleongtang",
            nameHe: "סאולונגטאנג",
            notesFr: "Soupe d'os de bœuf blanc laiteux avec riz et oignons verts",
            notesEs: "Sopa de hueso de buey blanco lechoso con arroz y cebolletas",
            notesHe: "מרק עצמות שור לבן חלבי עם אורז ובצל ירוק"
        ),
        
        // Korean Pancake
        FoodItem(
            id: UUID(),
            name: "Kimchi Jeon",
            category: .grains,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.8,
                carbohydrates: 28,
                fat: 5.8,
                fiber: 3.2,
                sugar: 4.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 1.2,
                vitaminE: 1.8,
                vitaminK: 125,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.18,
                vitaminB12: 0.8,
                folate: 65,
                calcium: 125,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 85,
                potassium: 385,
                sodium: 785,
                zinc: 1.2,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy pancake made with kimchi and flour batter",
            nameFr: "Kimchi Jeon",
            nameEs: "Kimchi Jeon",
            nameHe: "קימצ'י ג'ון",
            notesFr: "Crêpe croustillante faite avec kimchi et pâte de farine",
            notesEs: "Panqueque crujiente hecho con kimchi y masa de harina",
            notesHe: "פנקייק פריך עשוי קימצ'י ובצק קמח"
        ),
        
        // Korean Rice Wine
        FoodItem(
            id: UUID(),
            name: "Makgeolli",
            category: .beverages,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 85,
                protein: 1.8,
                carbohydrates: 8,
                fat: 0.2,
                fiber: 0.5,
                sugar: 4.5,
                vitaminA: 5,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 1,
                thiamin: 0.05,
                riboflavin: 0.08,
                niacin: 0.8,
                vitaminB6: 0.05,
                vitaminB12: 0.2,
                folate: 15,
                calcium: 25,
                iron: 0.5,
                magnesium: 15,
                phosphorus: 35,
                potassium: 85,
                sodium: 25,
                zinc: 0.3,
                selenium: 2.5,
                omega3: 0.05,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 150,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional Korean rice wine - milky and slightly sweet",
            nameFr: "Makgeolli",
            nameEs: "Makgeolli",
            nameHe: "מקגולי",
            notesFr: "Vin de riz coréen traditionnel - laiteux et légèrement sucré",
            notesEs: "Vino de arroz coreano tradicional - lechoso y ligeramente dulce",
            notesHe: "יין אורז קוריאני מסורתי - חלבי ומתוק קלות"
        ),
        
        // Korean Chicken Soup
        FoodItem(
            id: UUID(),
            name: "Samgyetang",
            category: .protein,
            cuisineType: .korean,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 32.5,
                carbohydrates: 25,
                fat: 18.8,
                fiber: 2.8,
                sugar: 5.5,
                vitaminA: 125,
                vitaminC: 15,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.25,
                riboflavin: 0.28,
                niacin: 14.8,
                vitaminB6: 0.68,
                vitaminB12: 3.2,
                folate: 45,
                calcium: 85,
                iron: 3.2,
                magnesium: 65,
                phosphorus: 285,
                potassium: 485,
                sodium: 785,
                zinc: 4.2,
                selenium: 28.5,
                omega3: 0.5,
                omega6: 4.2,
                cholesterol: 125
            ),
            servingSize: 350,
            servingUnit: "ml",
            isCustom: true,
            notes: "Whole young chicken stuffed with rice, ginseng, and herbs",
            nameFr: "Samgyetang",
            nameEs: "Samgyetang",
            nameHe: "סמגיטאנג",
            notesFr: "Jeune poulet entier farci de riz, ginseng et herbes",
            notesEs: "Pollo joven entero relleno de arroz, ginseng y hierbas",
            notesHe: "עוף צעיר שלם ממולא אורז, ג'ינסנג ועשבי תיבול"
        ),
        
        // Korean Beef Soup
        FoodItem(
            id: UUID(),
            name: "Yukgaejang",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 22.5,
                carbohydrates: 12,
                fat: 12.8,
                fiber: 3.8,
                sugar: 5.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 85,
                thiamin: 0.18,
                riboflavin: 0.25,
                niacin: 8.8,
                vitaminB6: 0.45,
                vitaminB12: 3.2,
                folate: 65,
                calcium: 85,
                iron: 4.2,
                magnesium: 65,
                phosphorus: 225,
                potassium: 485,
                sodium: 985,
                zinc: 4.8,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 75
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Spicy shredded beef soup with vegetables and bean sprouts",
            nameFr: "Yukgaejang",
            nameEs: "Yukgaejang",
            nameHe: "יוקגאג'אנג",
            notesFr: "Soupe de bœuf effiloché épicée avec légumes et pousses de soja",
            notesEs: "Sopa de carne desmenuzada picante con verduras y brotes de soja",
            notesHe: "מרק בקר מגורד חריף עם ירקות ונבטי סויה"
        )
    ]
}
