import Foundation

struct MexicanCuisineFoodItems {
    static let foods: [FoodItem] = [
        // Tacos al Pastor
        FoodItem(
            id: UUID(),
            name: "Tacos al Pastor",
            category: .protein,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 18.5,
                carbohydrates: 22,
                fat: 14.2,
                fiber: 3.8,
                sugar: 4.2,
                vitaminA: 125,
                vitaminC: 12,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 8,
                thiamin: 0.25,
                riboflavin: 0.18,
                niacin: 6.8,
                vitaminB6: 0.42,
                vitaminB12: 1.8,
                folate: 28,
                calcium: 85,
                iron: 2.4,
                magnesium: 35,
                phosphorus: 185,
                potassium: 385,
                sodium: 520,
                zinc: 3.2,
                selenium: 18.5,
                omega3: 0.2,
                omega6: 2.1,
                cholesterol: 45
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional pork tacos with pineapple, onions, and cilantro",
            nameFr: "Tacos al Pastor",
            nameEs: "Tacos al Pastor",
            nameHe: "טאקוס אל פסטור",
            notesFr: "Tacos traditionnels au porc avec ananas, oignons et coriandre",
            notesEs: "Tacos tradicionales de cerdo con piña, cebolla y cilantro",
            notesHe: "טאקוס מסורתיים עם חזיר, אננס, בצל וכוסברה"
        ),
        
        // Enchiladas Verdes
        FoodItem(
            id: UUID(),
            name: "Enchiladas Verdes",
            category: .grains,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 16.8,
                carbohydrates: 28,
                fat: 18.5,
                fiber: 4.2,
                sugar: 5.8,
                vitaminA: 185,
                vitaminC: 22,
                vitaminD: 0.5,
                vitaminE: 1.8,
                vitaminK: 15,
                thiamin: 0.18,
                riboflavin: 0.28,
                niacin: 4.2,
                vitaminB6: 0.35,
                vitaminB12: 0.8,
                folate: 45,
                calcium: 245,
                iron: 2.1,
                magnesium: 42,
                phosphorus: 195,
                potassium: 425,
                sodium: 680,
                zinc: 2.8,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 35
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Corn tortillas filled with chicken in green tomatillo sauce",
            nameFr: "Enchiladas Vertes",
            nameEs: "Enchiladas Verdes",
            nameHe: "אנצ'ילדס ירוקות",
            notesFr: "Tortillas de maïs farcies au poulet dans une sauce verte aux tomatilles",
            notesEs: "Tortillas de maíz rellenas de pollo en salsa verde de tomatillo",
            notesHe: "טורטיות תירס ממולאות עוף ברוטב ירוק"
        ),
        
        // Chiles Rellenos
        FoodItem(
            id: UUID(),
            name: "Chiles Rellenos",
            category: .vegetables,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 295,
                protein: 14.2,
                carbohydrates: 18,
                fat: 20.8,
                fiber: 3.5,
                sugar: 8.2,
                vitaminA: 245,
                vitaminC: 185,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 12,
                thiamin: 0.12,
                riboflavin: 0.32,
                niacin: 2.8,
                vitaminB6: 0.48,
                vitaminB12: 0.6,
                folate: 35,
                calcium: 285,
                iron: 1.8,
                magnesium: 38,
                phosphorus: 225,
                potassium: 385,
                sodium: 485,
                zinc: 2.2,
                selenium: 15.8,
                omega3: 0.2,
                omega6: 1.5,
                cholesterol: 125
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Poblano peppers stuffed with cheese, battered and fried",
            nameFr: "Chiles Rellenos",
            nameEs: "Chiles Rellenos",
            nameHe: "צ'ילס רייאנוס",
            notesFr: "Poivrons poblano farcis au fromage, panés et frits",
            notesEs: "Chiles poblanos rellenos de queso, empanizados y fritos",
            notesHe: "פלפלים ממולאים גבינה, מצופים ומטוגנים"
        ),
        
        // Mole Poblano
        FoodItem(
            id: UUID(),
            name: "Mole Poblano",
            category: .protein,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 22.5,
                carbohydrates: 25,
                fat: 24.8,
                fiber: 5.2,
                sugar: 12.5,
                vitaminA: 165,
                vitaminC: 8,
                vitaminD: 0.2,
                vitaminE: 3.5,
                vitaminK: 18,
                thiamin: 0.28,
                riboflavin: 0.22,
                niacin: 8.5,
                vitaminB6: 0.55,
                vitaminB12: 2.2,
                folate: 38,
                calcium: 125,
                iron: 3.8,
                magnesium: 85,
                phosphorus: 245,
                potassium: 485,
                sodium: 625,
                zinc: 4.2,
                selenium: 22.5,
                omega3: 0.8,
                omega6: 3.2,
                cholesterol: 65
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Complex sauce with chocolate, chiles, and spices over chicken",
            nameFr: "Mole Poblano",
            nameEs: "Mole Poblano",
            nameHe: "מולה פובלנו",
            notesFr: "Sauce complexe au chocolat, piments et épices sur poulet",
            notesEs: "Salsa compleja con chocolate, chiles y especias sobre pollo",
            notesHe: "רוטב מורכב עם שוקולד, צ'ילי ותבלינים על עוף"
        ),
        
        // Pozole Rojo
        FoodItem(
            id: UUID(),
            name: "Pozole Rojo",
            category: .grains,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 18.2,
                carbohydrates: 28,
                fat: 8.5,
                fiber: 6.8,
                sugar: 4.2,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0.1,
                vitaminE: 1.2,
                vitaminK: 8,
                thiamin: 0.22,
                riboflavin: 0.15,
                niacin: 5.8,
                vitaminB6: 0.38,
                vitaminB12: 1.5,
                folate: 125,
                calcium: 65,
                iron: 2.8,
                magnesium: 85,
                phosphorus: 185,
                potassium: 485,
                sodium: 785,
                zinc: 3.5,
                selenium: 18.2,
                omega3: 0.2,
                omega6: 1.2,
                cholesterol: 42
            ),
            servingSize: 300,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional hominy soup with pork in red chile broth",
            nameFr: "Pozole Rouge",
            nameEs: "Pozole Rojo",
            nameHe: "פוזולה רוחו",
            notesFr: "Soupe traditionnelle au maïs concassé et porc dans un bouillon de piment rouge",
            notesEs: "Sopa tradicional de maíz pozolero con cerdo en caldo de chile rojo",
            notesHe: "מרק מסורתי עם תירס ובשר חזיר במרק צ'ילי אדום"
        ),
        
        // Tamales
        FoodItem(
            id: UUID(),
            name: "Tamales",
            category: .grains,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.5,
                carbohydrates: 35,
                fat: 12.8,
                fiber: 4.5,
                sugar: 3.8,
                vitaminA: 95,
                vitaminC: 6,
                vitaminD: 0.2,
                vitaminE: 1.8,
                vitaminK: 5,
                thiamin: 0.18,
                riboflavin: 0.12,
                niacin: 3.5,
                vitaminB6: 0.25,
                vitaminB12: 0.8,
                folate: 85,
                calcium: 85,
                iron: 2.2,
                magnesium: 55,
                phosphorus: 145,
                potassium: 285,
                sodium: 485,
                zinc: 2.2,
                selenium: 12.8,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 28
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Corn masa filled with meat or cheese, wrapped in corn husks",
            nameFr: "Tamales",
            nameEs: "Tamales",
            nameHe: "טמלס",
            notesFr: "Pâte de maïs farcie à la viande ou au fromage, enveloppée dans des feuilles de maïs",
            notesEs: "Masa de maíz rellena de carne o queso, envuelta en hojas de maíz",
            notesHe: "בצק תירס ממולא בשר או גבינה, עטוף בעלי תירס"
        ),
        
        // Quesadillas
        FoodItem(
            id: UUID(),
            name: "Quesadillas",
            category: .grains,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 16.8,
                carbohydrates: 28,
                fat: 18.5,
                fiber: 3.2,
                sugar: 2.8,
                vitaminA: 125,
                vitaminC: 4,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 6,
                thiamin: 0.15,
                riboflavin: 0.28,
                niacin: 3.8,
                vitaminB6: 0.18,
                vitaminB12: 0.9,
                folate: 42,
                calcium: 285,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 225,
                potassium: 185,
                sodium: 485,
                zinc: 2.8,
                selenium: 15.2,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 45
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled tortillas filled with cheese and optional meat",
            nameFr: "Quesadillas",
            nameEs: "Quesadillas",
            nameHe: "קסדיאס",
            notesFr: "Tortillas grillées farcies au fromage et viande optionnelle",
            notesEs: "Tortillas a la plancha rellenas de queso y carne opcional",
            notesHe: "טורטיות צלויות ממולאות גבינה ובשר אופציונלי"
        ),
        
        // Carnitas
        FoodItem(
            id: UUID(),
            name: "Carnitas",
            category: .protein,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 345,
                protein: 28.5,
                carbohydrates: 2,
                fat: 24.8,
                fiber: 0.2,
                sugar: 0.8,
                vitaminA: 8,
                vitaminC: 2,
                vitaminD: 0.8,
                vitaminE: 0.8,
                vitaminK: 2,
                thiamin: 0.45,
                riboflavin: 0.28,
                niacin: 8.5,
                vitaminB6: 0.52,
                vitaminB12: 2.8,
                folate: 12,
                calcium: 25,
                iron: 2.5,
                magnesium: 28,
                phosphorus: 245,
                potassium: 385,
                sodium: 485,
                zinc: 4.2,
                selenium: 28.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Slow-cooked, tender shredded pork shoulder",
            nameFr: "Carnitas",
            nameEs: "Carnitas",
            nameHe: "קרניטס",
            notesFr: "Épaule de porc effilochée, cuite lentement et tendre",
            notesEs: "Cerdo deshebrado cocido lentamente hasta quedar tierno",
            notesHe: "כתף חזיר מבושלת לאט ומפורקת"
        ),
        
        // Guacamole
        FoodItem(
            id: UUID(),
            name: "Guacamole",
            category: .vegetables,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 2.2,
                carbohydrates: 8.5,
                fat: 15.2,
                fiber: 6.8,
                sugar: 1.2,
                vitaminA: 8,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 2.8,
                vitaminK: 22,
                thiamin: 0.08,
                riboflavin: 0.15,
                niacin: 1.8,
                vitaminB6: 0.28,
                vitaminB12: 0,
                folate: 85,
                calcium: 15,
                iron: 0.6,
                magnesium: 32,
                phosphorus: 55,
                potassium: 485,
                sodium: 285,
                zinc: 0.7,
                selenium: 0.4,
                omega3: 0.1,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Fresh avocado dip with lime, onions, tomatoes, and cilantro",
            nameFr: "Guacamole",
            nameEs: "Guacamole",
            nameHe: "גואקמולה",
            notesFr: "Trempette d'avocat frais avec citron vert, oignons, tomates et coriandre",
            notesEs: "Dip de aguacate fresco con limón, cebolla, tomate y cilantro",
            notesHe: "רוטב אבוקדו טרי עם ליים, בצל, עגבניות וכוסברה"
        ),
        
        // Ceviche
        FoodItem(
            id: UUID(),
            name: "Ceviche",
            category: .protein,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 125,
                protein: 22.5,
                carbohydrates: 8,
                fat: 1.8,
                fiber: 2.2,
                sugar: 4.5,
                vitaminA: 65,
                vitaminC: 45,
                vitaminD: 0.8,
                vitaminE: 0.8,
                vitaminK: 12,
                thiamin: 0.08,
                riboflavin: 0.12,
                niacin: 5.8,
                vitaminB6: 0.45,
                vitaminB12: 3.2,
                folate: 28,
                calcium: 45,
                iron: 0.8,
                magnesium: 35,
                phosphorus: 185,
                potassium: 485,
                sodium: 385,
                zinc: 1.2,
                selenium: 42.5,
                omega3: 0.8,
                omega6: 0.3,
                cholesterol: 55
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Raw fish marinated in citrus with onions and peppers",
            nameFr: "Ceviche",
            nameEs: "Ceviche",
            nameHe: "סביצ'ה",
            notesFr: "Poisson cru mariné aux agrumes avec oignons et poivrons",
            notesEs: "Pescado crudo marinado en cítricos con cebolla y chiles",
            notesHe: "דג נא במרינדת הדרים עם בצל ופלפלים"
        ),
        
        // Elote (Mexican Street Corn)
        FoodItem(
            id: UUID(),
            name: "Elote",
            category: .vegetables,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.2,
                carbohydrates: 28,
                fat: 8.5,
                fiber: 3.8,
                sugar: 8.2,
                vitaminA: 125,
                vitaminC: 8,
                vitaminD: 0.2,
                vitaminE: 0.8,
                vitaminK: 4,
                thiamin: 0.18,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.15,
                vitaminB12: 0.3,
                folate: 45,
                calcium: 125,
                iron: 0.8,
                magnesium: 42,
                phosphorus: 125,
                potassium: 285,
                sodium: 385,
                zinc: 1.2,
                selenium: 2.8,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 15
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Grilled corn with mayo, cheese, chili powder, and lime",
            nameFr: "Elote",
            nameEs: "Elote",
            nameHe: "אלוטה",
            notesFr: "Maïs grillé avec mayo, fromage, poudre de piment et citron vert",
            notesEs: "Maíz asado con mayonesa, queso, chile en polvo y limón",
            notesHe: "תירס צלוי עם מיונז, גבינה, אבקת צ'ילי וליים"
        ),
        
        // Chiles en Nogada
        FoodItem(
            id: UUID(),
            name: "Chiles en Nogada",
            category: .vegetables,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 18.5,
                carbohydrates: 32,
                fat: 22.8,
                fiber: 4.8,
                sugar: 18.5,
                vitaminA: 185,
                vitaminC: 125,
                vitaminD: 0.3,
                vitaminE: 3.8,
                vitaminK: 15,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 3.2,
                vitaminB6: 0.38,
                vitaminB12: 0.8,
                folate: 45,
                calcium: 185,
                iron: 2.8,
                magnesium: 85,
                phosphorus: 225,
                potassium: 485,
                sodium: 385,
                zinc: 2.8,
                selenium: 12.5,
                omega3: 2.8,
                omega6: 8.5,
                cholesterol: 45
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Poblano peppers stuffed with picadillo in walnut cream sauce",
            nameFr: "Chiles en Nogada",
            nameEs: "Chiles en Nogada",
            nameHe: "צ'ילס אן נוגדה",
            notesFr: "Poivrons poblano farcis au picadillo dans une sauce crémeuse aux noix",
            notesEs: "Chiles poblanos rellenos de picadillo en salsa de nuez",
            notesHe: "פלפלים ממולאים פיקדיו ברוטב שמנת אגוזים"
        ),
        
        // Cochinita Pibil
        FoodItem(
            id: UUID(),
            name: "Cochinita Pibil",
            category: .protein,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 25.8,
                carbohydrates: 8,
                fat: 16.8,
                fiber: 1.8,
                sugar: 4.2,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.5,
                vitaminE: 1.2,
                vitaminK: 5,
                thiamin: 0.38,
                riboflavin: 0.22,
                niacin: 7.8,
                vitaminB6: 0.48,
                vitaminB12: 2.2,
                folate: 18,
                calcium: 45,
                iron: 2.8,
                magnesium: 35,
                phosphorus: 225,
                potassium: 385,
                sodium: 585,
                zinc: 3.8,
                selenium: 25.8,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 75
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Yucatecan slow-roasted pork in achiote and citrus marinade",
            nameFr: "Cochinita Pibil",
            nameEs: "Cochinita Pibil",
            nameHe: "קוצ'יניטה פיביל",
            notesFr: "Porc rôti lentement du Yucatan dans une marinade d'achiote et d'agrumes",
            notesEs: "Cerdo asado lentamente yucateco en marinada de achiote y cítricos",
            notesHe: "חזיר צלוי לאט יוקטני במרינדת אצ'יוטה והדרים"
        ),
        
        // Sopa de Tortilla
        FoodItem(
            id: UUID(),
            name: "Sopa de Tortilla",
            category: .grains,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 8.5,
                carbohydrates: 22,
                fat: 8.2,
                fiber: 3.8,
                sugar: 6.8,
                vitaminA: 125,
                vitaminC: 18,
                vitaminD: 0.2,
                vitaminE: 1.8,
                vitaminK: 12,
                thiamin: 0.12,
                riboflavin: 0.15,
                niacin: 2.8,
                vitaminB6: 0.22,
                vitaminB12: 0.3,
                folate: 35,
                calcium: 85,
                iron: 1.8,
                magnesium: 35,
                phosphorus: 125,
                potassium: 385,
                sodium: 685,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.2,
                omega6: 1.2,
                cholesterol: 12
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Tomato-based soup with fried tortilla strips and avocado",
            nameFr: "Soupe de Tortilla",
            nameEs: "Sopa de Tortilla",
            nameHe: "מרק טורטיה",
            notesFr: "Soupe à base de tomate avec des lanières de tortilla frites et avocat",
            notesEs: "Sopa a base de tomate con tiras de tortilla frita y aguacate",
            notesHe: "מרק על בסיס עגבניות עם רצועות טורטיה מטוגנות ואבוקדו"
        ),
        
        // Barbacoa
        FoodItem(
            id: UUID(),
            name: "Barbacoa",
            category: .protein,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 28.5,
                carbohydrates: 3,
                fat: 17.8,
                fiber: 0.5,
                sugar: 1.2,
                vitaminA: 12,
                vitaminC: 2,
                vitaminD: 0.3,
                vitaminE: 0.8,
                vitaminK: 3,
                thiamin: 0.35,
                riboflavin: 0.28,
                niacin: 8.2,
                vitaminB6: 0.45,
                vitaminB12: 3.8,
                folate: 15,
                calcium: 35,
                iron: 3.2,
                magnesium: 28,
                phosphorus: 225,
                potassium: 385,
                sodium: 485,
                zinc: 5.8,
                selenium: 28.5,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Slow-cooked, tender shredded beef or lamb",
            nameFr: "Barbacoa",
            nameEs: "Barbacoa",
            nameHe: "ברבקואה",
            notesFr: "Bœuf ou agneau effiloché cuit lentement et tendre",
            notesEs: "Carne de res o cordero deshebrada cocida lentamente",
            notesHe: "בשר בקר או כבש מפורק ומבושל לאט"
        ),
        
        // Agua Fresca de Jamaica
        FoodItem(
            id: UUID(),
            name: "Agua Fresca de Jamaica",
            category: .beverages,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 45,
                protein: 0.2,
                carbohydrates: 11.5,
                fat: 0.1,
                fiber: 0.8,
                sugar: 10.2,
                vitaminA: 2,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 1,
                thiamin: 0.01,
                riboflavin: 0.02,
                niacin: 0.1,
                vitaminB6: 0.02,
                vitaminB12: 0,
                folate: 2,
                calcium: 15,
                iron: 1.2,
                magnesium: 8,
                phosphorus: 12,
                potassium: 85,
                sodium: 5,
                zinc: 0.1,
                selenium: 0.2,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Refreshing hibiscus flower tea with sugar and lime",
            nameFr: "Agua Fresca de Jamaica",
            nameEs: "Agua Fresca de Jamaica",
            nameHe: "אגואה פרסקה דה חמייקה",
            notesFr: "Thé rafraîchissant aux fleurs d'hibiscus avec sucre et citron vert",
            notesEs: "Té refrescante de flor de jamaica con azúcar y limón",
            notesHe: "תה מרענן מפרחי היביסקוס עם סוכר וליים"
        ),
        
        // Tres Leches Cake
        FoodItem(
            id: UUID(),
            name: "Tres Leches Cake",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 6.8,
                carbohydrates: 38,
                fat: 12.5,
                fiber: 0.8,
                sugar: 32.5,
                vitaminA: 125,
                vitaminC: 1,
                vitaminD: 0.8,
                vitaminE: 0.8,
                vitaminK: 2,
                thiamin: 0.08,
                riboflavin: 0.22,
                niacin: 1.2,
                vitaminB6: 0.05,
                vitaminB12: 0.8,
                folate: 18,
                calcium: 185,
                iron: 0.8,
                magnesium: 18,
                phosphorus: 145,
                potassium: 185,
                sodium: 185,
                zinc: 0.8,
                selenium: 8.5,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Sponge cake soaked in three types of milk",
            nameFr: "Gâteau Tres Leches",
            nameEs: "Pastel de Tres Leches",
            nameHe: "עוגת טרס לצ'ס",
            notesFr: "Gâteau éponge imbibé de trois types de lait",
            notesEs: "Bizcocho empapado en tres tipos de leche",
            notesHe: "עוגת ספוג ספוגה בשלושה סוגי חלב"
        ),
        
        // Flan
        FoodItem(
            id: UUID(),
            name: "Flan",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 5.8,
                carbohydrates: 32,
                fat: 8.5,
                fiber: 0.2,
                sugar: 31.5,
                vitaminA: 85,
                vitaminC: 1,
                vitaminD: 0.5,
                vitaminE: 0.5,
                vitaminK: 1,
                thiamin: 0.05,
                riboflavin: 0.18,
                niacin: 0.8,
                vitaminB6: 0.08,
                vitaminB12: 0.6,
                folate: 12,
                calcium: 145,
                iron: 0.5,
                magnesium: 15,
                phosphorus: 125,
                potassium: 145,
                sodium: 85,
                zinc: 0.6,
                selenium: 8.2,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 125
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Creamy caramel custard dessert",
            nameFr: "Flan",
            nameEs: "Flan",
            nameHe: "פלאן",
            notesFr: "Dessert crémeux à la crème caramel",
            notesEs: "Postre cremoso de natilla con caramelo",
            notesHe: "קינוח קרם קרמל קרמי"
        ),
        
        // Horchata
        FoodItem(
            id: UUID(),
            name: "Horchata",
            category: .beverages,
            cuisineType: .mexican,
            nutritionalInfo: NutritionalInfo(
                calories: 125,
                protein: 2.8,
                carbohydrates: 22,
                fat: 3.5,
                fiber: 0.8,
                sugar: 18.5,
                vitaminA: 25,
                vitaminC: 2,
                vitaminD: 0.3,
                vitaminE: 1.2,
                vitaminK: 2,
                thiamin: 0.08,
                riboflavin: 0.12,
                niacin: 0.8,
                vitaminB6: 0.05,
                vitaminB12: 0.2,
                folate: 8,
                calcium: 125,
                iron: 0.8,
                magnesium: 35,
                phosphorus: 85,
                potassium: 185,
                sodium: 45,
                zinc: 0.5,
                selenium: 2.8,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 8
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Sweet rice and cinnamon drink",
            nameFr: "Horchata",
            nameEs: "Horchata",
            nameHe: "הורצ'טה",
            notesFr: "Boisson sucrée au riz et à la cannelle",
            notesEs: "Bebida dulce de arroz y canela",
            notesHe: "משקה מתוק מאורז וקינמון"
        )
    ]
} 