import Foundation

struct NewFoodItems {
    static let foods: [FoodItem] = [
        // Oatmeal
        FoodItem(
            id: UUID(),
            name: "Oatmeal",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 150,
                protein: 5,
                carbohydrates: 27,
                fat: 3,
                fiber: 4,
                sugar: 1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 20,
                calcium: 20,
                iron: 2,
                magnesium: 60,
                phosphorus: 150,
                potassium: 150,
                sodium: 0,
                zinc: 1.5,
                selenium: 10,
                omega3: 0.1,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked oatmeal, plain. Low GI (55). Contains avenanthramides and beta-glucan."
        ),
        
        // Cheerios
        FoodItem(
            id: UUID(),
            name: "Cheerios",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 100,
                protein: 3,
                carbohydrates: 20,
                fat: 2,
                fiber: 3,
                sugar: 1,
                vitaminA: 500,
                vitaminC: 12,
                vitaminD: 40,
                vitaminE: 1.5,
                vitaminK: 0,
                thiamin: 0.3,
                riboflavin: 0.3,
                niacin: 4,
                vitaminB6: 0.4,
                vitaminB12: 1.2,
                folate: 100,
                calcium: 100,
                iron: 4.5,
                magnesium: 40,
                phosphorus: 100,
                potassium: 150,
                sodium: 150,
                zinc: 2,
                selenium: 5,
                omega3: 0,
                omega6: 0.5,
                cholesterol: 0
            ),
            servingSize: 30,
            servingUnit: "g",
            isCustom: false,
            notes: "Cereal with medium GI (65). Contains avenanthramides and beta-glucan. 0.3g saturated fat, 1g unsaturated fat."
        ),
        
        // Whole Wheat Bread
        FoodItem(
            id: UUID(),
            name: "Whole Wheat Bread",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 80,
                protein: 4,
                carbohydrates: 15,
                fat: 1,
                fiber: 2,
                sugar: 1.5,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 1,
                thiamin: 0.1,
                riboflavin: 0.05,
                niacin: 1.5,
                vitaminB6: 0.05,
                vitaminB12: 0,
                folate: 20,
                calcium: 20,
                iron: 1,
                magnesium: 25,
                phosphorus: 70,
                potassium: 80,
                sodium: 160,
                zinc: 0.5,
                selenium: 10,
                omega3: 0,
                omega6: 0.4,
                cholesterol: 0
            ),
            servingSize: 30,
            servingUnit: "g",
            isCustom: false,
            notes: "One slice of whole wheat bread. Medium-high GI (70). Contains ferulic acid and lignans. 0.2g saturated fat, 0.4g unsaturated fat."
        ),
        
        // Brown Rice
        FoodItem(
            id: UUID(),
            name: "Brown Rice",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 215,
                protein: 5,
                carbohydrates: 45,
                fat: 1.7,
                fiber: 3.5,
                sugar: 0.5,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.5,
                thiamin: 0.2,
                riboflavin: 0.05,
                niacin: 3,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 8,
                calcium: 10,
                iron: 1,
                magnesium: 86,
                phosphorus: 150,
                potassium: 150,
                sodium: 10,
                zinc: 1.2,
                selenium: 15,
                omega3: 0,
                omega6: 0.6,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked brown rice. Medium GI (50). Contains gamma-oryzanol and phenolic acids. 0.3g saturated fat, 1.3g unsaturated fat."
        ),
        
        // Sweet Potato
        FoodItem(
            id: UUID(),
            name: "Sweet Potato",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 110,
                protein: 2,
                carbohydrates: 27,
                fat: 0.2,
                fiber: 3.8,
                sugar: 6,
                vitaminA: 14200,
                vitaminC: 20,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 2.3,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 11,
                calcium: 38,
                iron: 0.7,
                magnesium: 27,
                phosphorus: 54,
                potassium: 448,
                sodium: 36,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Baked sweet potato. Low-medium GI (44). Rich in beta-carotene and carotenoids."
        ),
        
        // Broccoli - updated entry
        FoodItem(
            id: UUID(),
            name: "Broccoli",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 50,
                protein: 4,
                carbohydrates: 10,
                fat: 0.5,
                fiber: 5,
                sugar: 2,
                vitaminA: 623,
                vitaminC: 89.2,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 101.6,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.6,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 63,
                calcium: 47,
                iron: 0.7,
                magnesium: 21,
                phosphorus: 66,
                potassium: 316,
                sodium: 33,
                zinc: 0.4,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked broccoli. Very low GI (10). Contains sulforaphane and glucosinolates."
        ),
        
        // Spinach
        FoodItem(
            id: UUID(),
            name: "Spinach",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 40,
                protein: 5,
                carbohydrates: 7,
                fat: 0.5,
                fiber: 4,
                sugar: 0.5,
                vitaminA: 9400,
                vitaminC: 28,
                vitaminD: 0,
                vitaminE: 2,
                vitaminK: 483,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 0.7,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 194,
                calcium: 99,
                iron: 2.7,
                magnesium: 79,
                phosphorus: 49,
                potassium: 558,
                sodium: 79,
                zinc: 0.5,
                selenium: 1,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked spinach. Very low GI (10). Rich in lutein, zeaxanthin, and carotenoids."
        ),
        
        // Blueberries
        FoodItem(
            id: UUID(),
            name: "Blueberries",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 84,
                protein: 1,
                carbohydrates: 21,
                fat: 0.5,
                fiber: 3.6,
                sugar: 15,
                vitaminA: 54,
                vitaminC: 9.7,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 19.3,
                thiamin: 0.04,
                riboflavin: 0.04,
                niacin: 0.4,
                vitaminB6: 0.05,
                vitaminB12: 0,
                folate: 6,
                calcium: 6,
                iron: 0.3,
                magnesium: 6,
                phosphorus: 12,
                potassium: 77,
                sodium: 1,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh blueberries. Medium GI (53). Rich in anthocyanins."
        ),
        
        // Almonds
        FoodItem(
            id: UUID(),
            name: "Almonds",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 160,
                protein: 6,
                carbohydrates: 6,
                fat: 14,
                fiber: 4,
                sugar: 1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 7.3,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.3,
                niacin: 1.1,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 14,
                calcium: 70,
                iron: 1.1,
                magnesium: 77,
                phosphorus: 136,
                potassium: 208,
                sodium: 1,
                zinc: 0.9,
                selenium: 1.2,
                omega3: 0,
                omega6: 3.5,
                cholesterol: 0
            ),
            servingSize: 30,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw almonds (about 23 nuts). Zero GI. Fat breakdown: 9g monounsaturated, 4g polyunsaturated, 1g saturated. Rich in vitamin E and polyphenols."
        ),
        
        // Olive Oil
        FoodItem(
            id: UUID(),
            name: "Olive Oil",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 120,
                protein: 0,
                carbohydrates: 0,
                fat: 14,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 1.9,
                vitaminK: 8.1,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 0,
                phosphorus: 0,
                potassium: 0,
                sodium: 0,
                zinc: 0,
                selenium: 0,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 15,
            servingUnit: "ml",
            isCustom: false,
            notes: "Extra virgin olive oil (1 tbsp). Zero GI. Fat breakdown: 10g monounsaturated, 2g saturated, 2g polyunsaturated. Contains oleocanthal and polyphenols."
        ),
        
        // Greek Yogurt
        FoodItem(
            id: UUID(),
            name: "Greek Yogurt",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 150,
                protein: 15,
                carbohydrates: 8,
                fat: 4,
                fiber: 0,
                sugar: 6,
                vitaminA: 20,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.2,
                thiamin: 0.1,
                riboflavin: 0.3,
                niacin: 0.2,
                vitaminB6: 0.1,
                vitaminB12: 0.6,
                folate: 12,
                calcium: 200,
                iron: 0,
                magnesium: 19,
                phosphorus: 150,
                potassium: 240,
                sodium: 70,
                zinc: 1,
                selenium: 8,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 15
            ),
            servingSize: 170,
            servingUnit: "g",
            isCustom: false,
            notes: "Plain Greek yogurt (container). Low GI (30). Fat breakdown: 2.5g saturated, 1.5g unsaturated. Contains vitamins C, E and probiotics."
        ),
        
        // Egg
        FoodItem(
            id: UUID(),
            name: "Egg",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 72,
                protein: 6,
                carbohydrates: 0.5,
                fat: 5,
                fiber: 0,
                sugar: 0.5,
                vitaminA: 270,
                vitaminC: 0,
                vitaminD: 41,
                vitaminE: 1,
                vitaminK: 0.3,
                thiamin: 0.04,
                riboflavin: 0.5,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 0.6,
                folate: 22,
                calcium: 28,
                iron: 0.9,
                magnesium: 6,
                phosphorus: 86,
                potassium: 69,
                sodium: 71,
                zinc: 0.6,
                selenium: 15.4,
                omega3: 0.1,
                omega6: 0.7,
                cholesterol: 186
            ),
            servingSize: 50,
            servingUnit: "g",
            isCustom: false,
            notes: "One large egg. Zero GI. Fat breakdown: 1.6g saturated, 2.7g unsaturated. Contains lutein, zeaxanthin, and choline."
        ),
        
        // Chicken Breast
        FoodItem(
            id: UUID(),
            name: "Chicken Breast",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 140,
                protein: 26,
                carbohydrates: 0,
                fat: 3,
                fiber: 0,
                sugar: 0,
                vitaminA: 20,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 0.1,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 11.8,
                vitaminB6: 0.5,
                vitaminB12: 0.3,
                folate: 4,
                calcium: 15,
                iron: 1,
                magnesium: 28,
                phosphorus: 210,
                potassium: 255,
                sodium: 65,
                zinc: 0.9,
                selenium: 23,
                omega3: 0,
                omega6: 0.4,
                cholesterol: 75
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Skinless, boneless chicken breast. Zero GI. Fat breakdown: 0.9g saturated, 1.7g unsaturated. Contains selenium and carnosine."
        ),
        
        // Salmon
        FoodItem(
            id: UUID(),
            name: "Salmon",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 175,
                protein: 17,
                carbohydrates: 0,
                fat: 11,
                fiber: 0,
                sugar: 0,
                vitaminA: 50,
                vitaminC: 3.9,
                vitaminD: 526,
                vitaminE: 2.9,
                vitaminK: 0.1,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 8.5,
                vitaminB6: 0.5,
                vitaminB12: 2.8,
                folate: 26,
                calcium: 12,
                iron: 0.8,
                magnesium: 29,
                phosphorus: 218,
                potassium: 384,
                sodium: 55,
                zinc: 0.6,
                selenium: 31,
                omega3: 2.2,
                omega6: 0.3,
                cholesterol: 54
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Wild-caught salmon fillet. Zero GI. Fat breakdown: 2g saturated, 7g unsaturated. Contains astaxanthin and omega-3 fatty acids."
        ),
        
        // Black Beans
        FoodItem(
            id: UUID(),
            name: "Black Beans",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 110,
                protein: 7,
                carbohydrates: 20,
                fat: 0.5,
                fiber: 7.5,
                sugar: 0.5,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 2.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 0.4,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 128,
                calcium: 23,
                iron: 1.8,
                magnesium: 60,
                phosphorus: 120,
                potassium: 305,
                sodium: 1,
                zinc: 0.9,
                selenium: 1.5,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked black beans. Low GI (30). Contains anthocyanins and flavonoids."
        ),
        
        // Ensure Original
        FoodItem(
            id: UUID(),
            name: "Ensure Original",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 9,
                carbohydrates: 33,
                fat: 6,
                fiber: 1,
                sugar: 15,
                vitaminA: 760,
                vitaminC: 30,
                vitaminD: 100,
                vitaminE: 10,
                vitaminK: 20,
                thiamin: 0.75,
                riboflavin: 0.85,
                niacin: 5,
                vitaminB6: 1,
                vitaminB12: 3,
                folate: 200,
                calcium: 300,
                iron: 4.5,
                magnesium: 100,
                phosphorus: 250,
                potassium: 370,
                sodium: 200,
                zinc: 3.8,
                selenium: 15,
                omega3: 0.2,
                omega6: 1.5,
                cholesterol: 5
            ),
            servingSize: 237,
            servingUnit: "ml",
            isCustom: false,
            notes: "Nutritional shake (1 bottle). Medium-high GI (65). Fat breakdown: 1g saturated, 5g unsaturated. Contains vitamins C, E."
        ),
        
        // Canned Tuna
        FoodItem(
            id: UUID(),
            name: "Canned Tuna",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 100,
                protein: 22,
                carbohydrates: 0,
                fat: 1,
                fiber: 0,
                sugar: 0,
                vitaminA: 15,
                vitaminC: 0,
                vitaminD: 150,
                vitaminE: 0.5,
                vitaminK: 0.1,
                thiamin: 0.05,
                riboflavin: 0.05,
                niacin: 10,
                vitaminB6: 0.3,
                vitaminB12: 1.8,
                folate: 2,
                calcium: 10,
                iron: 1.3,
                magnesium: 28,
                phosphorus: 200,
                potassium: 200,
                sodium: 300,
                zinc: 0.9,
                selenium: 60,
                omega3: 0.7,
                omega6: 0.1,
                cholesterol: 40
            ),
            servingSize: 85,
            servingUnit: "g",
            isCustom: false,
            notes: "Light tuna in water (1 can). Zero GI. Fat breakdown: 0.2g saturated, 0.8g unsaturated. Contains selenium."
        ),
        
        // Cottage Cheese
        FoodItem(
            id: UUID(),
            name: "Cottage Cheese",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 90,
                protein: 12,
                carbohydrates: 5,
                fat: 2,
                fiber: 0,
                sugar: 5,
                vitaminA: 102,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.2,
                thiamin: 0.03,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 0.5,
                folate: 12,
                calcium: 80,
                iron: 0.1,
                magnesium: 8,
                phosphorus: 150,
                potassium: 105,
                sodium: 380,
                zinc: 0.5,
                selenium: 10,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 10
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Low-fat cottage cheese. Low GI (30). Fat breakdown: 1.3g saturated, 0.7g unsaturated. Contains vitamin A and selenium."
        ),
        
        // Chicken Noodle Soup
        FoodItem(
            id: UUID(),
            name: "Chicken Noodle Soup",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 60,
                protein: 3,
                carbohydrates: 8,
                fat: 2,
                fiber: 0.5,
                sugar: 1,
                vitaminA: 300,
                vitaminC: 0.5,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 0.5,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1,
                vitaminB6: 0.1,
                vitaminB12: 0.1,
                folate: 10,
                calcium: 10,
                iron: 0.5,
                magnesium: 5,
                phosphorus: 35,
                potassium: 50,
                sodium: 800,
                zinc: 0.3,
                selenium: 3,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 5
            ),
            servingSize: 240,
            servingUnit: "ml",
            isCustom: false,
            notes: "Canned soup (1 cup). Medium GI (60). Fat breakdown: 0.5g saturated, 1.5g unsaturated. Contains small amounts of vitamin A."
        ),
        
        // Banana
        FoodItem(
            id: UUID(),
            name: "Banana",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 105,
                protein: 1.3,
                carbohydrates: 27,
                fat: 0.4,
                fiber: 3,
                sugar: 14,
                vitaminA: 64,
                vitaminC: 10,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.5,
                thiamin: 0.03,
                riboflavin: 0.07,
                niacin: 0.7,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 24,
                calcium: 5,
                iron: 0.3,
                magnesium: 32,
                phosphorus: 26,
                potassium: 422,
                sodium: 1,
                zinc: 0.2,
                selenium: 1,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: false,
            notes: "Medium banana. Medium GI (51). Contains dopamine, catechins, and polyphenols."
        )
    ]
} 