import Foundation

struct PastaFoodItems {
    static let foods: [FoodItem] = [
        // Spaghetti with Marinara Sauce
        FoodItem(
            id: UUID(),
            name: "Spaghetti with Marinara Sauce",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 320,
                protein: 12,
                carbohydrates: 64,
                fat: 3,
                fiber: 4,
                sugar: 8,
                vitaminA: 600,
                vitaminC: 13.5,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 10,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 2,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 40,
                calcium: 60,
                iron: 1.2,
                magnesium: 40,
                phosphorus: 100,
                potassium: 400,
                sodium: 590,
                zinc: 1,
                selenium: 10,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Low in fat and relatively low in calories. Good source of complex carbohydrates for energy. Tomato sauce provides lycopene, an antioxidant.",
            nameFr: "Spaghetti à la sauce marinara",
            nameEs: "Espaguetis con salsa marinara",
            nameHe: "ספגטי ברוטב מרינרה",
            notesFr: "Faible en matières grasses et en calories. Bonne source de glucides complexes. La sauce tomate apporte du lycopène, un antioxydant.",
            notesEs: "Bajo en grasa y relativamente bajo en calorías. Buena fuente de carbohidratos complejos. La salsa de tomate aporta licopeno, un antioxidante.",
            notesHe: "דל שומן וקלוריות יחסית. מקור טוב לפחמימות מורכבות. רוטב העגבניות מספק ליקופן, נוגד חמצון."
        ),

        // Fettuccine Alfredo
        FoodItem(
            id: UUID(),
            name: "Fettuccine Alfredo",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 670,
                protein: 19,
                carbohydrates: 50,
                fat: 43,
                fiber: 2,
                sugar: 3,
                vitaminA: 1500,
                vitaminC: 0,
                vitaminD: 20,
                vitaminE: 2,
                vitaminK: 5,
                thiamin: 0.3,
                riboflavin: 0.3,
                niacin: 2,
                vitaminB6: 0.1,
                vitaminB12: 0.5,
                folate: 20,
                calcium: 300,
                iron: 1,
                magnesium: 30,
                phosphorus: 200,
                potassium: 200,
                sodium: 950,
                zinc: 1.5,
                selenium: 15,
                omega3: 0.2,
                omega6: 1,
                cholesterol: 80
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Good source of calcium from cream and cheese. Very high in calories and saturated fat. Can contribute to elevated cholesterol levels.",
            nameFr: "Fettuccine Alfredo",
            nameEs: "Fettuccine Alfredo",
            nameHe: "פטוצ'יני אלפרדו",
            notesFr: "Bonne source de calcium grâce à la crème et au fromage. Très riche en calories et en graisses saturées. Peut augmenter le cholestérol.",
            notesEs: "Buena fuente de calcio de la crema y el queso. Muy alto en calorías y grasas saturadas. Puede elevar el colesterol.",
            notesHe: "מקור טוב לסידן מקרם וגבינה. עתיר קלוריות ושומן רווי. עלול להעלות את רמות הכולסטרול."
        ),

        // Whole Wheat Pasta Primavera
        FoodItem(
            id: UUID(),
            name: "Whole Wheat Pasta Primavera",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 350,
                protein: 14,
                carbohydrates: 60,
                fat: 8,
                fiber: 9,
                sugar: 6,
                vitaminA: 1750,
                vitaminC: 40.5,
                vitaminD: 0,
                vitaminE: 3,
                vitaminK: 30,
                thiamin: 0.4,
                riboflavin: 0.3,
                niacin: 3,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 80,
                calcium: 100,
                iron: 1.6,
                magnesium: 80,
                phosphorus: 150,
                potassium: 500,
                sodium: 400,
                zinc: 1.5,
                selenium: 20,
                omega3: 0.3,
                omega6: 1,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Rich in fiber from whole wheat pasta and vegetables. Excellent source of vitamins A and C from mixed vegetables. High in antioxidants and phytonutrients.",
            nameFr: "Pâtes complètes Primavera",
            nameEs: "Pasta integral Primavera",
            nameHe: "פסטה מחיטה מלאה פרימברה",
            notesFr: "Riche en fibres grâce aux pâtes complètes et légumes. Excellente source de vitamines A et C. Riche en antioxydants et phytonutriments.",
            notesEs: "Rica en fibra de pasta integral y verduras. Excelente fuente de vitaminas A y C. Alta en antioxidantes y fitonutrientes.",
            notesHe: "עשירה בסיבים תזונתיים מחיטה מלאה וירקות. מקור מצוין לוויטמינים A ו־C. עשירה בנוגדי חמצון ופיטונוטריאנטים."
        ),

        // Shrimp Scampi with Linguine
        FoodItem(
            id: UUID(),
            name: "Shrimp Scampi with Linguine",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 440,
                protein: 24,
                carbohydrates: 52,
                fat: 16,
                fiber: 2,
                sugar: 2,
                vitaminA: 300,
                vitaminC: 5,
                vitaminD: 40,
                vitaminE: 2,
                vitaminK: 5,
                thiamin: 0.2,
                riboflavin: 0.2,
                niacin: 3,
                vitaminB6: 0.3,
                vitaminB12: 1.2,
                folate: 30,
                calcium: 80,
                iron: 1.2,
                magnesium: 50,
                phosphorus: 200,
                potassium: 300,
                sodium: 800,
                zinc: 1.5,
                selenium: 41.25,
                omega3: 0.5,
                omega6: 0.8,
                cholesterol: 150
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Excellent source of lean protein from shrimp. Rich in selenium and vitamin B12. Contains heart-healthy garlic. Good source of omega-3 fatty acids.",
            nameFr: "Scampi aux crevettes et linguine",
            nameEs: "Scampi de camarones con linguini",
            nameHe: "שימפ סקאמפי עם לינגוויני",
            notesFr: "Excellente source de protéines maigres des crevettes. Riche en sélénium et vitamine B12. Contient de l'ail bon pour le cœur. Bonne source d'oméga-3.",
            notesEs: "Excelente fuente de proteína magra de camarones. Rico en selenio y vitamina B12. Contiene ajo saludable para el corazón. Buena fuente de omega-3.",
            notesHe: "מקור מצוין לחלבון רזה מהשרימפס. עשיר בסלניום ובוויטמין B12. מכיל שום בריא ללב. מקור טוב לחומצות שומן אומגה 3."
        ),

        // Pesto Pasta with Pine Nuts
        FoodItem(
            id: UUID(),
            name: "Pesto Pasta with Pine Nuts",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 490,
                protein: 15,
                carbohydrates: 52,
                fat: 25,
                fiber: 3,
                sugar: 3,
                vitaminA: 500,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 3.75,
                vitaminK: 132,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 2,
                vitaminB6: 0.2,
                vitaminB12: 0.2,
                folate: 40,
                calcium: 150,
                iron: 2,
                magnesium: 80,
                phosphorus: 200,
                potassium: 300,
                sodium: 600,
                zinc: 2,
                selenium: 24.75,
                omega3: 1,
                omega6: 5,
                cholesterol: 10
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Contains healthy fats from olive oil, pine nuts, and sometimes walnuts. Rich in antioxidants from basil and olive oil. Good source of vitamin K for bone health.",
            nameFr: "Pâtes au pesto avec pignons de pin",
            nameEs: "Pasta al pesto con piñones",
            nameHe: "פסטו פסטה עם אגוזי אורן",
            notesFr: "Contient des graisses saines de l'huile d'olive, des pignons et parfois des noix. Riche en antioxydants. Bonne source de vitamine K pour les os.",
            notesEs: "Contiene grasas saludables de aceite de oliva, piñones y a veces nueces. Rica en antioxidantes. Buena fuente de vitamina K para los huesos.",
            notesHe: "מכילה שומנים בריאים משמן זית, אגוזי אורן ולעיתים גם אגוזים. עשירה בנוגדי חמצון. מקור טוב לוויטמין K לבריאות העצם."
        )
    ]
}
