import Foundation

struct RegionalFoodData {
    // MARK: - North American Foods
    static let northAmericanFoods: [FoodItem] = [
        // Grains
        FoodItem(
            id: UUID(),
            name: "Oatmeal",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 150,
                protein: 5,
                carbohydrates: 27,
                fat: 3,
                fiber: 4,
                sugar: 1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 20,
                calcium: 20,
                iron: 2,
                magnesium: 60,
                phosphorus: 150,
                potassium: 150,
                sodium: 0,
                zinc: 1.5,
                selenium: 10,
                omega3: 0.1,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked oatmeal, plain"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Whole-Wheat Bread",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 247,
                protein: 13,
                carbohydrates: 41,
                fat: 3.2,
                fiber: 7,
                sugar: 6,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 1.2,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 4,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 40,
                calcium: 100,
                iron: 3.6,
                magnesium: 80,
                phosphorus: 200,
                potassium: 250,
                sodium: 400,
                zinc: 2,
                selenium: 30,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Whole-wheat bread, sliced"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Brown Rice",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 112,
                protein: 2.6,
                carbohydrates: 23.5,
                fat: 0.9,
                fiber: 1.8,
                sugar: 0.4,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 2.6,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 8,
                calcium: 10,
                iron: 0.4,
                magnesium: 43,
                phosphorus: 83,
                potassium: 86,
                sodium: 5,
                zinc: 0.6,
                selenium: 15,
                omega3: 0.1,
                omega6: 0.3,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked brown rice"
        ),
        
        // Vegetables
        FoodItem(
            id: UUID(),
            name: "Broccoli",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 34,
                protein: 2.8,
                carbohydrates: 6.6,
                fat: 0.4,
                fiber: 2.6,
                sugar: 1.7,
                vitaminA: 623,
                vitaminC: 89.2,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 101.6,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.6,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 63,
                calcium: 47,
                iron: 0.7,
                magnesium: 21,
                phosphorus: 66,
                potassium: 316,
                sodium: 33,
                zinc: 0.4,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw broccoli florets"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Carrots",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 41,
                protein: 0.9,
                carbohydrates: 9.6,
                fat: 0.2,
                fiber: 2.8,
                sugar: 4.7,
                vitaminA: 835,
                vitaminC: 5.9,
                vitaminD: 0,
                vitaminE: 0.7,
                vitaminK: 13.2,
                thiamin: 0.07,
                riboflavin: 0.06,
                niacin: 0.9,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 19,
                calcium: 33,
                iron: 0.3,
                magnesium: 12,
                phosphorus: 35,
                potassium: 320,
                sodium: 69,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw carrots"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Spinach",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 23,
                protein: 2.9,
                carbohydrates: 3.6,
                fat: 0.4,
                fiber: 2.2,
                sugar: 0.4,
                vitaminA: 469,
                vitaminC: 28.1,
                vitaminD: 0,
                vitaminE: 2,
                vitaminK: 483,
                thiamin: 0.08,
                riboflavin: 0.19,
                niacin: 0.7,
                vitaminB6: 0.19,
                vitaminB12: 0,
                folate: 194,
                calcium: 99,
                iron: 2.7,
                magnesium: 79,
                phosphorus: 49,
                potassium: 558,
                sodium: 79,
                zinc: 0.5,
                selenium: 1,
                omega3: 0.14,
                omega6: 0.03,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw spinach leaves"
        ),
        
        // Fruits
        FoodItem(
            id: UUID(),
            name: "Apples",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 95,
                protein: 0.5,
                carbohydrates: 25,
                fat: 0.3,
                fiber: 4.5,
                sugar: 19,
                vitaminA: 54,
                vitaminC: 8.4,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 2.2,
                thiamin: 0.02,
                riboflavin: 0.03,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 5,
                calcium: 11,
                iron: 0.2,
                magnesium: 9,
                phosphorus: 20,
                potassium: 195,
                sodium: 2,
                zinc: 0.1,
                selenium: 0,
                omega3: 0.01,
                omega6: 0.04,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Medium-sized apple with skin"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Blueberries",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 57,
                protein: 0.7,
                carbohydrates: 14.5,
                fat: 0.3,
                fiber: 2.4,
                sugar: 10,
                vitaminA: 54,
                vitaminC: 9.7,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 19.3,
                thiamin: 0.04,
                riboflavin: 0.04,
                niacin: 0.4,
                vitaminB6: 0.05,
                vitaminB12: 0,
                folate: 6,
                calcium: 6,
                iron: 0.3,
                magnesium: 6,
                phosphorus: 12,
                potassium: 77,
                sodium: 1,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0.06,
                omega6: 0.09,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh blueberries"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Bananas",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 105,
                protein: 1.3,
                carbohydrates: 27,
                fat: 0.3,
                fiber: 3.1,
                sugar: 14,
                vitaminA: 64,
                vitaminC: 10.3,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.5,
                thiamin: 0.03,
                riboflavin: 0.1,
                niacin: 0.8,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 24,
                calcium: 6,
                iron: 0.3,
                magnesium: 32,
                phosphorus: 26,
                potassium: 422,
                sodium: 1,
                zinc: 0.2,
                selenium: 1,
                omega3: 0.03,
                omega6: 0.05,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Medium-sized banana"
        ),
        
        // Protein
        FoodItem(
            id: UUID(),
            name: "Skinless Chicken Breast",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 31,
                carbohydrates: 0,
                fat: 3.6,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 14,
                vitaminB6: 0.6,
                vitaminB12: 0.3,
                folate: 4,
                calcium: 15,
                iron: 1,
                magnesium: 30,
                phosphorus: 230,
                potassium: 300,
                sodium: 70,
                zinc: 1,
                selenium: 25,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 85
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked, skinless chicken breast"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Salmon",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 208,
                protein: 22,
                carbohydrates: 0,
                fat: 13,
                fiber: 0,
                sugar: 0,
                vitaminA: 149,
                vitaminC: 3.9,
                vitaminD: 13.1,
                vitaminE: 3.55,
                vitaminK: 0.7,
                thiamin: 0.18,
                riboflavin: 0.38,
                niacin: 8.5,
                vitaminB6: 0.6,
                vitaminB12: 2.6,
                folate: 25,
                calcium: 9,
                iron: 0.3,
                magnesium: 27,
                phosphorus: 240,
                potassium: 363,
                sodium: 59,
                zinc: 0.6,
                selenium: 36.5,
                omega3: 2.3,
                omega6: 0.17,
                cholesterol: 55
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked Atlantic salmon"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Black Beans",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 132,
                protein: 8.9,
                carbohydrates: 23.7,
                fat: 0.5,
                fiber: 8.7,
                sugar: 0.3,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 140,
                calcium: 27,
                iron: 2.1,
                magnesium: 70,
                phosphorus: 140,
                potassium: 355,
                sodium: 1,
                zinc: 1.1,
                selenium: 1.2,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked black beans"
        ),
        
        // Dairy
        FoodItem(
            id: UUID(),
            name: "Low-Fat Milk",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 42,
                protein: 3.4,
                carbohydrates: 5,
                fat: 1,
                fiber: 0,
                sugar: 5,
                vitaminA: 46,
                vitaminC: 1,
                vitaminD: 1.2,
                vitaminE: 0.1,
                vitaminK: 0.1,
                thiamin: 0.04,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.5,
                folate: 5,
                calcium: 125,
                iron: 0.1,
                magnesium: 11,
                phosphorus: 95,
                potassium: 150,
                sodium: 42,
                zinc: 0.4,
                selenium: 3.3,
                omega3: 0.01,
                omega6: 0.02,
                cholesterol: 5
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "1% low-fat milk"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Greek Yogurt",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 59,
                protein: 10.3,
                carbohydrates: 3.6,
                fat: 0.4,
                fiber: 0,
                sugar: 3.6,
                vitaminA: 4,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.03,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.2,
                folate: 7,
                calcium: 111,
                iron: 0.1,
                magnesium: 11,
                phosphorus: 135,
                potassium: 141,
                sodium: 36,
                zinc: 0.5,
                selenium: 9.7,
                omega3: 0.01,
                omega6: 0.01,
                cholesterol: 5
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Plain, non-fat Greek yogurt"
        ),
        
        // Fats
        FoodItem(
            id: UUID(),
            name: "Olive Oil",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 884,
                protein: 0,
                carbohydrates: 0,
                fat: 100,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 14.4,
                vitaminK: 60.2,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 1,
                iron: 0.6,
                magnesium: 0,
                phosphorus: 0,
                potassium: 1,
                sodium: 2,
                zinc: 0,
                selenium: 0,
                omega3: 0.8,
                omega6: 9.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Extra virgin olive oil"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Almonds",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 579,
                protein: 21.2,
                carbohydrates: 21.7,
                fat: 49.9,
                fiber: 12.5,
                sugar: 4.4,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 25.6,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 1.1,
                niacin: 3.6,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 44,
                calcium: 269,
                iron: 3.7,
                magnesium: 270,
                phosphorus: 481,
                potassium: 733,
                sodium: 1,
                zinc: 3.1,
                selenium: 4.1,
                omega3: 0.1,
                omega6: 12.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw almonds"
        ),
        
        // Beverages
        FoodItem(
            id: UUID(),
            name: "Plain Water",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 0,
                protein: 0,
                carbohydrates: 0,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0,
                magnesium: 0,
                phosphorus: 0,
                potassium: 0,
                sodium: 0,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Filtered water"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Green Tea",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 1,
                protein: 0.2,
                carbohydrates: 0.2,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0.1,
                niacin: 0.1,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 2,
                phosphorus: 0,
                potassium: 27,
                sodium: 1,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Brewed green tea"
        ),
        
        // Snacks
        FoodItem(
            id: UUID(),
            name: "Whole-Grain Crackers with Hummus",
            category: .snacks,
            nutritionalInfo: NutritionalInfo(
                calories: 180,
                protein: 5,
                carbohydrates: 25,
                fat: 7,
                fiber: 4,
                sugar: 2,
                vitaminA: 0,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 1,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 20,
                calcium: 30,
                iron: 1.5,
                magnesium: 40,
                phosphorus: 100,
                potassium: 150,
                sodium: 300,
                zinc: 1,
                selenium: 10,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Whole-grain crackers with hummus spread"
        ),
        
        // Other
        FoodItem(
            id: UUID(),
            name: "Fortified Multigrain Cereal",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 350,
                protein: 10,
                carbohydrates: 75,
                fat: 2,
                fiber: 8,
                sugar: 12,
                vitaminA: 500,
                vitaminC: 60,
                vitaminD: 3,
                vitaminE: 20,
                vitaminK: 0,
                thiamin: 1.5,
                riboflavin: 1.7,
                niacin: 20,
                vitaminB6: 2,
                vitaminB12: 6,
                folate: 400,
                calcium: 1000,
                iron: 18,
                magnesium: 100,
                phosphorus: 300,
                potassium: 300,
                sodium: 300,
                zinc: 15,
                selenium: 20,
                omega3: 0.5,
                omega6: 2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fortified multigrain breakfast cereal"
        )
    ]
    
    // MARK: - South American Foods
    static let southAmericanFoods: [FoodItem] = [
        // Grains
        FoodItem(
            id: UUID(),
            name: "White Rice",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 130,
                protein: 2.7,
                carbohydrates: 28,
                fat: 0.3,
                fiber: 0.4,
                sugar: 0.1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0,
                niacin: 1.6,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 8,
                calcium: 10,
                iron: 0.2,
                magnesium: 12,
                phosphorus: 43,
                potassium: 35,
                sodium: 1,
                zinc: 0.5,
                selenium: 15,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked white rice"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Quinoa",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 120,
                protein: 4.4,
                carbohydrates: 21.3,
                fat: 1.9,
                fiber: 2.8,
                sugar: 0.9,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.4,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 42,
                calcium: 17,
                iron: 1.5,
                magnesium: 64,
                phosphorus: 152,
                potassium: 172,
                sodium: 7,
                zinc: 1.1,
                selenium: 2.8,
                omega3: 0.1,
                omega6: 0.6,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked quinoa"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Cornmeal Arepa",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 220,
                protein: 4.5,
                carbohydrates: 45,
                fat: 2.5,
                fiber: 3.5,
                sugar: 1.5,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.5,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 30,
                calcium: 20,
                iron: 1.8,
                magnesium: 50,
                phosphorus: 100,
                potassium: 150,
                sodium: 300,
                zinc: 1.2,
                selenium: 15,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional South American cornmeal cake"
        ),
        
        // Vegetables
        FoodItem(
            id: UUID(),
            name: "Cassava (Yuca)",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 160,
                protein: 1.4,
                carbohydrates: 38,
                fat: 0.3,
                fiber: 1.8,
                sugar: 1.7,
                vitaminA: 0,
                vitaminC: 20.6,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 1.9,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.9,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 27,
                calcium: 16,
                iron: 0.3,
                magnesium: 21,
                phosphorus: 27,
                potassium: 271,
                sodium: 14,
                zinc: 0.3,
                selenium: 0.7,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked cassava root"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Pumpkin",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 26,
                protein: 1,
                carbohydrates: 6.5,
                fat: 0.1,
                fiber: 0.5,
                sugar: 2.8,
                vitaminA: 8513,
                vitaminC: 9,
                vitaminD: 0,
                vitaminE: 1.1,
                vitaminK: 1.1,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.6,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 16,
                calcium: 21,
                iron: 0.8,
                magnesium: 12,
                phosphorus: 44,
                potassium: 340,
                sodium: 1,
                zinc: 0.3,
                selenium: 0.3,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked pumpkin"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Bell Pepper",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 1,
                carbohydrates: 6,
                fat: 0.3,
                fiber: 2.1,
                sugar: 4.2,
                vitaminA: 157,
                vitaminC: 127.7,
                vitaminD: 0,
                vitaminE: 1.6,
                vitaminK: 4.9,
                thiamin: 0.05,
                riboflavin: 0.09,
                niacin: 0.9,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 46,
                calcium: 7,
                iron: 0.4,
                magnesium: 12,
                phosphorus: 26,
                potassium: 211,
                sodium: 4,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0.01,
                omega6: 0.05,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw red bell pepper"
        ),
        
        // Fruits
        FoodItem(
            id: UUID(),
            name: "Papaya",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 43,
                protein: 0.5,
                carbohydrates: 10.8,
                fat: 0.3,
                fiber: 1.7,
                sugar: 7.8,
                vitaminA: 950,
                vitaminC: 60.9,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 2.6,
                thiamin: 0.02,
                riboflavin: 0.03,
                niacin: 0.4,
                vitaminB6: 0.04,
                vitaminB12: 0,
                folate: 37,
                calcium: 20,
                iron: 0.3,
                magnesium: 21,
                phosphorus: 10,
                potassium: 182,
                sodium: 8,
                zinc: 0.1,
                selenium: 0.6,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh papaya"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Mango",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 60,
                protein: 0.8,
                carbohydrates: 15,
                fat: 0.4,
                fiber: 1.6,
                sugar: 13.7,
                vitaminA: 54,
                vitaminC: 36.4,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 4.2,
                thiamin: 0.03,
                riboflavin: 0.04,
                niacin: 0.7,
                vitaminB6: 0.16,
                vitaminB12: 0,
                folate: 43,
                calcium: 11,
                iron: 0.2,
                magnesium: 10,
                phosphorus: 14,
                potassium: 168,
                sodium: 1,
                zinc: 0.1,
                selenium: 0.6,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh mango"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Avocado",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 160,
                protein: 2,
                carbohydrates: 8.5,
                fat: 14.7,
                fiber: 6.7,
                sugar: 0.7,
                vitaminA: 7,
                vitaminC: 10,
                vitaminD: 0,
                vitaminE: 2.1,
                vitaminK: 21,
                thiamin: 0.07,
                riboflavin: 0.13,
                niacin: 1.7,
                vitaminB6: 0.26,
                vitaminB12: 0,
                folate: 81,
                calcium: 12,
                iron: 0.6,
                magnesium: 29,
                phosphorus: 52,
                potassium: 485,
                sodium: 7,
                zinc: 0.6,
                selenium: 0.4,
                omega3: 0.1,
                omega6: 1.7,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh avocado"
        ),
        
        // Protein
        FoodItem(
            id: UUID(),
            name: "Black Beans",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 132,
                protein: 8.9,
                carbohydrates: 23.7,
                fat: 0.5,
                fiber: 8.7,
                sugar: 0.3,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 140,
                calcium: 27,
                iron: 2.1,
                magnesium: 70,
                phosphorus: 140,
                potassium: 355,
                sodium: 1,
                zinc: 1.1,
                selenium: 1.2,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked black beans"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Lean Beef Steak",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 250,
                protein: 26,
                carbohydrates: 0,
                fat: 17,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 5.4,
                vitaminB6: 0.5,
                vitaminB12: 2.1,
                folate: 9,
                calcium: 12,
                iron: 2.6,
                magnesium: 22,
                phosphorus: 198,
                potassium: 318,
                sodium: 55,
                zinc: 4.3,
                selenium: 21.5,
                omega3: 0.1,
                omega6: 0.4,
                cholesterol: 85
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked lean beef steak"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Sardines",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 208,
                protein: 24,
                carbohydrates: 0,
                fat: 12,
                fiber: 0,
                sugar: 0,
                vitaminA: 64,
                vitaminC: 0,
                vitaminD: 4.8,
                vitaminE: 2,
                vitaminK: 2.6,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 5.2,
                vitaminB6: 0.2,
                vitaminB12: 8.9,
                folate: 10,
                calcium: 382,
                iron: 2.9,
                magnesium: 39,
                phosphorus: 490,
                potassium: 397,
                sodium: 505,
                zinc: 1.3,
                selenium: 52.7,
                omega3: 1.5,
                omega6: 0.1,
                cholesterol: 142
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Canned sardines in oil"
        ),
        
        // Dairy
        FoodItem(
            id: UUID(),
            name: "Queso Fresco",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 299,
                protein: 20,
                carbohydrates: 2.2,
                fat: 24,
                fiber: 0,
                sugar: 2.2,
                vitaminA: 200,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 2.1,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 0.5,
                folate: 10,
                calcium: 700,
                iron: 0.2,
                magnesium: 20,
                phosphorus: 400,
                potassium: 100,
                sodium: 400,
                zinc: 2.5,
                selenium: 15,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 80
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh Mexican-style cheese"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Kefir",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 61,
                protein: 3.3,
                carbohydrates: 4.7,
                fat: 3.3,
                fiber: 0,
                sugar: 4.7,
                vitaminA: 100,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.03,
                riboflavin: 0.14,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.3,
                folate: 13,
                calcium: 120,
                iron: 0.1,
                magnesium: 12,
                phosphorus: 100,
                potassium: 150,
                sodium: 40,
                zinc: 0.4,
                selenium: 3.3,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 10
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Fermented milk drink"
        ),
        
        // Fats
        FoodItem(
            id: UUID(),
            name: "Olive Oil",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 884,
                protein: 0,
                carbohydrates: 0,
                fat: 100,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 14.4,
                vitaminK: 60.2,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 1,
                iron: 0.6,
                magnesium: 0,
                phosphorus: 0,
                potassium: 1,
                sodium: 2,
                zinc: 0,
                selenium: 0,
                omega3: 0.8,
                omega6: 9.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Extra virgin olive oil"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Brazil Nuts",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 656,
                protein: 14.3,
                carbohydrates: 12.3,
                fat: 66.4,
                fiber: 7.5,
                sugar: 2.3,
                vitaminA: 0,
                vitaminC: 0.7,
                vitaminD: 0,
                vitaminE: 5.7,
                vitaminK: 0,
                thiamin: 0.6,
                riboflavin: 0.1,
                niacin: 0.3,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 22,
                calcium: 160,
                iron: 2.4,
                magnesium: 376,
                phosphorus: 725,
                potassium: 659,
                sodium: 3,
                zinc: 4.1,
                selenium: 1917,
                omega3: 0.1,
                omega6: 20.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw Brazil nuts"
        ),
        
        // Beverages
        FoodItem(
            id: UUID(),
            name: "Yerba Mate",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 1,
                protein: 0.1,
                carbohydrates: 0.2,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0.1,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 2,
                phosphorus: 0,
                potassium: 20,
                sodium: 1,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Traditional South American tea"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Filtered Coffee",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 1,
                protein: 0.1,
                carbohydrates: 0,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0.1,
                niacin: 0.7,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 7,
                phosphorus: 7,
                potassium: 116,
                sodium: 2,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Brewed coffee"
        ),
        
        // Snacks
        FoodItem(
            id: UUID(),
            name: "Baked Plantain Chips",
            category: .snacks,
            nutritionalInfo: NutritionalInfo(
                calories: 531,
                protein: 2.3,
                carbohydrates: 58,
                fat: 33,
                fiber: 3.5,
                sugar: 2.3,
                vitaminA: 0,
                vitaminC: 18.4,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.3,
                vitaminB12: 0,
                folate: 22,
                calcium: 10,
                iron: 1.2,
                magnesium: 50,
                phosphorus: 60,
                potassium: 500,
                sodium: 300,
                zinc: 0.5,
                selenium: 1.5,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Baked plantain chips"
        ),
        
        // Other
        FoodItem(
            id: UUID(),
            name: "Chimichurri Herb Sauce",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 120,
                protein: 1,
                carbohydrates: 2,
                fat: 12,
                fiber: 1,
                sugar: 0.5,
                vitaminA: 500,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 2,
                vitaminK: 50,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 10,
                calcium: 20,
                iron: 1,
                magnesium: 10,
                phosphorus: 15,
                potassium: 100,
                sodium: 200,
                zinc: 0.2,
                selenium: 1,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional Argentine herb sauce"
        )
    ]
    
    // MARK: - European Foods
    static let europeanFoods: [FoodItem] = [
        // Grains
        FoodItem(
            id: UUID(),
            name: "Rye Bread",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 259,
                protein: 8.5,
                carbohydrates: 48,
                fat: 3.3,
                fiber: 5.8,
                sugar: 3.9,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 1.2,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.8,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 60,
                calcium: 73,
                iron: 2.8,
                magnesium: 40,
                phosphorus: 125,
                potassium: 166,
                sodium: 603,
                zinc: 1.5,
                selenium: 30,
                omega3: 0.1,
                omega6: 0.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional European rye bread"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Rolled Oats",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 389,
                protein: 16.9,
                carbohydrates: 66.3,
                fat: 6.9,
                fiber: 10.6,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 2,
                thiamin: 0.8,
                riboflavin: 0.1,
                niacin: 1,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 56,
                calcium: 54,
                iron: 4.7,
                magnesium: 177,
                phosphorus: 523,
                potassium: 429,
                sodium: 2,
                zinc: 4,
                selenium: 34,
                omega3: 0.1,
                omega6: 2.4,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw rolled oats"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Buckwheat Groats",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 343,
                protein: 13.2,
                carbohydrates: 71.5,
                fat: 3.4,
                fiber: 10,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.4,
                niacin: 7,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 30,
                calcium: 18,
                iron: 2.2,
                magnesium: 258,
                phosphorus: 347,
                potassium: 460,
                sodium: 1,
                zinc: 2.4,
                selenium: 8.3,
                omega3: 0.1,
                omega6: 0.9,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw buckwheat groats"
        ),
        
        // Vegetables
        FoodItem(
            id: UUID(),
            name: "Cabbage",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.3,
                carbohydrates: 5.8,
                fat: 0.1,
                fiber: 2.5,
                sugar: 3.2,
                vitaminA: 98,
                vitaminC: 36.6,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 76,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.2,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 43,
                calcium: 40,
                iron: 0.5,
                magnesium: 12,
                phosphorus: 26,
                potassium: 170,
                sodium: 18,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw green cabbage"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Garden Peas",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 81,
                protein: 5.4,
                carbohydrates: 14.5,
                fat: 0.4,
                fiber: 5.1,
                sugar: 5.7,
                vitaminA: 765,
                vitaminC: 40,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 24.8,
                thiamin: 0.3,
                riboflavin: 0.1,
                niacin: 2.1,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 65,
                calcium: 25,
                iron: 1.5,
                magnesium: 33,
                phosphorus: 108,
                potassium: 244,
                sodium: 5,
                zinc: 1.2,
                selenium: 1.8,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked garden peas"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Beetroot",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 43,
                protein: 1.6,
                carbohydrates: 9.6,
                fat: 0.2,
                fiber: 2.8,
                sugar: 6.8,
                vitaminA: 33,
                vitaminC: 4.9,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.2,
                thiamin: 0.03,
                riboflavin: 0.04,
                niacin: 0.3,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 109,
                calcium: 16,
                iron: 0.8,
                magnesium: 23,
                phosphorus: 40,
                potassium: 325,
                sodium: 78,
                zinc: 0.4,
                selenium: 0.7,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked beetroot"
        ),
        
        // Fruits
        FoodItem(
            id: UUID(),
            name: "Pears",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 57,
                protein: 0.4,
                carbohydrates: 15.2,
                fat: 0.1,
                fiber: 3.1,
                sugar: 9.8,
                vitaminA: 1,
                vitaminC: 4.3,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 4.4,
                thiamin: 0.01,
                riboflavin: 0.03,
                niacin: 0.2,
                vitaminB6: 0.03,
                vitaminB12: 0,
                folate: 7,
                calcium: 9,
                iron: 0.2,
                magnesium: 7,
                phosphorus: 12,
                potassium: 116,
                sodium: 1,
                zinc: 0.1,
                selenium: 0.1,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh pear"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Plums",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 46,
                protein: 0.7,
                carbohydrates: 11.4,
                fat: 0.3,
                fiber: 1.4,
                sugar: 9.9,
                vitaminA: 345,
                vitaminC: 9.5,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 6.4,
                thiamin: 0.03,
                riboflavin: 0.03,
                niacin: 0.4,
                vitaminB6: 0.03,
                vitaminB12: 0,
                folate: 5,
                calcium: 6,
                iron: 0.2,
                magnesium: 7,
                phosphorus: 16,
                potassium: 157,
                sodium: 0,
                zinc: 0.1,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh plum"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Raspberries",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 52,
                protein: 1.2,
                carbohydrates: 11.9,
                fat: 0.7,
                fiber: 6.5,
                sugar: 4.4,
                vitaminA: 33,
                vitaminC: 26.2,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 7.8,
                thiamin: 0.03,
                riboflavin: 0.04,
                niacin: 0.6,
                vitaminB6: 0.06,
                vitaminB12: 0,
                folate: 21,
                calcium: 25,
                iron: 0.7,
                magnesium: 22,
                phosphorus: 29,
                potassium: 151,
                sodium: 1,
                zinc: 0.4,
                selenium: 0.2,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh raspberries"
        ),
        
        // Protein
        FoodItem(
            id: UUID(),
            name: "Eggs",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 155,
                protein: 12.6,
                carbohydrates: 1.1,
                fat: 11.3,
                fiber: 0,
                sugar: 1.1,
                vitaminA: 160,
                vitaminC: 0,
                vitaminD: 2,
                vitaminE: 1.1,
                vitaminK: 0.3,
                thiamin: 0.1,
                riboflavin: 0.5,
                niacin: 0.1,
                vitaminB6: 0.2,
                vitaminB12: 0.6,
                folate: 47,
                calcium: 56,
                iron: 1.8,
                magnesium: 12,
                phosphorus: 198,
                potassium: 138,
                sodium: 124,
                zinc: 1.3,
                selenium: 15.4,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 373
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Whole egg, cooked"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Herring",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 158,
                protein: 18,
                carbohydrates: 0,
                fat: 9,
                fiber: 0,
                sugar: 0,
                vitaminA: 93,
                vitaminC: 0.7,
                vitaminD: 4.2,
                vitaminE: 1.1,
                vitaminK: 0.1,
                thiamin: 0.1,
                riboflavin: 0.3,
                niacin: 3.2,
                vitaminB6: 0.3,
                vitaminB12: 13.7,
                folate: 5,
                calcium: 57,
                iron: 1.1,
                magnesium: 32,
                phosphorus: 236,
                potassium: 327,
                sodium: 90,
                zinc: 1.1,
                selenium: 36.5,
                omega3: 1.7,
                omega6: 0.2,
                cholesterol: 77
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked Atlantic herring"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Brown Lentils",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 116,
                protein: 9,
                carbohydrates: 20,
                fat: 0.4,
                fiber: 7.9,
                sugar: 1.8,
                vitaminA: 0,
                vitaminC: 1.5,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 1.7,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.1,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 181,
                calcium: 19,
                iron: 3.3,
                magnesium: 36,
                phosphorus: 180,
                potassium: 369,
                sodium: 2,
                zinc: 1.3,
                selenium: 2.8,
                omega3: 0.1,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked brown lentils"
        ),
        
        // Dairy
        FoodItem(
            id: UUID(),
            name: "Kefir",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 61,
                protein: 3.3,
                carbohydrates: 4.7,
                fat: 3.3,
                fiber: 0,
                sugar: 4.7,
                vitaminA: 100,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.03,
                riboflavin: 0.14,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.3,
                folate: 13,
                calcium: 120,
                iron: 0.1,
                magnesium: 12,
                phosphorus: 100,
                potassium: 150,
                sodium: 40,
                zinc: 0.4,
                selenium: 3.3,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 10
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Fermented milk drink"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Aged Cheddar",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 403,
                protein: 25,
                carbohydrates: 1.3,
                fat: 33.1,
                fiber: 0,
                sugar: 0.5,
                vitaminA: 265,
                vitaminC: 0,
                vitaminD: 0.6,
                vitaminE: 0.7,
                vitaminK: 2.4,
                thiamin: 0.02,
                riboflavin: 0.4,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 1.1,
                folate: 18,
                calcium: 721,
                iron: 0.7,
                magnesium: 28,
                phosphorus: 512,
                potassium: 98,
                sodium: 621,
                zinc: 3.1,
                selenium: 14.5,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 105
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Aged cheddar cheese"
        ),
        
        // Fats
        FoodItem(
            id: UUID(),
            name: "Rapeseed (Canola) Oil",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 884,
                protein: 0,
                carbohydrates: 0,
                fat: 100,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 17.5,
                vitaminK: 71.3,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0,
                magnesium: 0,
                phosphorus: 0,
                potassium: 0,
                sodium: 0,
                zinc: 0,
                selenium: 0,
                omega3: 9.1,
                omega6: 19.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Rapeseed oil"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Walnuts",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 654,
                protein: 15.2,
                carbohydrates: 13.7,
                fat: 65.2,
                fiber: 6.7,
                sugar: 2.6,
                vitaminA: 0,
                vitaminC: 1.3,
                vitaminD: 0,
                vitaminE: 0.7,
                vitaminK: 2.7,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 1.1,
                vitaminB6: 0.5,
                vitaminB12: 0,
                folate: 98,
                calcium: 98,
                iron: 2.9,
                magnesium: 158,
                phosphorus: 346,
                potassium: 441,
                sodium: 2,
                zinc: 3.1,
                selenium: 4.9,
                omega3: 9.1,
                omega6: 38.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw walnuts"
        ),
        
        // Beverages
        FoodItem(
            id: UUID(),
            name: "Black Tea",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 1,
                protein: 0.1,
                carbohydrates: 0.2,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 3,
                phosphorus: 1,
                potassium: 37,
                sodium: 3,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Brewed black tea"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Sparkling Mineral Water",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 0,
                protein: 0,
                carbohydrates: 0,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0,
                magnesium: 0,
                phosphorus: 0,
                potassium: 0,
                sodium: 0,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Carbonated mineral water"
        ),
        
        // Snacks
        FoodItem(
            id: UUID(),
            name: "Scottish Oatcakes",
            category: .snacks,
            nutritionalInfo: NutritionalInfo(
                calories: 471,
                protein: 11.5,
                carbohydrates: 58.1,
                fat: 22.5,
                fiber: 7.2,
                sugar: 1.2,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.5,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 30,
                calcium: 50,
                iron: 3.5,
                magnesium: 100,
                phosphorus: 300,
                potassium: 300,
                sodium: 500,
                zinc: 2,
                selenium: 20,
                omega3: 0.5,
                omega6: 2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional Scottish oatcakes"
        ),
        
        // Other
        FoodItem(
            id: UUID(),
            name: "Sauerkraut",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 19,
                protein: 0.9,
                carbohydrates: 4.3,
                fat: 0.2,
                fiber: 2.9,
                sugar: 1.8,
                vitaminA: 1,
                vitaminC: 14.7,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 13,
                thiamin: 0.02,
                riboflavin: 0.02,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 24,
                calcium: 30,
                iron: 1.5,
                magnesium: 13,
                phosphorus: 20,
                potassium: 170,
                sodium: 661,
                zinc: 0.2,
                selenium: 0.6,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fermented cabbage"
        )
    ]
    
    // MARK: - Mediterranean Foods
    static let mediterraneanFoods: [FoodItem] = [
        // Grains
        FoodItem(
            id: UUID(),
            name: "Bulgur Wheat",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 83,
                protein: 3.1,
                carbohydrates: 17.8,
                fat: 0.2,
                fiber: 4.5,
                sugar: 0.2,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.1,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1.8,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 18,
                calcium: 10,
                iron: 0.9,
                magnesium: 32,
                phosphorus: 40,
                potassium: 68,
                sodium: 5,
                zinc: 0.5,
                selenium: 0.8,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked bulgur wheat"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Couscous",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 112,
                protein: 3.8,
                carbohydrates: 23.2,
                fat: 0.2,
                fiber: 1.4,
                sugar: 0.1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 15,
                calcium: 8,
                iron: 0.5,
                magnesium: 13,
                phosphorus: 22,
                potassium: 58,
                sodium: 5,
                zinc: 0.3,
                selenium: 0.5,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked couscous"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Whole Wheat Pita",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 275,
                protein: 9.1,
                carbohydrates: 55.7,
                fat: 1.2,
                fiber: 7.4,
                sugar: 0.8,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 1.2,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 4.5,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 50,
                calcium: 100,
                iron: 3.6,
                magnesium: 80,
                phosphorus: 200,
                potassium: 250,
                sodium: 400,
                zinc: 2,
                selenium: 30,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Whole wheat pita bread"
        ),
        
        // Vegetables
        FoodItem(
            id: UUID(),
            name: "Eggplant",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1,
                carbohydrates: 6,
                fat: 0.2,
                fiber: 3,
                sugar: 3.5,
                vitaminA: 23,
                vitaminC: 2.2,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 3.5,
                thiamin: 0.04,
                riboflavin: 0.04,
                niacin: 0.6,
                vitaminB6: 0.08,
                vitaminB12: 0,
                folate: 22,
                calcium: 9,
                iron: 0.2,
                magnesium: 14,
                phosphorus: 24,
                potassium: 229,
                sodium: 2,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw eggplant"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Zucchini",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 17,
                protein: 1.2,
                carbohydrates: 3.1,
                fat: 0.3,
                fiber: 1,
                sugar: 2.5,
                vitaminA: 10,
                vitaminC: 17.9,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 4.3,
                thiamin: 0.05,
                riboflavin: 0.09,
                niacin: 0.5,
                vitaminB6: 0.16,
                vitaminB12: 0,
                folate: 24,
                calcium: 16,
                iron: 0.4,
                magnesium: 18,
                phosphorus: 38,
                potassium: 261,
                sodium: 8,
                zinc: 0.3,
                selenium: 0.2,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw zucchini"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Artichoke",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 47,
                protein: 3.3,
                carbohydrates: 10.5,
                fat: 0.2,
                fiber: 5.4,
                sugar: 0.9,
                vitaminA: 13,
                vitaminC: 11.7,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 14.8,
                thiamin: 0.07,
                riboflavin: 0.07,
                niacin: 1,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 68,
                calcium: 44,
                iron: 1.3,
                magnesium: 60,
                phosphorus: 90,
                potassium: 370,
                sodium: 94,
                zinc: 0.5,
                selenium: 0.2,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked artichoke"
        ),
        
        // Fruits
        FoodItem(
            id: UUID(),
            name: "Figs",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 74,
                protein: 0.8,
                carbohydrates: 19.2,
                fat: 0.3,
                fiber: 2.9,
                sugar: 16.3,
                vitaminA: 7,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 4.7,
                thiamin: 0.06,
                riboflavin: 0.05,
                niacin: 0.4,
                vitaminB6: 0.11,
                vitaminB12: 0,
                folate: 6,
                calcium: 35,
                iron: 0.4,
                magnesium: 17,
                phosphorus: 14,
                potassium: 232,
                sodium: 1,
                zinc: 0.2,
                selenium: 0.2,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh figs"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Pomegranate",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 83,
                protein: 1.7,
                carbohydrates: 18.7,
                fat: 1.2,
                fiber: 4,
                sugar: 13.7,
                vitaminA: 0,
                vitaminC: 10.2,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 16.4,
                thiamin: 0.07,
                riboflavin: 0.05,
                niacin: 0.3,
                vitaminB6: 0.08,
                vitaminB12: 0,
                folate: 38,
                calcium: 10,
                iron: 0.3,
                magnesium: 12,
                phosphorus: 36,
                potassium: 236,
                sodium: 3,
                zinc: 0.4,
                selenium: 0.5,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh pomegranate arils"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Dates",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 282,
                protein: 2.5,
                carbohydrates: 75,
                fat: 0.4,
                fiber: 8,
                sugar: 63.4,
                vitaminA: 10,
                vitaminC: 0.4,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 2.7,
                thiamin: 0.05,
                riboflavin: 0.07,
                niacin: 1.6,
                vitaminB6: 0.16,
                vitaminB12: 0,
                folate: 19,
                calcium: 39,
                iron: 1,
                magnesium: 43,
                phosphorus: 62,
                potassium: 656,
                sodium: 2,
                zinc: 0.3,
                selenium: 3,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Dried dates"
        ),
        
        // Protein
        FoodItem(
            id: UUID(),
            name: "Chickpeas",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 164,
                protein: 8.9,
                carbohydrates: 27.4,
                fat: 2.6,
                fiber: 7.6,
                sugar: 4.8,
                vitaminA: 27,
                vitaminC: 1.3,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 4,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 172,
                calcium: 49,
                iron: 2.9,
                magnesium: 48,
                phosphorus: 168,
                potassium: 291,
                sodium: 7,
                zinc: 1.5,
                selenium: 3.7,
                omega3: 0.1,
                omega6: 1.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked chickpeas"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Lamb",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 294,
                protein: 25.6,
                carbohydrates: 0,
                fat: 21.2,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 5.7,
                vitaminB6: 0.2,
                vitaminB12: 2.7,
                folate: 19,
                calcium: 17,
                iron: 1.9,
                magnesium: 23,
                phosphorus: 198,
                potassium: 310,
                sodium: 65,
                zinc: 4.4,
                selenium: 21.5,
                omega3: 0.5,
                omega6: 1.5,
                cholesterol: 97
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked lamb meat"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Anchovies",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 131,
                protein: 20.1,
                carbohydrates: 0,
                fat: 4.8,
                fiber: 0,
                sugar: 0,
                vitaminA: 50,
                vitaminC: 0,
                vitaminD: 1.7,
                vitaminE: 0.6,
                vitaminK: 0.1,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 14.6,
                vitaminB6: 0.1,
                vitaminB12: 0.6,
                folate: 9,
                calcium: 147,
                iron: 3.3,
                magnesium: 41,
                phosphorus: 174,
                potassium: 383,
                sodium: 104,
                zinc: 1.7,
                selenium: 36.5,
                omega3: 1.5,
                omega6: 0.1,
                cholesterol: 60
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Canned anchovies in oil"
        ),
        
        // Dairy
        FoodItem(
            id: UUID(),
            name: "Feta Cheese",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 264,
                protein: 14.2,
                carbohydrates: 4.1,
                fat: 21.3,
                fiber: 0,
                sugar: 4.1,
                vitaminA: 125,
                vitaminC: 0,
                vitaminD: 0.2,
                vitaminE: 0.2,
                vitaminK: 1.8,
                thiamin: 0.15,
                riboflavin: 0.84,
                niacin: 0.99,
                vitaminB6: 0.42,
                vitaminB12: 1.69,
                folate: 32,
                calcium: 493,
                iron: 0.7,
                magnesium: 19,
                phosphorus: 337,
                potassium: 62,
                sodium: 1116,
                zinc: 2.9,
                selenium: 15,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 89
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional Greek feta cheese"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Greek Yogurt",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 59,
                protein: 10.3,
                carbohydrates: 3.6,
                fat: 0.4,
                fiber: 0,
                sugar: 3.6,
                vitaminA: 4,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.03,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.2,
                folate: 7,
                calcium: 111,
                iron: 0.1,
                magnesium: 11,
                phosphorus: 135,
                potassium: 141,
                sodium: 36,
                zinc: 0.5,
                selenium: 9.7,
                omega3: 0.01,
                omega6: 0.01,
                cholesterol: 5
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Plain, non-fat Greek yogurt"
        ),
        
        // Fats
        FoodItem(
            id: UUID(),
            name: "Extra Virgin Olive Oil",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 884,
                protein: 0,
                carbohydrates: 0,
                fat: 100,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 14.4,
                vitaminK: 60.2,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 1,
                iron: 0.6,
                magnesium: 0,
                phosphorus: 0,
                potassium: 1,
                sodium: 2,
                zinc: 0,
                selenium: 0,
                omega3: 0.8,
                omega6: 9.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Extra virgin olive oil"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Pine Nuts",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 673,
                protein: 13.7,
                carbohydrates: 13.1,
                fat: 68.4,
                fiber: 3.7,
                sugar: 3.6,
                vitaminA: 1,
                vitaminC: 0.8,
                vitaminD: 0,
                vitaminE: 9.3,
                vitaminK: 53.9,
                thiamin: 0.4,
                riboflavin: 0.2,
                niacin: 4.4,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 34,
                calcium: 16,
                iron: 5.5,
                magnesium: 251,
                phosphorus: 575,
                potassium: 597,
                sodium: 2,
                zinc: 6.5,
                selenium: 0.7,
                omega3: 0.1,
                omega6: 33.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw pine nuts"
        ),
        
        // Beverages
        FoodItem(
            id: UUID(),
            name: "Green Tea",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 1,
                protein: 0.2,
                carbohydrates: 0.2,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0.1,
                niacin: 0.1,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 2,
                phosphorus: 0,
                potassium: 27,
                sodium: 1,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Brewed green tea"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Pomegranate Juice",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 54,
                protein: 0.2,
                carbohydrates: 13.1,
                fat: 0.3,
                fiber: 0.1,
                sugar: 12.7,
                vitaminA: 0,
                vitaminC: 0.1,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 10.4,
                thiamin: 0.02,
                riboflavin: 0.02,
                niacin: 0.2,
                vitaminB6: 0.04,
                vitaminB12: 0,
                folate: 24,
                calcium: 11,
                iron: 0.1,
                magnesium: 7,
                phosphorus: 11,
                potassium: 214,
                sodium: 9,
                zinc: 0.1,
                selenium: 0.3,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Pure pomegranate juice"
        ),
        
        // Snacks
        FoodItem(
            id: UUID(),
            name: "Hummus",
            category: .snacks,
            nutritionalInfo: NutritionalInfo(
                calories: 166,
                protein: 7.9,
                carbohydrates: 14.3,
                fat: 9.6,
                fiber: 6,
                sugar: 0.3,
                vitaminA: 0,
                vitaminC: 1.5,
                vitaminD: 0,
                vitaminE: 0.7,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 83,
                calcium: 38,
                iron: 2.4,
                magnesium: 48,
                phosphorus: 176,
                potassium: 228,
                sodium: 379,
                zinc: 1.8,
                selenium: 2.6,
                omega3: 0.1,
                omega6: 3.6,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional chickpea dip"
        ),
        
        // Other
        FoodItem(
            id: UUID(),
            name: "Tahini",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 595,
                protein: 17,
                carbohydrates: 21.2,
                fat: 53.8,
                fiber: 9.3,
                sugar: 0.5,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 0,
                thiamin: 0.8,
                riboflavin: 0.5,
                niacin: 5.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 98,
                calcium: 426,
                iron: 8.9,
                magnesium: 95,
                phosphorus: 732,
                potassium: 414,
                sodium: 115,
                zinc: 4.6,
                selenium: 34.4,
                omega3: 0.6,
                omega6: 20.7,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Sesame seed paste"
        )
    ]
} 