import Foundation

struct RussianCuisineFoodItems {
    static let foods: [FoodItem] = [
        // Borscht
        FoodItem(
            id: UUID(),
            name: "Borscht",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 145,
                protein: 6.8,
                carbohydrates: 22,
                fat: 4.8,
                fiber: 4.2,
                sugar: 12.5,
                vitaminA: 285,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 125,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.25,
                vitaminB12: 0.8,
                folate: 85,
                calcium: 125,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 145,
                potassium: 485,
                sodium: 685,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 15
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional beetroot soup with cabbage, meat, and sour cream",
            nameFr: "Bortsch",
            nameEs: "Borscht",
            nameHe: "בורשט",
            notesFr: "Soupe traditionnelle de betterave avec chou, viande et crème aigre",
            notesEs: "Sopa tradicional de remolacha con repollo, carne y crema agria",
            notesHe: "מרק סלק מסורתי עם כרוב, בשר וקרם חמוץ"
        ),
        
        // Beef Stroganoff
        FoodItem(
            id: UUID(),
            name: "Beef Stroganoff",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 425,
                protein: 32.5,
                carbohydrates: 18,
                fat: 26.8,
                fiber: 2.2,
                sugar: 6.5,
                vitaminA: 125,
                vitaminC: 15,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.28,
                riboflavin: 0.35,
                niacin: 12.8,
                vitaminB6: 0.58,
                vitaminB12: 4.2,
                folate: 45,
                calcium: 185,
                iron: 4.8,
                magnesium: 85,
                phosphorus: 385,
                potassium: 585,
                sodium: 885,
                zinc: 6.8,
                selenium: 28.5,
                omega3: 0.5,
                omega6: 4.8,
                cholesterol: 125
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Tender beef strips in creamy mushroom and sour cream sauce",
            nameFr: "Bœuf Stroganoff",
            nameEs: "Stroganoff de Ternera",
            nameHe: "בקר סטרוגנוף",
            notesFr: "Lamelles de bœuf tendres dans une sauce crémeuse aux champignons et crème aigre",
            notesEs: "Tiras tiernas de ternera en salsa cremosa de champiñones y crema agria",
            notesHe: "רצועות בקר רכות ברוטב קרמי של פטריות וקרם חמוץ"
        ),
        
        // Pelmeni
        FoodItem(
            id: UUID(),
            name: "Pelmeni",
            category: .grains,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 18.5,
                carbohydrates: 32,
                fat: 14.8,
                fiber: 2.8,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 8,
                vitaminD: 0.5,
                vitaminE: 1.8,
                vitaminK: 15,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 6.8,
                vitaminB6: 0.35,
                vitaminB12: 2.2,
                folate: 65,
                calcium: 85,
                iron: 3.2,
                magnesium: 65,
                phosphorus: 225,
                potassium: 385,
                sodium: 685,
                zinc: 3.8,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 4.2,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional dumplings filled with meat, served with sour cream",
            nameFr: "Pelmeni",
            nameEs: "Pelmeni",
            nameHe: "פלמני",
            notesFr: "Boulettes traditionnelles farcies à la viande, servies avec crème aigre",
            notesEs: "Empanadillas tradicionales rellenas de carne, servidas con crema agria",
            notesHe: "כופתאות מסורתיות ממולאות בשר, מוגשות עם קרם חמוץ"
        ),
        
        // Chicken Kiev
        FoodItem(
            id: UUID(),
            name: "Chicken Kiev",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 485,
                protein: 28.5,
                carbohydrates: 15,
                fat: 35.8,
                fiber: 1.2,
                sugar: 2.5,
                vitaminA: 185,
                vitaminC: 12,
                vitaminD: 1.2,
                vitaminE: 3.8,
                vitaminK: 45,
                thiamin: 0.25,
                riboflavin: 0.28,
                niacin: 11.8,
                vitaminB6: 0.58,
                vitaminB12: 2.8,
                folate: 35,
                calcium: 125,
                iron: 2.8,
                magnesium: 58,
                phosphorus: 285,
                potassium: 485,
                sodium: 785,
                zinc: 4.2,
                selenium: 25.8,
                omega3: 0.5,
                omega6: 8.8,
                cholesterol: 145
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Breaded chicken breast stuffed with garlic butter and herbs",
            nameFr: "Poulet à la Kiev",
            nameEs: "Pollo Kiev",
            nameHe: "עוף קייב",
            notesFr: "Poitrine de poulet panée farcie au beurre à l'ail et aux herbes",
            notesEs: "Pechuga de pollo empanada rellena de mantequilla de ajo y hierbas",
            notesHe: "חזה עוף פירורי לחם ממולא חמאת שום ועשבי תיבול"
        ),
        
        // Blini
        FoodItem(
            id: UUID(),
            name: "Blini",
            category: .grains,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 8.8,
                carbohydrates: 28,
                fat: 8.8,
                fiber: 2.2,
                sugar: 6.5,
                vitaminA: 125,
                vitaminC: 5,
                vitaminD: 1.2,
                vitaminE: 1.8,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.25,
                niacin: 3.2,
                vitaminB6: 0.12,
                vitaminB12: 1.8,
                folate: 65,
                calcium: 185,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 185,
                potassium: 285,
                sodium: 385,
                zinc: 1.8,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 85
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Thin pancakes served with caviar, sour cream, or jam",
            nameFr: "Blinis",
            nameEs: "Blinis",
            nameHe: "בליני",
            notesFr: "Crêpes fines servies avec caviar, crème aigre ou confiture",
            notesEs: "Panqueques finos servidos con caviar, crema agria o mermelada",
            notesHe: "פנקייקים דקים מוגשים עם קוויאר, קרם חמוץ או ריבה"
        ),
        
        // Solyanka
        FoodItem(
            id: UUID(),
            name: "Solyanka",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 12.8,
                carbohydrates: 15,
                fat: 8.8,
                fiber: 3.8,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 0,
                vitaminE: 2.2,
                vitaminK: 85,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 4.2,
                vitaminB6: 0.28,
                vitaminB12: 1.2,
                folate: 65,
                calcium: 125,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 185,
                potassium: 585,
                sodium: 985,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 3.2,
                cholesterol: 35
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Hearty soup with pickled vegetables, meat, and olives",
            nameFr: "Solianka",
            nameEs: "Solyanka",
            nameHe: "סוליאנקה",
            notesFr: "Soupe copieuse avec légumes marinés, viande et olives",
            notesEs: "Sopa abundante con verduras encurtidas, carne y aceitunas",
            notesHe: "מרק מזין עם ירקות כבושים, בשר וזיתים"
        ),
        
        // Beef Goulash
        FoodItem(
            id: UUID(),
            name: "Russian Beef Goulash",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 28.5,
                carbohydrates: 22,
                fat: 22.8,
                fiber: 3.2,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0.5,
                vitaminE: 2.8,
                vitaminK: 45,
                thiamin: 0.25,
                riboflavin: 0.28,
                niacin: 9.8,
                vitaminB6: 0.48,
                vitaminB12: 3.8,
                folate: 55,
                calcium: 125,
                iron: 4.2,
                magnesium: 85,
                phosphorus: 285,
                potassium: 685,
                sodium: 785,
                zinc: 5.8,
                selenium: 25.8,
                omega3: 0.5,
                omega6: 5.2,
                cholesterol: 105
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Slow-cooked beef stew with vegetables in rich paprika sauce",
            nameFr: "Goulasch de Bœuf Russe",
            nameEs: "Gulash de Ternera Ruso",
            nameHe: "גולאש בקר רוסי",
            notesFr: "Ragoût de bœuf mijoté avec légumes dans une sauce riche au paprika",
            notesEs: "Estofado de ternera cocido lentamente con verduras en salsa rica de pimentón",
            notesHe: "תבשיל בקר מבושל איטי עם ירקות ברוטב עשיר של פפריקה"
        ),
        
        // Cabbage Rolls (Golubtsy)
        FoodItem(
            id: UUID(),
            name: "Golubtsy",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 14.8,
                carbohydrates: 28,
                fat: 9.8,
                fiber: 4.8,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 2.2,
                vitaminK: 125,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.35,
                vitaminB12: 1.2,
                folate: 85,
                calcium: 125,
                iron: 3.2,
                magnesium: 85,
                phosphorus: 185,
                potassium: 585,
                sodium: 685,
                zinc: 2.8,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 3.8,
                cholesterol: 45
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Cabbage leaves stuffed with rice, meat, and herbs in tomato sauce",
            nameFr: "Golubtsy",
            nameEs: "Golubtsy",
            nameHe: "גולובצי",
            notesFr: "Feuilles de chou farcies au riz, viande et herbes dans sauce tomate",
            notesEs: "Hojas de repollo rellenas de arroz, carne y hierbas en salsa de tomate",
            notesHe: "עלי כרוב ממולאים באורז, בשר ועשבי תיבול ברוטב עגבניות"
        ),
        
        // Olivier Salad
        FoodItem(
            id: UUID(),
            name: "Olivier Salad",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 8.8,
                carbohydrates: 22,
                fat: 18.8,
                fiber: 3.8,
                sugar: 6.5,
                vitaminA: 185,
                vitaminC: 35,
                vitaminD: 0.8,
                vitaminE: 4.2,
                vitaminK: 45,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 3.2,
                vitaminB6: 0.28,
                vitaminB12: 0.8,
                folate: 65,
                calcium: 85,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 145,
                potassium: 485,
                sodium: 885,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.8,
                omega6: 6.8,
                cholesterol: 125
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional potato salad with eggs, pickles, and mayonnaise",
            nameFr: "Salade Olivier",
            nameEs: "Ensalada Olivier",
            nameHe: "סלט אוליבייה",
            notesFr: "Salade de pommes de terre traditionnelle avec œufs, cornichons et mayonnaise",
            notesEs: "Ensalada tradicional de papas con huevos, pepinillos y mayonesa",
            notesHe: "סלט תפוחי אדמה מסורתי עם ביצים, חמוצים ומיונז"
        ),
        
        // Kotlety
        FoodItem(
            id: UUID(),
            name: "Kotlety",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 22.5,
                carbohydrates: 18,
                fat: 19.8,
                fiber: 2.2,
                sugar: 4.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.22,
                riboflavin: 0.25,
                niacin: 8.8,
                vitaminB6: 0.42,
                vitaminB12: 2.8,
                folate: 45,
                calcium: 125,
                iron: 3.8,
                magnesium: 65,
                phosphorus: 225,
                potassium: 485,
                sodium: 685,
                zinc: 4.2,
                selenium: 22.5,
                omega3: 0.3,
                omega6: 5.8,
                cholesterol: 95
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Pan-fried ground meat patties with bread crumbs and onions",
            nameFr: "Kotlety",
            nameEs: "Kotlety",
            nameHe: "קוטלטי",
            notesFr: "Galettes de viande hachée poêlées avec chapelure et oignons",
            notesEs: "Hamburguesas de carne picada fritas con pan rallado y cebollas",
            notesHe: "קציצות בשר טחון מטוגנות עם פירורי לחם ובצל"
        ),
        
        // Shchi
        FoodItem(
            id: UUID(),
            name: "Shchi",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 125,
                protein: 8.8,
                carbohydrates: 15,
                fat: 3.8,
                fiber: 4.2,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 125,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.25,
                vitaminB12: 0.5,
                folate: 85,
                calcium: 125,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 125,
                potassium: 485,
                sodium: 585,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 15
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Traditional cabbage soup with meat and vegetables",
            nameFr: "Chtchi",
            nameEs: "Shchi",
            nameHe: "שצ'י",
            notesFr: "Soupe traditionnelle au chou avec viande et légumes",
            notesEs: "Sopa tradicional de repollo con carne y verduras",
            notesHe: "מרק כרוב מסורתי עם בשר וירקות"
        ),
        
        // Vareniki
        FoodItem(
            id: UUID(),
            name: "Vareniki",
            category: .grains,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.8,
                carbohydrates: 45,
                fat: 6.8,
                fiber: 3.8,
                sugar: 12.5,
                vitaminA: 125,
                vitaminC: 15,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 25,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 4.2,
                vitaminB6: 0.25,
                vitaminB12: 1.2,
                folate: 85,
                calcium: 125,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 185,
                potassium: 385,
                sodium: 485,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 65
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Dumplings filled with potatoes, cheese, or berries",
            nameFr: "Vareniki",
            nameEs: "Vareniki",
            nameHe: "ורניקי",
            notesFr: "Boulettes farcies aux pommes de terre, fromage ou baies",
            notesEs: "Empanadillas rellenas de papas, queso o bayas",
            notesHe: "כופתאות ממולאות תפוחי אדמה, גבינה או פירות יער"
        ),
        
        // Beef Stroganov
        FoodItem(
            id: UUID(),
            name: "Russian Fish Soup (Ukha)",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 18.5,
                carbohydrates: 8,
                fat: 6.8,
                fiber: 1.8,
                sugar: 4.5,
                vitaminA: 85,
                vitaminC: 25,
                vitaminD: 2.8,
                vitaminE: 1.8,
                vitaminK: 15,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 6.8,
                vitaminB6: 0.35,
                vitaminB12: 3.8,
                folate: 25,
                calcium: 85,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 225,
                potassium: 485,
                sodium: 685,
                zinc: 2.2,
                selenium: 25.8,
                omega3: 1.8,
                omega6: 0.8,
                cholesterol: 65
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: true,
            notes: "Clear fish soup with vegetables and herbs",
            nameFr: "Soupe de Poisson Russe (Ukha)",
            nameEs: "Sopa de Pescado Rusa (Ukha)",
            nameHe: "מרק דגים רוסי (אוחה)",
            notesFr: "Soupe de poisson claire avec légumes et herbes",
            notesEs: "Sopa clara de pescado con verduras y hierbas",
            notesHe: "מרק דגים צלול עם ירקות ועשבי תיבול"
        ),
        
        // Syrniki
        FoodItem(
            id: UUID(),
            name: "Syrniki",
            category: .dairy,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 14.8,
                carbohydrates: 22,
                fat: 12.8,
                fiber: 1.8,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 5,
                vitaminD: 1.8,
                vitaminE: 1.8,
                vitaminK: 8,
                thiamin: 0.15,
                riboflavin: 0.35,
                niacin: 2.8,
                vitaminB6: 0.12,
                vitaminB12: 2.2,
                folate: 45,
                calcium: 285,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 285,
                potassium: 285,
                sodium: 385,
                zinc: 2.2,
                selenium: 15.5,
                omega3: 0.3,
                omega6: 3.8,
                cholesterol: 125
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Cottage cheese pancakes served with sour cream or jam",
            nameFr: "Syrniki",
            nameEs: "Syrniki",
            nameHe: "סירניקי",
            notesFr: "Crêpes au fromage blanc servies avec crème aigre ou confiture",
            notesEs: "Panqueques de requesón servidos con crema agria o mermelada",
            notesHe: "פנקייקים של גבינת קוטג' מוגשים עם קרם חמוץ או ריבה"
        ),
        
        // Herring Under Fur Coat
        FoodItem(
            id: UUID(),
            name: "Herring Under Fur Coat",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 16.8,
                carbohydrates: 18,
                fat: 22.8,
                fiber: 3.2,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 2.8,
                vitaminE: 4.2,
                vitaminK: 45,
                thiamin: 0.18,
                riboflavin: 0.22,
                niacin: 5.8,
                vitaminB6: 0.32,
                vitaminB12: 4.8,
                folate: 65,
                calcium: 125,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 225,
                potassium: 485,
                sodium: 985,
                zinc: 2.8,
                selenium: 22.5,
                omega3: 2.8,
                omega6: 6.8,
                cholesterol: 145
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Layered salad with herring, vegetables, and mayonnaise",
            nameFr: "Hareng Sous Manteau de Fourrure",
            nameEs: "Arenque Bajo Abrigo de Piel",
            nameHe: "הרינג תחת מעיל פרווה",
            notesFr: "Salade en couches avec hareng, légumes et mayonnaise",
            notesEs: "Ensalada en capas con arenque, verduras y mayonesa",
            notesHe: "סלט בשכבות עם הרינג, ירקות ומיונז"
        ),
        
        // Kasha
        FoodItem(
            id: UUID(),
            name: "Buckwheat Kasha",
            category: .grains,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 6.8,
                carbohydrates: 35,
                fat: 2.8,
                fiber: 5.2,
                sugar: 2.5,
                vitaminA: 25,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 1.8,
                vitaminK: 15,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 4.2,
                vitaminB6: 0.25,
                vitaminB12: 0,
                folate: 85,
                calcium: 85,
                iron: 2.8,
                magnesium: 125,
                phosphorus: 185,
                potassium: 385,
                sodium: 285,
                zinc: 2.2,
                selenium: 12.5,
                omega3: 0.5,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Buckwheat porridge with butter and onions",
            nameFr: "Kasha de Sarrasin",
            nameEs: "Kasha de Trigo Sarraceno",
            nameHe: "קאשה כוסמת",
            notesFr: "Bouillie de sarrasin avec beurre et oignons",
            notesEs: "Gachas de trigo sarraceno con mantequilla y cebollas",
            notesHe: "דייסת כוסמת עם חמאה ובצל"
        ),
        
        // Russian Meatballs
        FoodItem(
            id: UUID(),
            name: "Russian Meatballs (Tefteli)",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 20.5,
                carbohydrates: 12,
                fat: 18.8,
                fiber: 1.8,
                sugar: 4.5,
                vitaminA: 85,
                vitaminC: 15,
                vitaminD: 0.5,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.22,
                riboflavin: 0.25,
                niacin: 7.8,
                vitaminB6: 0.35,
                vitaminB12: 2.8,
                folate: 35,
                calcium: 85,
                iron: 3.2,
                magnesium: 58,
                phosphorus: 225,
                potassium: 485,
                sodium: 685,
                zinc: 4.2,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 5.2,
                cholesterol: 85
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Large meatballs in tomato sauce with rice filling",
            nameFr: "Boulettes de Viande Russes (Tefteli)",
            nameEs: "Albóndigas Rusas (Tefteli)",
            nameHe: "קציצות רוסיות (טפטלי)",
            notesFr: "Grosses boulettes de viande dans sauce tomate avec farce au riz",
            notesEs: "Albóndigas grandes en salsa de tomate con relleno de arroz",
            notesHe: "קציצות גדולות ברוטב עגבניות עם מילוי אורז"
        ),
        
        // Beef Tongue
        FoodItem(
            id: UUID(),
            name: "Russian Beef Tongue",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 22.5,
                carbohydrates: 3,
                fat: 19.8,
                fiber: 0,
                sugar: 1.5,
                vitaminA: 45,
                vitaminC: 8,
                vitaminD: 0.8,
                vitaminE: 1.8,
                vitaminK: 5,
                thiamin: 0.25,
                riboflavin: 0.35,
                niacin: 6.8,
                vitaminB6: 0.42,
                vitaminB12: 8.8,
                folate: 25,
                calcium: 45,
                iron: 4.8,
                magnesium: 45,
                phosphorus: 185,
                potassium: 385,
                sodium: 485,
                zinc: 5.8,
                selenium: 18.5,
                omega3: 0.3,
                omega6: 2.8,
                cholesterol: 185
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Boiled beef tongue served with horseradish sauce",
            nameFr: "Langue de Bœuf Russe",
            nameEs: "Lengua de Ternera Rusa",
            nameHe: "לשון בקר רוסי",
            notesFr: "Langue de bœuf bouillie servie avec sauce au raifort",
            notesEs: "Lengua de ternera hervida servida con salsa de rábano picante",
            notesHe: "לשון בקר מבושלת מוגשת עם רוטב חזרת"
        ),
        
        // Pryaniki
        FoodItem(
            id: UUID(),
            name: "Pryaniki",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 4.8,
                carbohydrates: 42,
                fat: 5.8,
                fiber: 2.2,
                sugar: 25.5,
                vitaminA: 45,
                vitaminC: 2,
                vitaminD: 0.3,
                vitaminE: 1.8,
                vitaminK: 5,
                thiamin: 0.15,
                riboflavin: 0.12,
                niacin: 2.8,
                vitaminB6: 0.08,
                vitaminB12: 0.3,
                folate: 35,
                calcium: 85,
                iron: 2.2,
                magnesium: 45,
                phosphorus: 125,
                potassium: 185,
                sodium: 285,
                zinc: 1.2,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 2.2,
                cholesterol: 25
            ),
            servingSize: 80,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional spiced honey cookies with various fillings",
            nameFr: "Pryaniki",
            nameEs: "Pryaniki",
            nameHe: "פריאניקי",
            notesFr: "Biscuits traditionnels au miel épicé avec diverses garnitures",
            notesEs: "Galletas tradicionales de miel especiado con varios rellenos",
            notesHe: "עוגיות דבש מתובלות מסורתיות עם מילויים שונים"
        ),
        
        // Caviar Appetizer
        FoodItem(
            id: UUID(),
            name: "Russian Caviar Appetizer",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 12.8,
                carbohydrates: 15,
                fat: 9.8,
                fiber: 1.2,
                sugar: 2.5,
                vitaminA: 185,
                vitaminC: 8,
                vitaminD: 2.8,
                vitaminE: 2.8,
                vitaminK: 15,
                thiamin: 0.15,
                riboflavin: 0.22,
                niacin: 3.8,
                vitaminB6: 0.25,
                vitaminB12: 6.8,
                folate: 45,
                calcium: 125,
                iron: 2.8,
                magnesium: 45,
                phosphorus: 225,
                potassium: 285,
                sodium: 885,
                zinc: 2.8,
                selenium: 22.5,
                omega3: 3.8,
                omega6: 1.8,
                cholesterol: 385
            ),
            servingSize: 50,
            servingUnit: "g",
            isCustom: true,
            notes: "Black or red caviar served on blinis with sour cream",
            nameFr: "Apéritif au Caviar Russe",
            nameEs: "Aperitivo de Caviar Ruso",
            nameHe: "מתאבן קוויאר רוסי",
            notesFr: "Caviar noir ou rouge servi sur blinis avec crème aigre",
            notesEs: "Caviar negro o rojo servido en blinis con crema agria",
            notesHe: "קוויאר שחור או אדום מוגש על בליני עם קרם חמוץ"
        ),
        
        // Beef Stew
        FoodItem(
            id: UUID(),
            name: "Russian Beef Stew (Tushenka)",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 345,
                protein: 26.5,
                carbohydrates: 18,
                fat: 20.8,
                fiber: 3.2,
                sugar: 8.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0.5,
                vitaminE: 2.8,
                vitaminK: 45,
                thiamin: 0.25,
                riboflavin: 0.28,
                niacin: 9.8,
                vitaminB6: 0.48,
                vitaminB12: 3.8,
                folate: 55,
                calcium: 125,
                iron: 4.2,
                magnesium: 85,
                phosphorus: 285,
                potassium: 685,
                sodium: 785,
                zinc: 5.8,
                selenium: 25.8,
                omega3: 0.5,
                omega6: 5.2,
                cholesterol: 105
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: true,
            notes: "Slow-cooked beef stew with root vegetables and herbs",
            nameFr: "Ragoût de Bœuf Russe (Tushenka)",
            nameEs: "Estofado de Ternera Ruso (Tushenka)",
            nameHe: "תבשיל בקר רוסי (טושנקה)",
            notesFr: "Ragoût de bœuf mijoté avec légumes racines et herbes",
            notesEs: "Estofado de ternera cocido lentamente con verduras de raíz y hierbas",
            notesHe: "תבשיל בקר מבושל איטי עם ירקות שורש ועשבי תיבול"
        ),
        
        // Potato Pancakes
        FoodItem(
            id: UUID(),
            name: "Russian Potato Pancakes (Draniki)",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 6.8,
                carbohydrates: 32,
                fat: 8.8,
                fiber: 3.8,
                sugar: 4.5,
                vitaminA: 25,
                vitaminC: 25,
                vitaminD: 0.5,
                vitaminE: 2.2,
                vitaminK: 15,
                thiamin: 0.18,
                riboflavin: 0.12,
                niacin: 3.2,
                vitaminB6: 0.32,
                vitaminB12: 0.8,
                folate: 45,
                calcium: 85,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 145,
                potassium: 585,
                sodium: 485,
                zinc: 1.8,
                selenium: 8.5,
                omega3: 0.3,
                omega6: 3.8,
                cholesterol: 65
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Crispy potato pancakes served with sour cream or applesauce",
            nameFr: "Crêpes de Pommes de Terre Russes (Draniki)",
            nameEs: "Panqueques de Papa Rusos (Draniki)",
            nameHe: "לביבות תפוחי אדמה רוסיות (דראניקי)",
            notesFr: "Crêpes de pommes de terre croustillantes servies avec crème aigre ou compote",
            notesEs: "Panqueques crujientes de papa servidos con crema agria o puré de manzana",
            notesHe: "לביבות תפוחי אדמה פריכות מוגשות עם קרם חמוץ או רסק תפוחים"
        ),
        
        // Pickled Vegetables
        FoodItem(
            id: UUID(),
            name: "Russian Pickled Vegetables",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 45,
                protein: 2.8,
                carbohydrates: 8,
                fat: 0.5,
                fiber: 3.2,
                sugar: 4.5,
                vitaminA: 125,
                vitaminC: 35,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 85,
                thiamin: 0.08,
                riboflavin: 0.08,
                niacin: 1.8,
                vitaminB6: 0.18,
                vitaminB12: 0,
                folate: 45,
                calcium: 85,
                iron: 1.8,
                magnesium: 45,
                phosphorus: 65,
                potassium: 285,
                sodium: 885,
                zinc: 1.2,
                selenium: 5.5,
                omega3: 0.2,
                omega6: 0.3,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Assorted pickled cucumbers, tomatoes, and cabbage",
            nameFr: "Légumes Marinés Russes",
            nameEs: "Verduras Encurtidas Rusas",
            nameHe: "ירקות כבושים רוסיים",
            notesFr: "Assortiment de concombres, tomates et chou marinés",
            notesEs: "Surtido de pepinos, tomates y repollo encurtidos",
            notesHe: "מבחר מלפפונים, עגבניות וכרוב כבושים"
        ),
        
        // Beef and Potato Casserole
        FoodItem(
            id: UUID(),
            name: "Russian Beef and Potato Casserole",
            category: .grains,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 365,
                protein: 22.5,
                carbohydrates: 35,
                fat: 16.8,
                fiber: 4.2,
                sugar: 6.5,
                vitaminA: 185,
                vitaminC: 25,
                vitaminD: 0.8,
                vitaminE: 2.8,
                vitaminK: 45,
                thiamin: 0.28,
                riboflavin: 0.25,
                niacin: 8.8,
                vitaminB6: 0.48,
                vitaminB12: 3.2,
                folate: 65,
                calcium: 185,
                iron: 4.2,
                magnesium: 85,
                phosphorus: 285,
                potassium: 685,
                sodium: 785,
                zinc: 5.2,
                selenium: 22.5,
                omega3: 0.5,
                omega6: 4.8,
                cholesterol: 95
            ),
            servingSize: 220,
            servingUnit: "g",
            isCustom: true,
            notes: "Layered casserole with beef, potatoes, and cheese",
            nameFr: "Gratin de Bœuf et Pommes de Terre Russe",
            nameEs: "Cazuela Rusa de Ternera y Papas",
            nameHe: "קסרול בקר ותפוחי אדמה רוסי",
            notesFr: "Gratin en couches avec bœuf, pommes de terre et fromage",
            notesEs: "Cazuela en capas con ternera, papas y queso",
            notesHe: "קסרול בשכבות עם בקר, תפוחי אדמה וגבינה"
        ),
        
        // Mushroom Julienne
        FoodItem(
            id: UUID(),
            name: "Mushroom Julienne",
            category: .vegetables,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 225,
                protein: 12.8,
                carbohydrates: 12,
                fat: 14.8,
                fiber: 3.2,
                sugar: 6.5,
                vitaminA: 125,
                vitaminC: 15,
                vitaminD: 2.8,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.18,
                riboflavin: 0.25,
                niacin: 4.8,
                vitaminB6: 0.22,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 285,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 185,
                potassium: 485,
                sodium: 585,
                zinc: 2.8,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 4.2,
                cholesterol: 65
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: true,
            notes: "Baked mushrooms in cream sauce with cheese topping",
            nameFr: "Julienne de Champignons",
            nameEs: "Juliana de Champiñones",
            nameHe: "ג'וליין פטריות",
            notesFr: "Champignons cuits dans sauce crémeuse avec garniture au fromage",
            notesEs: "Champiñones horneados en salsa cremosa con cobertura de queso",
            notesHe: "פטריות אפויות ברוטב קרמי עם ציפוי גבינה"
        ),
        
        // Fish Cutlets
        FoodItem(
            id: UUID(),
            name: "Russian Fish Cutlets",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 245,
                protein: 22.5,
                carbohydrates: 15,
                fat: 12.8,
                fiber: 1.8,
                sugar: 3.5,
                vitaminA: 85,
                vitaminC: 12,
                vitaminD: 3.8,
                vitaminE: 2.2,
                vitaminK: 15,
                thiamin: 0.18,
                riboflavin: 0.15,
                niacin: 6.8,
                vitaminB6: 0.35,
                vitaminB12: 4.2,
                folate: 35,
                calcium: 125,
                iron: 2.2,
                magnesium: 65,
                phosphorus: 285,
                potassium: 485,
                sodium: 585,
                zinc: 2.8,
                selenium: 28.5,
                omega3: 2.8,
                omega6: 3.2,
                cholesterol: 85
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Pan-fried fish patties with herbs and breadcrumbs",
            nameFr: "Galettes de Poisson Russes",
            nameEs: "Hamburguesas de Pescado Rusas",
            nameHe: "קציצות דגים רוסיות",
            notesFr: "Galettes de poisson poêlées avec herbes et chapelure",
            notesEs: "Hamburguesas de pescado fritas con hierbas y pan rallado",
            notesHe: "קציצות דגים מטוגנות עם עשבי תיבול ופירורי לחם"
        ),
        
        // Pirozhki
        FoodItem(
            id: UUID(),
            name: "Pirozhki",
            category: .grains,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 285,
                protein: 12.8,
                carbohydrates: 35,
                fat: 11.8,
                fiber: 3.2,
                sugar: 5.5,
                vitaminA: 125,
                vitaminC: 12,
                vitaminD: 0.8,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.22,
                riboflavin: 0.18,
                niacin: 4.8,
                vitaminB6: 0.25,
                vitaminB12: 1.2,
                folate: 85,
                calcium: 125,
                iron: 3.2,
                magnesium: 65,
                phosphorus: 185,
                potassium: 385,
                sodium: 585,
                zinc: 2.8,
                selenium: 15.5,
                omega3: 0.3,
                omega6: 4.2,
                cholesterol: 65
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Baked or fried pastries filled with meat, vegetables, or fruit",
            nameFr: "Pirozhki",
            nameEs: "Pirozhki",
            nameHe: "פירוז'קי",
            notesFr: "Pâtisseries cuites ou frites farcies à la viande, légumes ou fruits",
            notesEs: "Pasteles horneados o fritos rellenos de carne, verduras o fruta",
            notesHe: "מאפים אפויים או מטוגנים ממולאים בשר, ירקות או פירות"
        ),
        
        // Beef Liver Stroganoff
        FoodItem(
            id: UUID(),
            name: "Beef Liver Stroganoff",
            category: .protein,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 325,
                protein: 28.5,
                carbohydrates: 12,
                fat: 18.8,
                fiber: 1.8,
                sugar: 5.5,
                vitaminA: 2285,
                vitaminC: 25,
                vitaminD: 1.2,
                vitaminE: 2.2,
                vitaminK: 25,
                thiamin: 0.35,
                riboflavin: 2.85,
                niacin: 18.8,
                vitaminB6: 1.25,
                vitaminB12: 85.8,
                folate: 285,
                calcium: 125,
                iron: 18.8,
                magnesium: 85,
                phosphorus: 485,
                potassium: 585,
                sodium: 785,
                zinc: 8.8,
                selenium: 45.8,
                omega3: 0.5,
                omega6: 4.8,
                cholesterol: 485
            ),
            servingSize: 180,
            servingUnit: "g",
            isCustom: true,
            notes: "Sliced beef liver in creamy mushroom and onion sauce",
            nameFr: "Foie de Bœuf Stroganoff",
            nameEs: "Hígado de Ternera Stroganoff",
            nameHe: "כבד בקר סטרוגנוף",
            notesFr: "Foie de bœuf tranché dans sauce crémeuse aux champignons et oignons",
            notesEs: "Hígado de ternera en rodajas en salsa cremosa de champiñones y cebolla",
            notesHe: "כבד בקר פרוס ברוטב קרמי של פטריות ובצל"
        ),
        
        // Tvorog
        FoodItem(
            id: UUID(),
            name: "Tvorog with Honey",
            category: .dairy,
            cuisineType: .russian,
            nutritionalInfo: NutritionalInfo(
                calories: 185,
                protein: 16.8,
                carbohydrates: 12,
                fat: 8.8,
                fiber: 0,
                sugar: 12,
                vitaminA: 125,
                vitaminC: 2,
                vitaminD: 1.2,
                vitaminE: 0.8,
                vitaminK: 2,
                thiamin: 0.08,
                riboflavin: 0.35,
                niacin: 1.2,
                vitaminB6: 0.12,
                vitaminB12: 2.8,
                folate: 25,
                calcium: 385,
                iron: 0.8,
                magnesium: 45,
                phosphorus: 285,
                potassium: 285,
                sodium: 185,
                zinc: 2.2,
                selenium: 15.5,
                omega3: 0.3,
                omega6: 1.8,
                cholesterol: 45
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Fresh cottage cheese served with honey and berries",
            nameFr: "Tvorog au Miel",
            nameEs: "Tvorog con Miel",
            nameHe: "טבורוג עם דבש",
            notesFr: "Fromage blanc frais servi avec miel et baies",
            notesEs: "Requesón fresco servido con miel y bayas",
            notesHe: "גבינת קוטג' טרייה מוגשת עם דבש ופירות יער"
        ),
        
        // Medovik
        FoodItem(
            id: UUID(),
            name: "Medovik (Honey Cake)",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 385,
                protein: 8.8,
                carbohydrates: 58,
                fat: 14.8,
                fiber: 2.2,
                sugar: 42.5,
                vitaminA: 185,
                vitaminC: 5,
                vitaminD: 1.2,
                vitaminE: 2.8,
                vitaminK: 8,
                thiamin: 0.18,
                riboflavin: 0.28,
                niacin: 3.2,
                vitaminB6: 0.12,
                vitaminB12: 1.8,
                folate: 45,
                calcium: 185,
                iron: 2.8,
                magnesium: 65,
                phosphorus: 185,
                potassium: 285,
                sodium: 385,
                zinc: 1.8,
                selenium: 12.5,
                omega3: 0.3,
                omega6: 4.8,
                cholesterol: 125
            ),
            servingSize: 120,
            servingUnit: "g",
            isCustom: true,
            notes: "Traditional layered honey cake with sour cream frosting",
            nameFr: "Medovik (Gâteau au Miel)",
            nameEs: "Medovik (Pastel de Miel)",
            nameHe: "מדוביק (עוגת דבש)",
            notesFr: "Gâteau traditionnel en couches au miel avec glaçage à la crème aigre",
            notesEs: "Pastel tradicional en capas de miel con glaseado de crema agria",
            notesHe: "עוגת דבש מסורתית בשכבות עם ציפוי קרם חמוץ"
        )
    ]
}
