import Foundation

struct SampleFoodData {
    static let foods: [FoodItem] = [
        // MARK: - Vegetables
        FoodItem(
            id: UUID(),
            name: "Cooked Green Peas",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 84,
                protein: 5.4,
                carbohydrates: 15,
                fat: 0.4,
                fiber: 5.5,
                sugar: 5.7,
                vitaminA: 765,
                vitaminC: 9.8,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 24.8,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.1,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 65,
                calcium: 25,
                iron: 1.5,
                magnesium: 33,
                phosphorus: 117,
                potassium: 244,
                sodium: 5,
                zinc: 1.2,
                selenium: 1.8,
                omega3: 0.03,
                omega6: 0.07,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked green peas (medium portion). Small = 75g, Large = 150g"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Broccoli",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 34,
                protein: 2.8,
                carbohydrates: 6.6,
                fat: 0.4,
                fiber: 2.6,
                sugar: 1.7,
                vitaminA: 623,
                vitaminC: 89.2,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 101.6,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.6,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 63,
                calcium: 47,
                iron: 0.7,
                magnesium: 21,
                phosphorus: 66,
                potassium: 316,
                sodium: 33,
                zinc: 0.4,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw broccoli florets"
        ),

        // Add other vegetables here...

        // MARK: - Protein
        FoodItem(
            id: UUID(),
            name: "Beef Stew",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 275,
                protein: 22.5,
                carbohydrates: 17.5,
                fat: 13.5,
                fiber: 2.5,
                sugar: 3.5,
                vitaminA: 800,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 10,
                thiamin: 0.2,
                riboflavin: 0.3,
                niacin: 4.0,
                vitaminB6: 0.4,
                vitaminB12: 2.0,
                folate: 30,
                calcium: 50,
                iron: 3.5,
                magnesium: 40,
                phosphorus: 200,
                potassium: 600,
                sodium: 750,
                zinc: 4.0,
                selenium: 20,
                omega3: 0.2,
                omega6: 0.5,
                cholesterol: 70
            ),
            servingSize: 240,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional beef stew with vegetables in broth (1 cup serving)"
        ),

        // Add other protein items here...

        // MARK: - Grains
        FoodItem(
            id: UUID(),
            name: "Oatmeal",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 150,
                protein: 5,
                carbohydrates: 27,
                fat: 3,
                fiber: 4,
                sugar: 1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 20,
                calcium: 20,
                iron: 2,
                magnesium: 60,
                phosphorus: 150,
                potassium: 150,
                sodium: 0,
                zinc: 1.5,
                selenium: 10,
                omega3: 0.1,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked oatmeal, plain"
        ),
        
        // Mediterranean Foods
        FoodItem(
            id: UUID(),
            name: "Greek Salad",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 150,
                protein: 4,
                carbohydrates: 8,
                fat: 12,
                fiber: 3,
                sugar: 4,
                vitaminA: 1200,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 2.5,
                vitaminK: 45,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 1.2,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 35,
                calcium: 120,
                iron: 1.2,
                magnesium: 25,
                phosphorus: 60,
                potassium: 350,
                sodium: 400,
                zinc: 0.5,
                selenium: 2,
                omega3: 0.3,
                omega6: 1.2,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional Greek salad with feta cheese, olives, and olive oil"
        ),
        
        // Asian Foods
        FoodItem(
            id: UUID(),
            name: "Sushi Roll (California)",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 255,
                protein: 9,
                carbohydrates: 38,
                fat: 7,
                fiber: 1,
                sugar: 6,
                vitaminA: 200,
                vitaminC: 8,
                vitaminD: 0,
                vitaminE: 1.2,
                vitaminK: 2,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 2.5,
                vitaminB6: 0.3,
                vitaminB12: 0.8,
                folate: 45,
                calcium: 20,
                iron: 1.5,
                magnesium: 35,
                phosphorus: 120,
                potassium: 180,
                sodium: 500,
                zinc: 1.2,
                selenium: 15,
                omega3: 0.8,
                omega6: 0.4,
                cholesterol: 25
            ),
            servingSize: 150,
            servingUnit: "g",
            isCustom: false,
            notes: "California roll with crab, avocado, and cucumber"
        ),
        
        // Indian Foods
        FoodItem(
            id: UUID(),
            name: "Chicken Curry",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 320,
                protein: 25,
                carbohydrates: 15,
                fat: 18,
                fiber: 3,
                sugar: 4,
                vitaminA: 800,
                vitaminC: 25,
                vitaminD: 0,
                vitaminE: 2,
                vitaminK: 5,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 8,
                vitaminB6: 0.5,
                vitaminB12: 0.6,
                folate: 30,
                calcium: 60,
                iron: 2.5,
                magnesium: 45,
                phosphorus: 200,
                potassium: 450,
                sodium: 600,
                zinc: 2.5,
                selenium: 20,
                omega3: 0.4,
                omega6: 2.5,
                cholesterol: 85
            ),
            servingSize: 250,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional Indian curry with chicken and spices"
        ),
        
        // Mexican Foods
        FoodItem(
            id: UUID(),
            name: "Bean Burrito",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 380,
                protein: 15,
                carbohydrates: 58,
                fat: 12,
                fiber: 8,
                sugar: 3,
                vitaminA: 400,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 8,
                thiamin: 0.3,
                riboflavin: 0.2,
                niacin: 3.5,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 120,
                calcium: 200,
                iron: 4.5,
                magnesium: 85,
                phosphorus: 250,
                potassium: 600,
                sodium: 800,
                zinc: 2.8,
                selenium: 15,
                omega3: 0.2,
                omega6: 1.8,
                cholesterol: 0
            ),
            servingSize: 200,
            servingUnit: "g",
            isCustom: false,
            notes: "Bean burrito with rice, beans, and vegetables"
        ),
        
        // Middle Eastern Foods
        FoodItem(
            id: UUID(),
            name: "Hummus",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 166,
                protein: 8,
                carbohydrates: 14,
                fat: 10,
                fiber: 6,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 2,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.8,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 60,
                calcium: 40,
                iron: 2.5,
                magnesium: 50,
                phosphorus: 120,
                potassium: 200,
                sodium: 400,
                zinc: 1.5,
                selenium: 3,
                omega3: 0.1,
                omega6: 2.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional chickpea dip with tahini and olive oil"
        ),
        
        // Traditional American Foods
        FoodItem(
            id: UUID(),
            name: "Grilled Chicken Breast",
            category: .protein,
            nutritionalInfo: NutritionalInfo(
                calories: 165,
                protein: 31,
                carbohydrates: 0,
                fat: 3.6,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.2,
                niacin: 14,
                vitaminB6: 0.6,
                vitaminB12: 0.3,
                folate: 4,
                calcium: 15,
                iron: 1,
                magnesium: 30,
                phosphorus: 230,
                potassium: 300,
                sodium: 70,
                zinc: 1,
                selenium: 25,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 85
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Skinless, boneless chicken breast"
        ),
        
        // Japanese Foods
        FoodItem(
            id: UUID(),
            name: "Miso Soup",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 40,
                protein: 2,
                carbohydrates: 5,
                fat: 1.5,
                fiber: 1,
                sugar: 1,
                vitaminA: 100,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 2,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 10,
                calcium: 20,
                iron: 0.5,
                magnesium: 15,
                phosphorus: 30,
                potassium: 100,
                sodium: 800,
                zinc: 0.3,
                selenium: 5,
                omega3: 0.1,
                omega6: 0.3,
                cholesterol: 0
            ),
            servingSize: 250,
            servingUnit: "ml",
            isCustom: false,
            notes: "Traditional Japanese soup with miso paste and tofu"
        ),
        
        // Italian Foods
        FoodItem(
            id: UUID(),
            name: "Whole Wheat Pasta",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 174,
                protein: 7.5,
                carbohydrates: 37,
                fat: 0.8,
                fiber: 6,
                sugar: 1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 0.1,
                niacin: 3,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 40,
                calcium: 20,
                iron: 2.5,
                magnesium: 60,
                phosphorus: 150,
                potassium: 200,
                sodium: 5,
                zinc: 1.2,
                selenium: 30,
                omega3: 0.1,
                omega6: 0.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked whole wheat pasta"
        ),
        
        // Chinese Foods
        FoodItem(
            id: UUID(),
            name: "Steamed Rice",
            category: .grains,
            nutritionalInfo: NutritionalInfo(
                calories: 130,
                protein: 2.7,
                carbohydrates: 28,
                fat: 0.3,
                fiber: 0.4,
                sugar: 0.1,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0,
                niacin: 1.6,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 8,
                calcium: 10,
                iron: 0.2,
                magnesium: 12,
                phosphorus: 43,
                potassium: 35,
                sodium: 1,
                zinc: 0.5,
                selenium: 15,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Cooked white rice"
        ),
        
        // Korean Foods
        FoodItem(
            id: UUID(),
            name: "Kimchi",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 23,
                protein: 1.1,
                carbohydrates: 4.5,
                fat: 0.2,
                fiber: 1.6,
                sugar: 1.1,
                vitaminA: 500,
                vitaminC: 21,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 43,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.5,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 24,
                calcium: 33,
                iron: 1.1,
                magnesium: 14,
                phosphorus: 24,
                potassium: 151,
                sodium: 498,
                zinc: 0.2,
                selenium: 0.6,
                omega3: 0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Traditional Korean fermented vegetables"
        ),
        
        // Fruits
        FoodItem(
            id: UUID(),
            name: "Apple",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 95,
                protein: 0.5,
                carbohydrates: 25,
                fat: 0.3,
                fiber: 4.5,
                sugar: 19,
                vitaminA: 54,
                vitaminC: 8.4,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 2.2,
                thiamin: 0.02,
                riboflavin: 0.03,
                niacin: 0.1,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 5,
                calcium: 11,
                iron: 0.2,
                magnesium: 9,
                phosphorus: 20,
                potassium: 195,
                sodium: 2,
                zinc: 0.1,
                selenium: 0,
                omega3: 0.01,
                omega6: 0.04,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Medium-sized apple with skin"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Banana",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 105,
                protein: 1.3,
                carbohydrates: 27,
                fat: 0.3,
                fiber: 3.1,
                sugar: 14,
                vitaminA: 64,
                vitaminC: 10.3,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0.5,
                thiamin: 0.03,
                riboflavin: 0.1,
                niacin: 0.8,
                vitaminB6: 0.4,
                vitaminB12: 0,
                folate: 24,
                calcium: 6,
                iron: 0.3,
                magnesium: 32,
                phosphorus: 26,
                potassium: 422,
                sodium: 1,
                zinc: 0.2,
                selenium: 1,
                omega3: 0.03,
                omega6: 0.05,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Medium-sized banana"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Orange",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 62,
                protein: 1.2,
                carbohydrates: 15.4,
                fat: 0.2,
                fiber: 3.1,
                sugar: 12.2,
                vitaminA: 225,
                vitaminC: 53.2,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.04,
                niacin: 0.4,
                vitaminB6: 0.06,
                vitaminB12: 0,
                folate: 30,
                calcium: 43,
                iron: 0.1,
                magnesium: 12,
                phosphorus: 23,
                potassium: 181,
                sodium: 0,
                zinc: 0.1,
                selenium: 0.5,
                omega3: 0.01,
                omega6: 0.02,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Medium-sized orange"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Strawberries",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 32,
                protein: 0.7,
                carbohydrates: 7.7,
                fat: 0.3,
                fiber: 2,
                sugar: 4.9,
                vitaminA: 12,
                vitaminC: 58.8,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 2.2,
                thiamin: 0.02,
                riboflavin: 0.02,
                niacin: 0.4,
                vitaminB6: 0.05,
                vitaminB12: 0,
                folate: 24,
                calcium: 16,
                iron: 0.4,
                magnesium: 13,
                phosphorus: 24,
                potassium: 153,
                sodium: 1,
                zinc: 0.1,
                selenium: 0.4,
                omega3: 0.07,
                omega6: 0.09,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh strawberries"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Blueberries",
            category: .fruits,
            nutritionalInfo: NutritionalInfo(
                calories: 57,
                protein: 0.7,
                carbohydrates: 14.5,
                fat: 0.3,
                fiber: 2.4,
                sugar: 10,
                vitaminA: 54,
                vitaminC: 9.7,
                vitaminD: 0,
                vitaminE: 0.6,
                vitaminK: 19.3,
                thiamin: 0.04,
                riboflavin: 0.04,
                niacin: 0.4,
                vitaminB6: 0.05,
                vitaminB12: 0,
                folate: 6,
                calcium: 6,
                iron: 0.3,
                magnesium: 6,
                phosphorus: 12,
                potassium: 77,
                sodium: 1,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0.06,
                omega6: 0.09,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fresh blueberries"
        ),
        
        // Dairy
        FoodItem(
            id: UUID(),
            name: "Low-Fat Milk",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 42,
                protein: 3.4,
                carbohydrates: 5,
                fat: 1,
                fiber: 0,
                sugar: 5,
                vitaminA: 46,
                vitaminC: 1,
                vitaminD: 1.2,
                vitaminE: 0.1,
                vitaminK: 0.1,
                thiamin: 0.04,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.5,
                folate: 5,
                calcium: 125,
                iron: 0.1,
                magnesium: 11,
                phosphorus: 95,
                potassium: 150,
                sodium: 42,
                zinc: 0.4,
                selenium: 3.3,
                omega3: 0.01,
                omega6: 0.02,
                cholesterol: 5
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "1% low-fat milk"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Greek Yogurt",
            category: .dairy,
            nutritionalInfo: NutritionalInfo(
                calories: 59,
                protein: 10.3,
                carbohydrates: 3.6,
                fat: 0.4,
                fiber: 0,
                sugar: 3.6,
                vitaminA: 4,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 0,
                thiamin: 0.03,
                riboflavin: 0.2,
                niacin: 0.1,
                vitaminB6: 0.05,
                vitaminB12: 0.2,
                folate: 7,
                calcium: 111,
                iron: 0.1,
                magnesium: 11,
                phosphorus: 135,
                potassium: 141,
                sodium: 36,
                zinc: 0.5,
                selenium: 9.7,
                omega3: 0.01,
                omega6: 0.01,
                cholesterol: 5
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Plain, non-fat Greek yogurt"
        ),
        
        // Fats
        FoodItem(
            id: UUID(),
            name: "Olive Oil",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 884,
                protein: 0,
                carbohydrates: 0,
                fat: 100,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 14.4,
                vitaminK: 60.2,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 1,
                iron: 0.6,
                magnesium: 0,
                phosphorus: 0,
                potassium: 1,
                sodium: 2,
                zinc: 0,
                selenium: 0,
                omega3: 0.8,
                omega6: 9.8,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Extra virgin olive oil"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Almonds",
            category: .fats,
            nutritionalInfo: NutritionalInfo(
                calories: 579,
                protein: 21.2,
                carbohydrates: 21.7,
                fat: 49.9,
                fiber: 12.5,
                sugar: 4.4,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 25.6,
                vitaminK: 0,
                thiamin: 0.2,
                riboflavin: 1.1,
                niacin: 3.6,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 44,
                calcium: 269,
                iron: 3.7,
                magnesium: 270,
                phosphorus: 481,
                potassium: 733,
                sodium: 1,
                zinc: 3.1,
                selenium: 4.1,
                omega3: 0.1,
                omega6: 12.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Raw almonds"
        ),
        
        // Beverages
        FoodItem(
            id: UUID(),
            name: "Plain Water",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 0,
                protein: 0,
                carbohydrates: 0,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 0,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0,
                niacin: 0,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0,
                magnesium: 0,
                phosphorus: 0,
                potassium: 0,
                sodium: 0,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Filtered water"
        ),
        
        FoodItem(
            id: UUID(),
            name: "Green Tea",
            category: .beverages,
            nutritionalInfo: NutritionalInfo(
                calories: 1,
                protein: 0.2,
                carbohydrates: 0.2,
                fat: 0,
                fiber: 0,
                sugar: 0,
                vitaminA: 0,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0,
                vitaminK: 0,
                thiamin: 0,
                riboflavin: 0.1,
                niacin: 0.1,
                vitaminB6: 0,
                vitaminB12: 0,
                folate: 0,
                calcium: 0,
                iron: 0.1,
                magnesium: 2,
                phosphorus: 0,
                potassium: 27,
                sodium: 1,
                zinc: 0,
                selenium: 0,
                omega3: 0,
                omega6: 0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "ml",
            isCustom: false,
            notes: "Brewed green tea"
        ),
        
        // Snacks
        FoodItem(
            id: UUID(),
            name: "Whole-Grain Crackers with Hummus",
            category: .snacks,
            nutritionalInfo: NutritionalInfo(
                calories: 180,
                protein: 5,
                carbohydrates: 25,
                fat: 7,
                fiber: 4,
                sugar: 2,
                vitaminA: 0,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 1,
                vitaminK: 0,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 1.5,
                vitaminB6: 0.1,
                vitaminB12: 0,
                folate: 20,
                calcium: 30,
                iron: 1.5,
                magnesium: 40,
                phosphorus: 100,
                potassium: 150,
                sodium: 300,
                zinc: 1,
                selenium: 10,
                omega3: 0.1,
                omega6: 1.5,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Whole-grain crackers with hummus spread"
        ),
        
        // Other
        FoodItem(
            id: UUID(),
            name: "Fortified Multigrain Cereal",
            category: .other,
            nutritionalInfo: NutritionalInfo(
                calories: 350,
                protein: 10,
                carbohydrates: 75,
                fat: 2,
                fiber: 8,
                sugar: 12,
                vitaminA: 500,
                vitaminC: 60,
                vitaminD: 3,
                vitaminE: 20,
                vitaminK: 0,
                thiamin: 1.5,
                riboflavin: 1.7,
                niacin: 20,
                vitaminB6: 2,
                vitaminB12: 6,
                folate: 400,
                calcium: 1000,
                iron: 18,
                magnesium: 100,
                phosphorus: 300,
                potassium: 300,
                sodium: 300,
                zinc: 15,
                selenium: 20,
                omega3: 0.5,
                omega6: 2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: false,
            notes: "Fortified multigrain breakfast cereal"
        )
    ]
    
    // Helper method to add new food items
    static func addFood(name: String, category: FoodCategory, nutritionalInfo: NutritionalInfo, servingSize: Double, servingUnit: String, notes: String? = nil) -> FoodItem {
        return FoodItem(
            id: UUID(),
            name: name,
            category: category,
            nutritionalInfo: nutritionalInfo,
            servingSize: servingSize,
            servingUnit: servingUnit,
            isCustom: true,
            notes: notes
        )
    }
} 