import Foundation

struct VegetableFoodItems {
    static let foods: [FoodItem] = [
        // Broccoli
        FoodItem(
            id: UUID(),
            name: "Broccoli",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 34,
                protein: 2.8,
                carbohydrates: 7,
                fat: 0.4,
                fiber: 2.6,
                sugar: 1.5,
                vitaminA: 623,
                vitaminC: 89,
                vitaminD: 0,
                vitaminE: 0.8,
                vitaminK: 102,
                thiamin: 0.07,
                riboflavin: 0.12,
                niacin: 0.6,
                vitaminB6: 0.18,
                vitaminB12: 0,
                folate: 63,
                calcium: 47,
                iron: 0.7,
                magnesium: 21,
                phosphorus: 66,
                potassium: 316,
                sodium: 33,
                zinc: 0.4,
                selenium: 2.5,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Rich in vitamin C and fiber, excellent steamed or roasted",
            nameFr: "Brocoli",
            nameEs: "Brócoli",
            nameHe: "ברוקולי",
            notesFr: "Riche en vitamine C et fibres, excellent à la vapeur ou rôti",
            notesEs: "Rico en vitamina C y fibra, excelente al vapor o asado",
            notesHe: "עשיר בוויטמין C וסיבים, מעולה מאודה או צלוי"
        ),
        
        // Spinach
        FoodItem(
            id: UUID(),
            name: "Spinach",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 23,
                protein: 2.9,
                carbohydrates: 3.6,
                fat: 0.4,
                fiber: 2.2,
                sugar: 0.4,
                vitaminA: 469,
                vitaminC: 28,
                vitaminD: 0,
                vitaminE: 2.0,
                vitaminK: 483,
                thiamin: 0.08,
                riboflavin: 0.19,
                niacin: 0.7,
                vitaminB6: 0.2,
                vitaminB12: 0,
                folate: 194,
                calcium: 99,
                iron: 2.7,
                magnesium: 79,
                phosphorus: 49,
                potassium: 558,
                sodium: 79,
                zinc: 0.5,
                selenium: 1,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in iron and folate, great in salads or cooked dishes",
            nameFr: "Épinards",
            nameEs: "Espinacas",
            nameHe: "תרד",
            notesFr: "Riche en fer et folate, excellent en salade ou cuit",
            notesEs: "Alto en hierro y folato, excelente en ensaladas o platos cocidos",
            notesHe: "עשיר בברזל וחומצה פולית, מעולה בסלטים או מבושל"
        ),
        
        // Carrots
        FoodItem(
            id: UUID(),
            name: "Carrots",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 41,
                protein: 0.9,
                carbohydrates: 10,
                fat: 0.2,
                fiber: 2.8,
                sugar: 4.7,
                vitaminA: 835,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 0.7,
                vitaminK: 13,
                thiamin: 0.07,
                riboflavin: 0.06,
                niacin: 1.0,
                vitaminB6: 0.14,
                vitaminB12: 0,
                folate: 19,
                calcium: 33,
                iron: 0.3,
                magnesium: 12,
                phosphorus: 35,
                potassium: 320,
                sodium: 69,
                zinc: 0.2,
                selenium: 0.1,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Excellent source of beta-carotene, sweet and crunchy",
            nameFr: "Carottes",
            nameEs: "Zanahorias",
            nameHe: "גזר",
            notesFr: "Excellente source de bêta-carotène, douce et croquante",
            notesEs: "Excelente fuente de beta-caroteno, dulce y crujiente",
            notesHe: "מקור מעולה לבטא-קרוטן, מתוק ופריך"
        ),
        
        // Bell Peppers (Red)
        FoodItem(
            id: UUID(),
            name: "Red Bell Peppers",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 1.0,
                carbohydrates: 7,
                fat: 0.3,
                fiber: 2.5,
                sugar: 4.2,
                vitaminA: 157,
                vitaminC: 128,
                vitaminD: 0,
                vitaminE: 1.6,
                vitaminK: 5,
                thiamin: 0.05,
                riboflavin: 0.09,
                niacin: 1.0,
                vitaminB6: 0.29,
                vitaminB12: 0,
                folate: 46,
                calcium: 7,
                iron: 0.4,
                magnesium: 12,
                phosphorus: 26,
                potassium: 211,
                sodium: 4,
                zinc: 0.3,
                selenium: 0.1,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very high in vitamin C, sweet and colorful",
            nameFr: "Poivrons rouges",
            nameEs: "Pimientos rojos",
            nameHe: "פלפל אדום",
            notesFr: "Très riche en vitamine C, doux et coloré",
            notesEs: "Muy alto en vitamina C, dulce y colorido",
            notesHe: "עשיר מאוד בוויטמין C, מתוק וצבעוני"
        ),
        
        // Tomatoes
        FoodItem(
            id: UUID(),
            name: "Tomatoes",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 18,
                protein: 0.9,
                carbohydrates: 3.9,
                fat: 0.2,
                fiber: 1.2,
                sugar: 2.6,
                vitaminA: 42,
                vitaminC: 14,
                vitaminD: 0,
                vitaminE: 0.5,
                vitaminK: 8,
                thiamin: 0.04,
                riboflavin: 0.02,
                niacin: 0.6,
                vitaminB6: 0.08,
                vitaminB12: 0,
                folate: 15,
                calcium: 10,
                iron: 0.3,
                magnesium: 11,
                phosphorus: 24,
                potassium: 237,
                sodium: 5,
                zinc: 0.2,
                selenium: 0,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Rich in lycopene, versatile for cooking and salads",
            nameFr: "Tomates",
            nameEs: "Tomates",
            nameHe: "עגבניות",
            notesFr: "Riche en lycopène, polyvalent pour la cuisine et les salades",
            notesEs: "Rico en licopeno, versátil para cocinar y ensaladas",
            notesHe: "עשיר בליקופן, רב-תכליתי לבישול וסלטים"
        ),
        
        // Cucumber
        FoodItem(
            id: UUID(),
            name: "Cucumber",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 16,
                protein: 0.7,
                carbohydrates: 4,
                fat: 0.1,
                fiber: 0.5,
                sugar: 1.7,
                vitaminA: 5,
                vitaminC: 3,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 16,
                thiamin: 0.03,
                riboflavin: 0.03,
                niacin: 0.1,
                vitaminB6: 0.04,
                vitaminB12: 0,
                folate: 7,
                calcium: 16,
                iron: 0.3,
                magnesium: 13,
                phosphorus: 24,
                potassium: 147,
                sodium: 2,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very hydrating, low calorie, refreshing in salads",
            nameFr: "Concombre",
            nameEs: "Pepino",
            nameHe: "מלפפון",
            notesFr: "Très hydratant, faible en calories, rafraîchissant en salade",
            notesEs: "Muy hidratante, bajo en calorías, refrescante en ensaladas",
            notesHe: "מאוד מרטיב, דל קלוריות, מרענן בסלטים"
        ),
        
        // Lettuce (Romaine)
        FoodItem(
            id: UUID(),
            name: "Romaine Lettuce",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 17,
                protein: 1.2,
                carbohydrates: 3.3,
                fat: 0.3,
                fiber: 2.1,
                sugar: 1.2,
                vitaminA: 436,
                vitaminC: 4,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 103,
                thiamin: 0.07,
                riboflavin: 0.07,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 136,
                calcium: 33,
                iron: 1.0,
                magnesium: 14,
                phosphorus: 30,
                potassium: 247,
                sodium: 8,
                zinc: 0.2,
                selenium: 0.4,
                omega3: 0.1,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate and vitamin K, crisp texture",
            nameFr: "Laitue romaine",
            nameEs: "Lechuga romana",
            nameHe: "חסה רומית",
            notesFr: "Riche en folate et vitamine K, texture croquante",
            notesEs: "Alto en folato y vitamina K, textura crujiente",
            notesHe: "עשיר בחומצה פולית ווויטמין K, מרקם פריך"
        ),
        
        // Zucchini
        FoodItem(
            id: UUID(),
            name: "Zucchini",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 17,
                protein: 1.2,
                carbohydrates: 3.1,
                fat: 0.3,
                fiber: 1.0,
                sugar: 2.5,
                vitaminA: 10,
                vitaminC: 18,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 4,
                thiamin: 0.05,
                riboflavin: 0.09,
                niacin: 0.5,
                vitaminB6: 0.16,
                vitaminB12: 0,
                folate: 24,
                calcium: 16,
                iron: 0.4,
                magnesium: 18,
                phosphorus: 38,
                potassium: 261,
                sodium: 8,
                zinc: 0.3,
                selenium: 0.2,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild flavor, versatile for grilling, baking, or spiralizing",
            nameFr: "Courgette",
            nameEs: "Calabacín",
            nameHe: "קישוא",
            notesFr: "Saveur douce, polyvalent pour griller, cuire ou spiraler",
            notesEs: "Sabor suave, versátil para asar, hornear o espiralizar",
            notesHe: "טעם עדין, רב-תכליתי לצלייה, אפייה או ספירליזציה"
        ),
        
        // Cauliflower
        FoodItem(
            id: UUID(),
            name: "Cauliflower",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.9,
                carbohydrates: 5,
                fat: 0.3,
                fiber: 2.0,
                sugar: 1.9,
                vitaminA: 0,
                vitaminC: 48,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 16,
                thiamin: 0.05,
                riboflavin: 0.06,
                niacin: 0.5,
                vitaminB6: 0.18,
                vitaminB12: 0,
                folate: 57,
                calcium: 22,
                iron: 0.4,
                magnesium: 15,
                phosphorus: 44,
                potassium: 299,
                sodium: 30,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of vitamin C, great rice substitute when riced",
            nameFr: "Chou-fleur",
            nameEs: "Coliflor",
            nameHe: "כרובית",
            notesFr: "Bonne source de vitamine C, excellent substitut de riz haché",
            notesEs: "Buena fuente de vitamina C, excelente sustituto del arroz rallado",
            notesHe: "מקור טוב לוויטמין C, תחליף מעולה לאורז כשקצוץ"
        ),
        
        // Brussels Sprouts
        FoodItem(
            id: UUID(),
            name: "Brussels Sprouts",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 43,
                protein: 3.4,
                carbohydrates: 9,
                fat: 0.3,
                fiber: 3.8,
                sugar: 2.2,
                vitaminA: 38,
                vitaminC: 85,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 177,
                thiamin: 0.14,
                riboflavin: 0.09,
                niacin: 0.7,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 61,
                calcium: 42,
                iron: 1.4,
                magnesium: 23,
                phosphorus: 69,
                potassium: 389,
                sodium: 25,
                zinc: 0.4,
                selenium: 1.6,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in vitamin K and fiber, delicious roasted with olive oil",
            nameFr: "Choux de Bruxelles",
            nameEs: "Coles de Bruselas",
            nameHe: "כרוב ניצנים",
            notesFr: "Riche en vitamine K et fibres, délicieux rôti à l'huile d'olive",
            notesEs: "Alto en vitamina K y fibra, delicioso asado con aceite de oliva",
            notesHe: "עשיר בוויטמין K וסיבים, טעים צלוי עם שמן זית"
        ),
        
        // Asparagus
        FoodItem(
            id: UUID(),
            name: "Asparagus",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 20,
                protein: 2.2,
                carbohydrates: 3.9,
                fat: 0.1,
                fiber: 2.1,
                sugar: 1.9,
                vitaminA: 38,
                vitaminC: 6,
                vitaminD: 0,
                vitaminE: 1.1,
                vitaminK: 42,
                thiamin: 0.14,
                riboflavin: 0.14,
                niacin: 1.0,
                vitaminB6: 0.09,
                vitaminB12: 0,
                folate: 52,
                calcium: 24,
                iron: 2.1,
                magnesium: 14,
                phosphorus: 52,
                potassium: 202,
                sodium: 2,
                zinc: 0.5,
                selenium: 2.3,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate, elegant vegetable perfect for grilling",
            nameFr: "Asperges",
            nameEs: "Espárragos",
            nameHe: "אספרגוס",
            notesFr: "Riche en folate, légume élégant parfait pour griller",
            notesEs: "Alto en folato, vegetal elegante perfecto para asar",
            notesHe: "עשיר בחומצה פולית, ירק אלגנטי מושלם לצלייה"
        ),
        
        // Green Beans
        FoodItem(
            id: UUID(),
            name: "Green Beans",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 31,
                protein: 1.8,
                carbohydrates: 7,
                fat: 0.2,
                fiber: 2.7,
                sugar: 3.3,
                vitaminA: 35,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 43,
                thiamin: 0.08,
                riboflavin: 0.10,
                niacin: 0.7,
                vitaminB6: 0.14,
                vitaminB12: 0,
                folate: 33,
                calcium: 37,
                iron: 1.0,
                magnesium: 25,
                phosphorus: 38,
                potassium: 211,
                sodium: 6,
                zinc: 0.2,
                selenium: 0.6,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of fiber, tender when steamed or sautéed",
            nameFr: "Haricots verts",
            nameEs: "Judías verdes",
            nameHe: "שעועית ירוקה",
            notesFr: "Bonne source de fibres, tendres à la vapeur ou sautés",
            notesEs: "Buena fuente de fibra, tiernos al vapor o salteados",
            notesHe: "מקור טוב לסיבים, רכים כשמאודים או מוקפצים"
        ),
        
        // Sweet Potato
        FoodItem(
            id: UUID(),
            name: "Sweet Potato",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 86,
                protein: 1.6,
                carbohydrates: 20,
                fat: 0.1,
                fiber: 3.0,
                sugar: 4.2,
                vitaminA: 709,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 2,
                thiamin: 0.08,
                riboflavin: 0.06,
                niacin: 0.6,
                vitaminB6: 0.21,
                vitaminB12: 0,
                folate: 11,
                calcium: 30,
                iron: 0.6,
                magnesium: 25,
                phosphorus: 47,
                potassium: 337,
                sodium: 54,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very high in vitamin A, naturally sweet and nutritious",
            nameFr: "Patate douce",
            nameEs: "Batata",
            nameHe: "בטטה",
            notesFr: "Très riche en vitamine A, naturellement douce et nutritive",
            notesEs: "Muy alto en vitamina A, naturalmente dulce y nutritivo",
            notesHe: "עשיר מאוד בוויטמין A, מתוק באופן טבעי ומזין"
        ),
        
        // Beets
        FoodItem(
            id: UUID(),
            name: "Beets",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 43,
                protein: 1.6,
                carbohydrates: 10,
                fat: 0.2,
                fiber: 2.8,
                sugar: 6.8,
                vitaminA: 2,
                vitaminC: 5,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 0.2,
                thiamin: 0.03,
                riboflavin: 0.04,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 109,
                calcium: 16,
                iron: 0.8,
                magnesium: 23,
                phosphorus: 40,
                potassium: 325,
                sodium: 78,
                zinc: 0.4,
                selenium: 0.7,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate and natural nitrates, earthy sweet flavor",
            nameFr: "Betteraves",
            nameEs: "Remolachas",
            nameHe: "סלק",
            notesFr: "Riche en folate et nitrates naturels, saveur douce terreuse",
            notesEs: "Alto en folato y nitratos naturales, sabor dulce terroso",
            notesHe: "עשיר בחומצה פולית וחנקות טבעיות, טעם מתוק אדמתי"
        ),
        
        // Cabbage
        FoodItem(
            id: UUID(),
            name: "Cabbage",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.3,
                carbohydrates: 6,
                fat: 0.1,
                fiber: 2.5,
                sugar: 3.2,
                vitaminA: 5,
                vitaminC: 37,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 76,
                thiamin: 0.06,
                riboflavin: 0.04,
                niacin: 0.2,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 43,
                calcium: 40,
                iron: 0.5,
                magnesium: 12,
                phosphorus: 26,
                potassium: 170,
                sodium: 18,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of vitamin C and K, excellent for coleslaw",
            nameFr: "Chou",
            nameEs: "Repollo",
            nameHe: "כרוב",
            notesFr: "Bonne source de vitamine C et K, excellent pour la salade de chou",
            notesEs: "Buena fuente de vitamina C y K, excelente para ensalada de col",
            notesHe: "מקור טוב לוויטמין C ו-K, מעולה לסלט כרוב"
        ),
        
        // Kale
        FoodItem(
            id: UUID(),
            name: "Kale",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 49,
                protein: 4.3,
                carbohydrates: 9,
                fat: 0.9,
                fiber: 3.6,
                sugar: 2.3,
                vitaminA: 681,
                vitaminC: 120,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 704,
                thiamin: 0.11,
                riboflavin: 0.13,
                niacin: 1.2,
                vitaminB6: 0.27,
                vitaminB12: 0,
                folate: 141,
                calcium: 150,
                iron: 1.5,
                magnesium: 47,
                phosphorus: 92,
                potassium: 491,
                sodium: 38,
                zinc: 0.6,
                selenium: 0.9,
                omega3: 0.2,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Superfood high in vitamins A, C, and K, great in smoothies",
            nameFr: "Chou frisé",
            nameEs: "Col rizada",
            nameHe: "קייל",
            notesFr: "Superaliment riche en vitamines A, C et K, excellent en smoothies",
            notesEs: "Superalimento alto en vitaminas A, C y K, excelente en batidos",
            notesHe: "סופרפוד עשיר בוויטמינים A, C ו-K, מעולה בשייקים"
        ),
        
        // Radishes
        FoodItem(
            id: UUID(),
            name: "Radishes",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 16,
                protein: 0.7,
                carbohydrates: 3.4,
                fat: 0.1,
                fiber: 1.6,
                sugar: 1.9,
                vitaminA: 0,
                vitaminC: 15,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 1.3,
                thiamin: 0.01,
                riboflavin: 0.04,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 25,
                calcium: 25,
                iron: 0.3,
                magnesium: 10,
                phosphorus: 20,
                potassium: 233,
                sodium: 39,
                zinc: 0.3,
                selenium: 0.6,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Crisp and peppery, adds crunch to salads",
            nameFr: "Radis",
            nameEs: "Rábanos",
            nameHe: "צנון",
            notesFr: "Croquant et poivré, ajoute du croquant aux salades",
            notesEs: "Crujiente y picante, añade textura a las ensaladas",
            notesHe: "פריך וחריף, מוסיף פריכות לסלטים"
        ),
        
        // Celery
        FoodItem(
            id: UUID(),
            name: "Celery",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 14,
                protein: 0.7,
                carbohydrates: 3,
                fat: 0.2,
                fiber: 1.6,
                sugar: 1.3,
                vitaminA: 22,
                vitaminC: 3,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 29,
                thiamin: 0.02,
                riboflavin: 0.06,
                niacin: 0.3,
                vitaminB6: 0.07,
                vitaminB12: 0,
                folate: 36,
                calcium: 40,
                iron: 0.2,
                magnesium: 11,
                phosphorus: 24,
                potassium: 260,
                sodium: 80,
                zinc: 0.1,
                selenium: 0.4,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very low calorie, crunchy, great with peanut butter",
            nameFr: "Céleri",
            nameEs: "Apio",
            nameHe: "סלרי",
            notesFr: "Très faible en calories, croquant, excellent avec du beurre d'arachide",
            notesEs: "Muy bajo en calorías, crujiente, excelente con mantequilla de maní",
            notesHe: "דל קלוריות מאוד, פריך, מעולה עם חמאת בוטנים"
        ),
        
        // Onions
        FoodItem(
            id: UUID(),
            name: "Onions",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 40,
                protein: 1.1,
                carbohydrates: 9.3,
                fat: 0.1,
                fiber: 1.7,
                sugar: 4.2,
                vitaminA: 0,
                vitaminC: 7,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 0.4,
                thiamin: 0.05,
                riboflavin: 0.03,
                niacin: 0.1,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 19,
                calcium: 23,
                iron: 0.2,
                magnesium: 10,
                phosphorus: 29,
                potassium: 146,
                sodium: 4,
                zinc: 0.2,
                selenium: 0.5,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Fundamental cooking ingredient, rich in antioxidants",
            nameFr: "Oignons",
            nameEs: "Cebollas",
            nameHe: "בצל",
            notesFr: "Ingrédient de cuisine fondamental, riche en antioxydants",
            notesEs: "Ingrediente fundamental de cocina, rico en antioxidantes",
            notesHe: "מרכיב בישול בסיסי, עשיר בנוגדי חמצון"
        ),
        
        // Garlic
        FoodItem(
            id: UUID(),
            name: "Garlic",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 149,
                protein: 6.4,
                carbohydrates: 33,
                fat: 0.5,
                fiber: 2.1,
                sugar: 1.0,
                vitaminA: 0,
                vitaminC: 31,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 1.7,
                thiamin: 0.20,
                riboflavin: 0.11,
                niacin: 0.7,
                vitaminB6: 1.24,
                vitaminB12: 0,
                folate: 3,
                calcium: 181,
                iron: 1.7,
                magnesium: 25,
                phosphorus: 153,
                potassium: 401,
                sodium: 17,
                zinc: 1.2,
                selenium: 14.2,
                omega3: 0.0,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Potent flavor enhancer with antimicrobial properties",
            nameFr: "Ail",
            nameEs: "Ajo",
            nameHe: "שום",
            notesFr: "Exhausteur de goût puissant avec propriétés antimicrobiennes",
            notesEs: "Potente realzador de sabor con propiedades antimicrobianas",
            notesHe: "מעצים טעם חזק עם תכונות אנטי-מיקרוביאליות"
        ),
        
        // Mushrooms (Button)
        FoodItem(
            id: UUID(),
            name: "Button Mushrooms",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 22,
                protein: 3.1,
                carbohydrates: 3.3,
                fat: 0.3,
                fiber: 1.0,
                sugar: 2.0,
                vitaminA: 0,
                vitaminC: 2,
                vitaminD: 0.2,
                vitaminE: 0.0,
                vitaminK: 0,
                thiamin: 0.08,
                riboflavin: 0.40,
                niacin: 3.6,
                vitaminB6: 0.10,
                vitaminB12: 0.04,
                folate: 17,
                calcium: 3,
                iron: 0.5,
                magnesium: 9,
                phosphorus: 86,
                potassium: 318,
                sodium: 5,
                zinc: 0.5,
                selenium: 9.3,
                omega3: 0.0,
                omega6: 0.2,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Good source of selenium and B vitamins, umami flavor",
            nameFr: "Champignons de Paris",
            nameEs: "Champiñones",
            nameHe: "פטריות",
            notesFr: "Bonne source de sélénium et vitamines B, saveur umami",
            notesEs: "Buena fuente de selenio y vitaminas B, sabor umami",
            notesHe: "מקור טוב לסלניום ווויטמיני B, טעם אומאמי"
        ),
        
        // Eggplant
        FoodItem(
            id: UUID(),
            name: "Eggplant",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 25,
                protein: 1.0,
                carbohydrates: 6,
                fat: 0.2,
                fiber: 3.0,
                sugar: 3.5,
                vitaminA: 1,
                vitaminC: 2,
                vitaminD: 0,
                vitaminE: 0.3,
                vitaminK: 3.5,
                thiamin: 0.04,
                riboflavin: 0.04,
                niacin: 0.6,
                vitaminB6: 0.08,
                vitaminB12: 0,
                folate: 22,
                calcium: 9,
                iron: 0.2,
                magnesium: 14,
                phosphorus: 24,
                potassium: 229,
                sodium: 2,
                zinc: 0.2,
                selenium: 0.3,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Absorbs flavors well, great for Mediterranean dishes",
            nameFr: "Aubergine",
            nameEs: "Berenjena",
            nameHe: "חציל",
            notesFr: "Absorbe bien les saveurs, excellent pour les plats méditerranéens",
            notesEs: "Absorbe bien los sabores, excelente para platos mediterráneos",
            notesHe: "סופג טעמים היטב, מעולה למנות ים-תיכוניות"
        ),
        
        // Artichoke
        FoodItem(
            id: UUID(),
            name: "Artichoke",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 47,
                protein: 3.3,
                carbohydrates: 11,
                fat: 0.2,
                fiber: 5.4,
                sugar: 1.0,
                vitaminA: 13,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 0.2,
                vitaminK: 15,
                thiamin: 0.07,
                riboflavin: 0.07,
                niacin: 1.0,
                vitaminB6: 0.12,
                vitaminB12: 0,
                folate: 68,
                calcium: 44,
                iron: 1.3,
                magnesium: 60,
                phosphorus: 90,
                potassium: 370,
                sodium: 94,
                zinc: 0.5,
                selenium: 0.2,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Very high in fiber and folate, elegant appetizer",
            nameFr: "Artichaut",
            nameEs: "Alcachofa",
            nameHe: "ארטישוק",
            notesFr: "Très riche en fibres et folate, apéritif élégant",
            notesEs: "Muy alto en fibra y folato, aperitivo elegante",
            notesHe: "עשיר מאוד בסיבים וחומצה פולית, מתאבן אלגנטי"
        ),
        
        // Leeks
        FoodItem(
            id: UUID(),
            name: "Leeks",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 61,
                protein: 1.5,
                carbohydrates: 14,
                fat: 0.3,
                fiber: 1.8,
                sugar: 3.9,
                vitaminA: 83,
                vitaminC: 12,
                vitaminD: 0,
                vitaminE: 0.9,
                vitaminK: 47,
                thiamin: 0.06,
                riboflavin: 0.03,
                niacin: 0.4,
                vitaminB6: 0.23,
                vitaminB12: 0,
                folate: 64,
                calcium: 59,
                iron: 2.1,
                magnesium: 28,
                phosphorus: 35,
                potassium: 180,
                sodium: 20,
                zinc: 0.1,
                selenium: 1.0,
                omega3: 0.1,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Mild onion flavor, excellent in soups and stews",
            nameFr: "Poireaux",
            nameEs: "Puerros",
            nameHe: "כרישה",
            notesFr: "Saveur d'oignon douce, excellent dans les soupes et ragoûts",
            notesEs: "Sabor suave a cebolla, excelente en sopas y guisos",
            notesHe: "טעם בצל עדין, מעולה במרקים ותבשילים"
        ),
        
        // Turnips
        FoodItem(
            id: UUID(),
            name: "Turnips",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 28,
                protein: 0.9,
                carbohydrates: 6.4,
                fat: 0.1,
                fiber: 1.8,
                sugar: 3.8,
                vitaminA: 0,
                vitaminC: 21,
                vitaminD: 0,
                vitaminE: 0.0,
                vitaminK: 0.1,
                thiamin: 0.04,
                riboflavin: 0.03,
                niacin: 0.4,
                vitaminB6: 0.09,
                vitaminB12: 0,
                folate: 15,
                calcium: 30,
                iron: 0.3,
                magnesium: 11,
                phosphorus: 27,
                potassium: 191,
                sodium: 67,
                zinc: 0.3,
                selenium: 0.7,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Root vegetable with peppery flavor, good roasted",
            nameFr: "Navets",
            nameEs: "Nabos",
            nameHe: "לפת",
            notesFr: "Légume racine au goût poivré, bon rôti",
            notesEs: "Vegetal de raíz con sabor picante, bueno asado",
            notesHe: "ירק שורש עם טעם חריף, טוב צלוי"
        ),
        
        // Parsnips
        FoodItem(
            id: UUID(),
            name: "Parsnips",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 75,
                protein: 1.2,
                carbohydrates: 18,
                fat: 0.3,
                fiber: 4.9,
                sugar: 4.8,
                vitaminA: 0,
                vitaminC: 17,
                vitaminD: 0,
                vitaminE: 1.5,
                vitaminK: 22,
                thiamin: 0.09,
                riboflavin: 0.05,
                niacin: 0.7,
                vitaminB6: 0.09,
                vitaminB12: 0,
                folate: 67,
                calcium: 36,
                iron: 0.6,
                magnesium: 29,
                phosphorus: 71,
                potassium: 375,
                sodium: 10,
                zinc: 0.6,
                selenium: 1.8,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Sweet root vegetable, excellent roasted or in soups",
            nameFr: "Panais",
            nameEs: "Chirivías",
            nameHe: "גזר לבן",
            notesFr: "Légume racine sucré, excellent rôti ou dans les soupes",
            notesEs: "Vegetal de raíz dulce, excelente asado o en sopas",
            notesHe: "ירק שורש מתוק, מעולה צלוי או במרקים"
        ),
        
        // Okra
        FoodItem(
            id: UUID(),
            name: "Okra",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 33,
                protein: 1.9,
                carbohydrates: 7.5,
                fat: 0.2,
                fiber: 3.2,
                sugar: 1.5,
                vitaminA: 36,
                vitaminC: 23,
                vitaminD: 0,
                vitaminE: 0.4,
                vitaminK: 32,
                thiamin: 0.20,
                riboflavin: 0.06,
                niacin: 1.0,
                vitaminB6: 0.22,
                vitaminB12: 0,
                folate: 60,
                calcium: 82,
                iron: 0.6,
                magnesium: 57,
                phosphorus: 61,
                potassium: 299,
                sodium: 7,
                zinc: 0.6,
                selenium: 0.7,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "High in folate and vitamin C, popular in Southern cuisine",
            nameFr: "Gombo",
            nameEs: "Quimbombó",
            nameHe: "במיה",
            notesFr: "Riche en folate et vitamine C, populaire dans la cuisine du Sud",
            notesEs: "Alto en folato y vitamina C, popular en la cocina sureña",
            notesHe: "עשיר בחומצה פולית ווויטמין C, פופולרי במטבח הדרומי"
        ),
        
        // Swiss Chard
        FoodItem(
            id: UUID(),
            name: "Swiss Chard",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 19,
                protein: 1.8,
                carbohydrates: 3.7,
                fat: 0.2,
                fiber: 1.6,
                sugar: 1.1,
                vitaminA: 306,
                vitaminC: 30,
                vitaminD: 0,
                vitaminE: 1.9,
                vitaminK: 830,
                thiamin: 0.04,
                riboflavin: 0.09,
                niacin: 0.4,
                vitaminB6: 0.10,
                vitaminB12: 0,
                folate: 14,
                calcium: 51,
                iron: 1.8,
                magnesium: 81,
                phosphorus: 46,
                potassium: 379,
                sodium: 213,
                zinc: 0.4,
                selenium: 0.9,
                omega3: 0.0,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Extremely high in vitamin K, colorful stems and leaves",
            nameFr: "Bette à carde",
            nameEs: "Acelga",
            nameHe: "מנגולד",
            notesFr: "Extrêmement riche en vitamine K, tiges et feuilles colorées",
            notesEs: "Extremadamente alto en vitamina K, tallos y hojas coloridos",
            notesHe: "עשיר במיוחד בוויטמין K, גבעולים ועלים צבעוניים"
        ),
        
        // Bok Choy
        FoodItem(
            id: UUID(),
            name: "Bok Choy",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 13,
                protein: 1.5,
                carbohydrates: 2.2,
                fat: 0.2,
                fiber: 1.0,
                sugar: 1.2,
                vitaminA: 223,
                vitaminC: 45,
                vitaminD: 0,
                vitaminE: 0.1,
                vitaminK: 46,
                thiamin: 0.04,
                riboflavin: 0.07,
                niacin: 0.5,
                vitaminB6: 0.19,
                vitaminB12: 0,
                folate: 66,
                calcium: 105,
                iron: 0.8,
                magnesium: 19,
                phosphorus: 37,
                potassium: 252,
                sodium: 65,
                zinc: 0.2,
                selenium: 0.5,
                omega3: 0.0,
                omega6: 0.1,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Asian green high in calcium and vitamin C, mild flavor",
            nameFr: "Pak-choï",
            nameEs: "Bok choy",
            nameHe: "בוק צ'וי",
            notesFr: "Légume vert asiatique riche en calcium et vitamine C, saveur douce",
            notesEs: "Verde asiático alto en calcio y vitamina C, sabor suave",
            notesHe: "ירק אסייתי עשיר בסידן ווויטמין C, טעם עדין"
        ),
        
        // Watercress
        FoodItem(
            id: UUID(),
            name: "Watercress",
            category: .vegetables,
            nutritionalInfo: NutritionalInfo(
                calories: 11,
                protein: 2.3,
                carbohydrates: 1.3,
                fat: 0.1,
                fiber: 0.5,
                sugar: 0.2,
                vitaminA: 160,
                vitaminC: 43,
                vitaminD: 0,
                vitaminE: 1.0,
                vitaminK: 250,
                thiamin: 0.09,
                riboflavin: 0.12,
                niacin: 0.2,
                vitaminB6: 0.13,
                vitaminB12: 0,
                folate: 9,
                calcium: 120,
                iron: 0.2,
                magnesium: 21,
                phosphorus: 60,
                potassium: 330,
                sodium: 41,
                zinc: 0.1,
                selenium: 0.3,
                omega3: 0.2,
                omega6: 0.0,
                cholesterol: 0
            ),
            servingSize: 100,
            servingUnit: "g",
            isCustom: true,
            notes: "Peppery superfood, very high in vitamin K and calcium",
            nameFr: "Cresson",
            nameEs: "Berro",
            nameHe: "גרגיר מים",
            notesFr: "Superaliment poivré, très riche en vitamine K et calcium",
            notesEs: "Superalimento picante, muy alto en vitamina K y calcio",
            notesHe: "סופרפוד חריף, עשיר מאוד בוויטמין K וסידן"
        )
    ]
}
